/** 홈 화면의 "오늘의 ~" 선택 로직과 실전 표현 데이터 — 순수 모듈. */
import type { TranslationKey } from '../../../shared/i18n/keys';

/** 날짜(YYYY-MM-DD)를 시드로 결정적 난수를 뽑아 오늘 하루 동안은 항상 같은 결과가 나오게 한다 */
export function pickDaily<T>(items: T[], count: number, seed: string): T[] {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  const pool = [...items];
  const picked: T[] = [];
  while (picked.length < count && pool.length > 0) {
    h = (h * 1664525 + 1013904223) >>> 0;
    const idx = h % pool.length;
    picked.push(pool.splice(idx, 1)[0]);
  }
  return picked;
}

/** "오늘의 실전 표현" — 한국 거주 외국인이 바로 써먹는 상황별 표현.
 * 신조어 사전과는 다른 결의 콘텐츠라 별도 로컬 데이터로 관리한다(다른 화면의
 * HORANG_HINTS 등과 동일한 컨벤션 — 아직 사전 콘텐츠처럼 5개 언어로 번역하진 않음). */
export type Situation = 'cafe' | 'transit' | 'work' | 'health' | 'sns' | 'meal' | 'argument' | 'daily';

export const SITUATION_LABEL_KEY: Record<Situation, TranslationKey> = {
  cafe: 'situationCafe', transit: 'situationTransit', work: 'situationWork',
  health: 'situationHealth', sns: 'situationSns', meal: 'situationMeal',
  argument: 'situationArgument', daily: 'situationDaily',
};

/** 교과서 문장 금지 — 10~20대가 실제로 쓰는 말투로, 사투리도 간간이 섞는다(운영자 지시).
 * 사투리 항목은 글로스에 지역·상대(친구끼리 등)를 반드시 표기해 잘못 쓰는 일을 막는다. */
export type Expression = {
  situation: Situation; ko: string; en: string; ja: string; es: string; vi: string; de: string;
  /** 사투리 문장 — 히어로 배너가 매일 1개를 별도 슬롯으로 뽑는다(운영자 지시 2026-09-06) */
  dialect?: true;
  /** 문장 속 신조어가 사전에 있으면 그 단어 상세로 연결(표제어, words.id) */
  wordId?: string; wordLabel?: string;
};

/** 사전 예문과 동일한 규칙: ko/en UI는 영어 글로스, 나머지는 UI 언어(없으면 en 폴백). */
export const expressionGloss = (e: Expression, language: string) =>
  language === 'ko' || language === 'en' ? e.en : (e as Record<string, any>)[language] ?? e.en;

export const EXPRESSIONS: Expression[] = [
  { situation: 'cafe', ko: '아아 한 잔 주세요',
    en: 'One iced americano, please ("a-a" = iced americano slang)',
    ja: 'アイスアメリカーノひとつください(「アア」=アイスアメリカーノの略)',
    es: 'Un americano con hielo, por favor ("a-a" = jerga para americano helado)',
    vi: 'Cho một ly americano đá ("a-a" = tiếng lóng chỉ americano đá)',
    de: 'Einen Eis-Americano, bitte („a-a“ = Slang für Iced Americano)' },
  { situation: 'cafe', ko: '전 얼죽아예요',
    en: "I'm team iced-even-if-I-freeze (얼죽아 = iced americano no matter the season)",
    ja: '私は얼죽아です(얼죽아=凍え死んでもアイスアメリカーノ派)',
    es: 'Yo soy del equipo 얼죽아 (americano helado aunque me congele)',
    vi: 'Mình là hội 얼죽아 (chết cóng vẫn uống americano đá)',
    de: 'Ich bin Team 얼죽아 (Iced Americano, egal wie kalt es ist)',
    wordId: '136', wordLabel: '얼죽아' },
  { situation: 'transit', ko: '나 이번에 내려, 이따 봐',
    en: "I'm getting off here — see you later (texting a friend)",
    ja: 'ここで降りるね、また後で(友達へのメッセージ)',
    es: 'Me bajo aquí, nos vemos luego (mensaje a un amigo)',
    vi: 'Tớ xuống trạm này, gặp sau nhé (nhắn cho bạn bè)',
    de: 'Ich steige hier aus — bis später (an Freunde)' },
  { situation: 'transit', ko: '지금 지옥철이야, 숨도 못 쉬어',
    en: "I'm stuck in hell-train, can't even breathe (지옥철 = 지옥 hell + 지하철 subway, rush-hour crush)",
    ja: '今地獄鉄なんだけど、息もできない(지옥철=地獄+地下鉄、ラッシュのすし詰め)',
    es: 'Voy en el metro-infierno, no puedo ni respirar (지옥철 = infierno + metro en hora punta)',
    vi: 'Đang kẹt trong tàu-địa-ngục, thở không nổi (지옥철 = địa ngục + tàu điện giờ cao điểm)',
    de: 'Ich stecke in der Höllenbahn, kriege keine Luft (지옥철 = Hölle + U-Bahn zur Rushhour)',
    wordId: '217', wordLabel: '지옥철' },
  { situation: 'transit', dialect: true, ko: '언제 오노? 퍼뜩 온나',
    en: 'When are you coming? Hurry up! (Busan/Gyeongsang dialect, close friends only)',
    ja: 'いつ来るの?早く来い!(釜山・慶尚道の方言、親しい友達だけ)',
    es: '¿Cuándo vienes? ¡Date prisa! (dialecto de Busan/Gyeongsang, solo entre amigos íntimos)',
    vi: 'Bao giờ đến? Nhanh lên! (phương ngữ Busan/Gyeongsang, chỉ dùng với bạn thân)',
    de: 'Wann kommst du? Beeil dich! (Busan/Gyeongsang-Dialekt, nur unter engen Freunden)' },
  { situation: 'work', ko: '넵! 바로 확인하겠습니다',
    en: 'Got it! Checking right away (넵 = the eager work "yes" every young employee types)',
    ja: 'はい!すぐ確認します(「넵」=若手社員の定番の返事)',
    es: '¡Entendido! Lo reviso ahora mismo (넵 = el "sí" entusiasta del trabajo)',
    vi: 'Vâng ạ! Em kiểm tra ngay (넵 = kiểu "vâng" nhiệt tình nơi công sở)',
    de: 'Jawohl! Prüfe ich sofort (넵 = das eifrige Arbeits-„Ja“ junger Angestellter)',
    wordId: '4', wordLabel: '넵병' },
  { situation: 'work', ko: '오늘 칼퇴 각이에요',
    en: 'Today looks like an on-the-dot leave (칼퇴 = leaving sharp on time, 각 = "the vibe is right")',
    ja: '今日は定時退社できそう(칼퇴=時間ぴったりの退勤、각=「その流れ」)',
    es: 'Hoy pinta que salgo puntual (칼퇴 = salir del trabajo justo a la hora)',
    vi: 'Hôm nay chắc được về đúng giờ (칼퇴 = tan làm đúng giờ tăm tắp)',
    de: 'Heute sieht’s nach pünktlichem Feierabend aus (칼퇴 = auf die Minute gehen)',
    wordId: '170', wordLabel: '칼퇴' },
  { situation: 'health', ko: '어제부터 몸살 기운이 있어요',
    en: "I've felt achy and feverish since yesterday",
    ja: '昨日から体がだるくて熱っぽいです',
    es: 'Desde ayer me siento con malestar y algo de fiebre',
    vi: 'Từ hôm qua tôi thấy người mệt mỏi, ớn lạnh',
    de: 'Seit gestern fühle ich mich schlapp und fiebrig' },
  { situation: 'health', ko: '약빨이 잘 안 듣는 것 같아요',
    en: "The meds don't seem to kick in (약빨 = slangy word for a medicine's effect)",
    ja: '薬の効きがいまいちみたいです(약빨=薬の効き目を指すスラング)',
    es: 'Parece que la medicina no me hace efecto (약빨 = jerga para el efecto de un fármaco)',
    vi: 'Hình như thuốc không ngấm (약빨 = tiếng lóng chỉ tác dụng của thuốc)',
    de: 'Die Medizin scheint nicht anzuschlagen (약빨 = Slang für die Wirkung eines Medikaments)',
    wordId: '218', wordLabel: '약빨' },
  { situation: 'sns', ko: '스토리 봤어, 개웃겨 ㅋㅋ',
    en: 'Saw your story — hilarious (개- = slangy intensifier, friends only)',
    ja: 'ストーリー見たよ、めっちゃウケる ㅋㅋ(개-=強調のスラング、友達だけ)',
    es: 'Vi tu historia, qué risa ㅋㅋ (개- = intensificador de jerga, solo amigos)',
    vi: 'Xem story rồi, buồn cười xỉu ㅋㅋ (개- = từ nhấn mạnh kiểu lóng, chỉ với bạn bè)',
    de: 'Hab deine Story gesehen — zum Schreien ㅋㅋ (개- = Slang-Verstärker, nur unter Freunden)' },
  { situation: 'sns', ko: '맞팔해요!',
    en: "Let's follow each other! (맞팔 = mutual follow)",
    ja: '相互フォローしましょう!(맞팔=相互フォロー)',
    es: '¡Sigámonos mutuamente! (맞팔 = follow mutuo)',
    vi: 'Follow qua lại nhé! (맞팔 = follow lẫn nhau)',
    de: 'Lass uns gegenseitig folgen! (맞팔 = Mutual Follow)' },
  { situation: 'sns', ko: '완전 인생샷이다',
    en: 'That is THE shot of your life (인생샷 = best photo ever taken of you)',
    ja: '完全に人生最高の一枚だ(인생샷=人生でいちばんよく撮れた写真)',
    es: 'Es la foto de tu vida (인생샷 = la mejor foto que te han hecho)',
    vi: 'Đúng là bức ảnh để đời (인생샷 = tấm ảnh đẹp nhất đời)',
    de: 'Das ist DAS Foto deines Lebens (인생샷 = bestes Foto aller Zeiten)',
    wordId: '219', wordLabel: '인생샷' },
  { situation: 'meal', ko: '오늘은 제가 쏠게요',
    en: "Tonight's on me (쏘다 = to treat someone)",
    ja: '今日は私がおごります(쏘다=おごる)',
    es: 'Hoy invito yo (쏘다 = invitar)',
    vi: 'Hôm nay để mình khao (쏘다 = khao, bao cả nhóm)',
    de: 'Heute geht’s auf mich (쏘다 = einladen/spendieren)' },
  { situation: 'meal', ko: '저 술 잘 못 마셔요, 콜라로 할게요',
    en: "I'm not much of a drinker — I'll have a cola (natural way to pass)",
    ja: 'お酒は弱いので、コーラにします(自然な断り方)',
    es: 'No bebo mucho alcohol, tomaré una cola (forma natural de declinar)',
    vi: 'Mình không uống được rượu, cho mình cola nhé (cách từ chối tự nhiên)',
    de: 'Ich vertrage Alkohol nicht gut — ich nehme eine Cola (natürliches Ablehnen)' },
  { situation: 'meal', dialect: true, ko: '겁나 맛있어요',
    en: 'This is crazy good (겁나 = Jeolla-dialect "super", now used nationwide)',
    ja: 'めちゃくちゃおいしいです(겁나=全羅道方言の「すごく」、今は全国区)',
    es: 'Está buenísimo (겁나 = "súper" del dialecto de Jeolla, hoy usado en todo el país)',
    vi: 'Ngon dã man (겁나 = "cực kỳ" gốc phương ngữ Jeolla, giờ dùng khắp nơi)',
    de: 'Das schmeckt wahnsinnig gut (겁나 = Jeolla-Dialekt für „mega“, heute überall üblich)' },
  { situation: 'meal', dialect: true, ko: '마이 무라!',
    en: 'Dig in! (Busan/Gyeongsang dialect, banmal — close friends only)',
    ja: 'たくさん食べな!(釜山・慶尚道の方言でタメ口 — 親しい友達だけ)',
    es: '¡Come mucho! (dialecto de Busan/Gyeongsang, informal — solo amigos íntimos)',
    vi: 'Ăn nhiều vào! (phương ngữ Busan/Gyeongsang, suồng sã — chỉ với bạn thân)',
    de: 'Hau rein! (Busan/Gyeongsang-Dialekt, salopp — nur unter engen Freunden)' },
  { situation: 'work', ko: '퇴사 마렵다',
    en: 'I\'m dying to quit this job (마렵다 originally = "need the toilet"; young Koreans now use it for "craving X" — banmal, never in front of a boss)',
    ja: '仕事辞めたくてたまらない(마렵다=元は「トイレに行きたい」、今は若者言葉で「〜したくてたまらない」。タメ口で、上司の前では絶対に使わない)',
    es: 'Me muero por renunciar (마렵다 = originalmente "tener ganas de ir al baño"; hoy los jóvenes lo usan como "morirse de ganas de". Informal, nunca ante un superior)',
    vi: 'Thèm nghỉ việc quá (마렵다 = gốc là "mót đi vệ sinh", giới trẻ nay dùng cho "thèm kinh khủng". Suồng sã, tuyệt đối không dùng trước cấp trên)',
    de: 'Ich will nur noch kündigen (마렵다 = ursprünglich „aufs Klo müssen“, heute Jugendslang für „unbedingt wollen“. Salopp, niemals vor Vorgesetzten)' },
  { situation: 'sns', ko: '알 수 없는 알고리즘이 나를 여기로 이끌었다',
    en: 'The mysterious algorithm led me here (the staple YouTube/Reels comment when a random recommended clip sucks you in)',
    ja: '謎のアルゴリズムが私をここへ導いた(おすすめに突然出てきた動画にハマった時の定番コメント)',
    es: 'Un algoritmo misterioso me trajo hasta aquí (comentario típico de YouTube cuando un vídeo aleatorio te engancha)',
    vi: 'Thuật toán bí ẩn đã đưa tôi đến đây (bình luận kinh điển trên YouTube khi bị video gợi ý cuốn vào)',
    de: 'Ein unerklärlicher Algorithmus hat mich hierhergeführt (Standard-Kommentar auf YouTube, wenn ein zufällig empfohlenes Video einen fesselt)' },
  { situation: 'meal', ko: '이거 완전 겉바속촉이다',
    en: 'This is properly crispy outside, soft inside (겉바속촉 = 겉은 바삭 속은 촉촉 — the go-to food compliment for fried chicken, pastries, cutlets)',
    ja: 'これ完全に外はサクサク中はしっとり(겉바속촉=「外カリ中しっとり」の略、チキンやパンを褒める定番の言い回し)',
    es: 'Esto está crujiente por fuera y jugoso por dentro (겉바속촉 = abreviatura de esa idea; el piropo gastronómico por excelencia)',
    vi: 'Món này đúng chuẩn ngoài giòn trong mềm (겉바속촉 = viết tắt của "ngoài giòn trong ẩm", lời khen món ăn quen thuộc nhất)',
    de: 'Das ist außen knusprig, innen saftig (겉바속촉 = Kurzwort dafür, das Standard-Foodkompliment)' },
  { situation: 'transit', ko: '막차 끊기기 전에 가야 돼',
    en: 'I have to go before the last train stops running (막차 끊기다 = the last train/bus is gone — the classic Korean exit line from a night out)',
    ja: '終電がなくなる前に行かなきゃ(막차 끊기다=終電・終バスがなくなる。飲み会を抜ける時の定番)',
    es: 'Tengo que irme antes de que se acabe el último metro (막차 끊기다 = ya no hay último tren/bus; la excusa clásica para irse de una quedada)',
    vi: 'Tớ phải đi trước khi hết chuyến tàu cuối (막차 끊기다 = tàu/xe buýt cuối đã hết; câu rút lui kinh điển khi đi chơi khuya)',
    de: 'Ich muss los, bevor die letzte Bahn weg ist (막차 끊기다 = letzte Bahn/Bus fährt nicht mehr; der Klassiker beim Aufbruch)' },
  { situation: 'cafe', ko: '여기 카공하기 좋다던데',
    en: 'I heard this place is good for studying at (카공 = 카페 공부, studying in a café; 카공족 = the people who camp there all day)',
    ja: 'ここ、カフェ勉するのに良いらしいよ(카공=カフェで勉強すること、카공족=カフェに長居して勉強する人たち)',
    es: 'Dicen que este sitio es bueno para estudiar (카공 = estudiar en una cafetería; 카공족 = los que se pasan el día allí estudiando)',
    vi: 'Nghe nói quán này học bài hợp lắm (카공 = học bài ở quán cà phê; 카공족 = hội ngồi quán cả ngày để học)',
    de: 'Hier soll man gut lernen können (카공 = im Café lernen; 카공족 = die Leute, die dort den ganzen Tag sitzen)' },
  { situation: 'sns', ko: '오늘도 오운완 성공',
    en: "Today's workout: done ✅ (오운완 = '오늘 운동 완료', the gym check-in hashtag everyone posts)",
    ja: '今日もオウンワン成功(오운완=「今日の運動完了」、SNS定番の筋トレ報告タグ)',
    es: '¡Entrenamiento de hoy, completado! (오운완 = \'ejercicio de hoy terminado\', el hashtag fitness que todo el mundo publica)',
    vi: "Hôm nay cũng hoàn thành buổi tập (오운완 = 'hôm nay tập xong', hashtag khoe tập gym quen thuộc)",
    de: 'Heutiges Workout: geschafft! (오운완 = „heutiges Training abgeschlossen“, der Fitness-Hashtag schlechthin)' },
  { situation: 'cafe', ko: '저 얼죽아라 겨울에도 아아 마셔요',
    en: "I'm an 'eoljukah' — I drink iced americano even in winter (얼죽아 = '얼어 죽어도 아이스 아메리카노', freeze to death but still iced americano; a near-universal Korean self-intro)",
    ja: '私「オルジュガ」なので冬でもアイスアメリカーノです(얼죽아=「凍え死んでもアイスアメリカーノ」、韓国では定番の自己紹介ネタ)',
    es: "Soy 'eoljukah': tomo americano con hielo hasta en invierno (얼죽아 = 'aunque me muera de frío, americano helado')",
    vi: "Mình là 'eoljukah', mùa đông vẫn uống americano đá (얼죽아 = 'chết cóng cũng phải americano đá')",
    de: 'Ich bin ein „Eoljukah“ — ich trinke selbst im Winter Iced Americano (얼죽아 = „lieber erfrieren als heißer Kaffee“)' },
  { situation: 'transit', ko: '출근길 진짜 지옥철이야',
    en: "The morning commute is a total hell-train (지옥철 = 지옥 'hell' + 전철 'subway'; the crush-packed rush-hour train, esp. Seoul Line 9. Banmal — to friends)",
    ja: '通勤ラッシュ、まじで地獄鉄だよ(지옥철=地獄+電車、超満員のラッシュ時の電車。特にソウル地下鉄9号線。タメ口なので友達に)',
    es: "El viaje al trabajo es un tren infernal (지옥철 = 'infierno' + 'metro'; el vagón repleto en hora punta, sobre todo la línea 9 de Seúl. Informal, entre amigos)",
    vi: "Chuyến tàu đi làm đúng là địa ngục (지옥철 = 'địa ngục' + 'tàu điện'; tàu chật cứng giờ cao điểm, nhất là tuyến 9 Seoul. Thân mật, với bạn bè)",
    de: 'Der Weg zur Arbeit ist die reinste Höllenbahn (지옥철 = „Hölle“ + „U-Bahn“; die überfüllte Rush-hour-Bahn, v. a. Seouler Linie 9. Salopp, unter Freunden)',
    wordId: '217', wordLabel: '지옥철' },
  { situation: 'work', ko: '일하다 갑자기 현타 온다',
    en: "Mid-work and suddenly hit by a reality check (현타 = the deflating moment you snap back to reality and wonder what you're even doing. Banmal — to friends/peers)",
    ja: '仕事中に急に我に返る(현타=夢中だった状態から現実に引き戻されて虚しくなる瞬間。タメ口なので友達・同僚に)',
    es: 'Trabajando y de repente me da el bajón de realidad (현타 = el momento en que aterrizas en la realidad y todo te parece absurdo. Informal, entre amigos/colegas)',
    vi: 'Đang làm việc tự dưng thấy hụt hẫng, tỉnh cả người (현타 = khoảnh khắc bừng tỉnh về thực tại và thấy trống rỗng. Thân mật, với bạn bè/đồng nghiệp)',
    de: 'Mitten in der Arbeit trifft mich plötzlich der Realitäts-Schock (현타 = der Moment, in dem du in der Realität landest und alles sinnlos wirkt. Salopp, unter Freunden/Kollegen)' },
  { situation: 'meal', dialect: true, ko: '우리가 남이가',
    en: "Come on, we're not strangers (Busan/Gyeongsang dialect for '우리가 남이냐'; said when treating someone or doing them a favour. Made famous by the 2001 film 친구. Banmal — close friends only)",
    ja: '水くさいこと言うなよ、俺らの仲だろ(釜山・慶尚道の方言で「우리가 남이냐」。おごる時や頼まれ事を引き受ける時に。2001年の映画『友へ チング』で有名に。タメ口なので親しい友達だけ)',
    es: "Anda ya, que no somos extraños (dialecto de Busan/Gyeongsang de '우리가 남이냐'; se dice al invitar a alguien o hacerle un favor. Lo popularizó la película 친구 (2001). Informal, solo entre amigos íntimos)",
    vi: "Bọn mình đâu phải người dưng (phương ngữ Busan/Gyeongsang của '우리가 남이냐'; nói khi bao bạn hoặc giúp bạn một việc. Nổi tiếng nhờ phim 친구 (2001). Suồng sã, chỉ với bạn thân)",
    de: 'Ach was, wir sind doch keine Fremden (Busan/Gyeongsang-Dialekt für „우리가 남이냐“; sagt man, wenn man jemanden einlädt oder ihm einen Gefallen tut. Bekannt durch den Film 친구 (2001). Salopp — nur unter engen Freunden)' },
  { situation: 'work', dialect: true, ko: '살아있네',
    en: "Still got it! (Busan-accented '살아 있네', lit. 'it's alive'; an admiring 'you've still got the touch' when someone surprises you with their skill. From the 2012 film 범죄와의 전쟁. Banmal — peers and friends)",
    ja: '腕は衰えてないな(釜山なまりの「살아 있네」、直訳「生きてるな」。相手が予想以上の腕前を見せた時の感嘆。2012年の映画『悪いやつら』から。タメ口で同僚・友達に)',
    es: "¡Sigues en forma! (con acento de Busan, '살아 있네', lit. 'está vivo'; admiración cuando alguien te sorprende con su habilidad. De la película 범죄와의 전쟁 (2012). Informal, entre iguales y amigos)",
    vi: "Vẫn còn phong độ ghê! (giọng Busan, '살아 있네', nghĩa đen 'còn sống'; câu trầm trồ khi ai đó khiến bạn bất ngờ vì tay nghề. Từ phim 범죄와의 전쟁 (2012). Thân mật, với bạn bè đồng trang lứa)",
    de: 'Du hast es immer noch drauf! (in Busan-Färbung „살아 있네“, wörtl. „es lebt“; anerkennender Ausruf, wenn jemand einen mit seinem Können überrascht. Aus dem Film 범죄와의 전쟁 (2012). Salopp — unter Gleichrangigen und Freunden)' },
  { situation: 'sns', ko: '이거 폼 미쳤다',
    en: "This is insanely good (폼 미쳤다 = lit. 'the form has gone crazy'; a top-tier compliment for someone's skill, style, or a product's design. Banmal — friends only)",
    ja: 'これ、ヤバいくらいカッコいい(폼 미쳤다=直訳「フォームが狂った」。実力・スタイル・デザインを最上級に褒める言い方。タメ口なので友達だけ)',
    es: "Esto está de locos de bueno (폼 미쳤다 = lit. 'la forma se volvió loca'; máximo elogio al talento, al estilo o al diseño de algo. Informal, solo entre amigos)",
    vi: "Cái này đỉnh phát điên (폼 미쳤다 = nghĩa đen 'phong độ phát điên'; lời khen đỉnh nhất cho kỹ năng, phong cách hay thiết kế. Thân mật, chỉ với bạn bè)",
    de: 'Das ist der absolute Wahnsinn (폼 미쳤다 = wörtl. „die Form ist verrückt geworden“; höchstes Lob für Können, Stil oder Design. Salopp, nur unter Freunden)' },
  { situation: 'work', ko: '아 진짜 킹받네',
    en: "Ugh, this is SO infuriating (킹받다 = 열받다 'to get mad' with King- as an intensifier; joking, exaggerated annoyance, not real rage. Banmal — never to a boss)",
    ja: 'あー、まじでムカつく(킹받다=「열받다(腹が立つ)」に King を付けた強調表現。本気の怒りではなく大げさに言うネタ。タメ口で上司には使わない)',
    es: "Ay, qué rabia me da (킹받다 = '열받다' enfadarse + King como intensificador; enfado exagerado y en broma, no ira real. Informal, nunca con un superior)",
    vi: "Trời ơi bực dễ sợ (킹받다 = '열받다' bực mình + King để nhấn mạnh; kiểu bực đùa cho vui chứ không phải giận thật. Thân mật, không dùng với cấp trên)",
    de: 'Ah, das nervt mich sowas von (킹받다 = „열받다“ sich ärgern + King als Verstärker; übertriebener Spaß-Ärger, kein echter Zorn. Salopp, nie gegenüber Vorgesetzten)' },
  { situation: 'meal', ko: '이건 국룰이지',
    en: "This is just the national rule (국룰 = 국민 'nation' + rule; the unwritten thing everyone does — e.g. fried chicken with beer. Banmal, said half-jokingly)",
    ja: 'これは国民的ルールでしょ(국룰=国民+rule。誰もが当然そうする暗黙の決まり。例:チキンにはビール。タメ口で半分冗談っぽく)',
    es: "Esto es la regla nacional (국룰 = 'nación' + rule; lo que todo el mundo hace sin que nadie lo diga, p. ej. pollo frito con cerveza. Informal y medio en broma)",
    vi: "Cái này là luật bất thành văn rồi (국룰 = 'quốc dân' + rule; điều ai cũng mặc định làm, ví dụ gà rán phải đi với bia. Thân mật, nói nửa đùa)",
    de: 'Das ist quasi Staatsgesetz (국룰 = „Nation“ + rule; das ungeschriebene Ding, das alle machen, z. B. frittiertes Hähnchen mit Bier. Salopp, halb im Scherz)' },
  { situation: 'cafe', ko: '여기 오픈런 해야 된대',
    en: 'They say you have to line up before this place opens (오픈런 = open + run; getting there before opening to beat the queue at hot cafés and shops)',
    ja: 'ここ、開店前から並ばないとダメらしいよ(오픈런=open+run。人気カフェや店で開店前から並んで一番乗りすること)',
    es: "Dicen que aquí hay que hacer 'open run' (오픈런 = open + run; llegar antes de que abran para adelantarse a la cola en cafés y tiendas de moda)",
    vi: 'Nghe nói chỗ này phải xếp hàng từ trước giờ mở cửa (오픈런 = open + run; đến trước giờ mở cửa để giành chỗ ở quán/cửa hàng hot)',
    de: 'Hier muss man wohl vor der Öffnung anstehen (오픈런 = open + run; vor Ladenöffnung anstehen, um in angesagten Cafés und Shops die Ersten zu sein)' },
  { situation: 'health', ko: '수액 맞고 왔어요',
    en: "I went and got an IV drip (수액 = IV fluids; young Koreans routinely get one at a clinic for a bad cold, stomach flu or sheer exhaustion — 'one bottle beats a day of rest')",
    ja: '点滴を打ってきました(수액=点滴。韓国の若者はひどい風邪・胃腸炎・疲労で気軽にクリニックで点滴を受ける)',
    es: 'Fui a que me pusieran suero (수액 = suero intravenoso; en Corea los jóvenes van a la clínica a ponérselo por un resfriado fuerte, gastroenteritis o puro agotamiento)',
    vi: 'Em vừa đi truyền nước về (수액 = truyền dịch; giới trẻ Hàn hay ra phòng khám truyền nước khi cảm nặng, đau bụng hay kiệt sức)',
    de: 'Ich war eine Infusion bekommen (수액 = Infusion; junge Koreaner lassen sich bei schwerer Erkältung, Magen-Darm-Infekt oder Erschöpfung ganz selbstverständlich eine legen)' },
  { situation: 'work', dialect: true, ko: '폭싹 속았수다',
    en: "Thank you, you've worked so hard (Jeju dialect for 정말 수고하셨습니다 — NOT '속다/to be fooled'. Title of the 2025 Netflix series. Polite, fine to say to anyone)",
    ja: '本当にお疲れさまでした(済州方言。「騙された」という意味ではない。2025年Netflixドラマの題名。丁寧な言い方で誰にでも使える)',
    es: "Muchas gracias por su esfuerzo (dialecto de Jeju para '정말 수고하셨습니다'; no significa 'ser engañado'. Título de la serie de Netflix de 2025. Es cortés, se puede decir a cualquiera)",
    vi: "Anh/chị đã vất vả nhiều rồi (phương ngữ Jeju của '정말 수고하셨습니다'; không phải nghĩa 'bị lừa'. Tên phim Netflix 2025. Lịch sự, nói với ai cũng được)",
    de: 'Vielen Dank für Ihre Mühe (Jeju-Dialekt für „정말 수고하셨습니다“; heißt NICHT „getäuscht werden“. Titel der Netflix-Serie von 2025. Höflich, gegenüber jedem sagbar)' },
  { situation: 'sns', dialect: true, ko: '뭣이 중헌디',
    en: "What even matters here? (Jeolla dialect for '뭐가 중요한데'; the 2016 film 곡성 turned it into a national catchphrase for 'you're missing the whole point'. Banmal — friends, or as a comment/meme)",
    ja: '何が大事なんだよ(全羅道方言で「뭐가 중요한데」。2016年の映画『哭声/コクソン』で全国的な流行語に。「話の本質を外している」と突っ込む言い方。タメ口で友達に、またはコメント・ミームとして)',
    es: "¿Qué es lo importante aquí? (dialecto de Jeolla de '뭐가 중요한데'; la película 곡성 (2016) lo convirtió en frase nacional para decir 'te estás perdiendo lo esencial'. Informal, entre amigos o como meme)",
    vi: "Rốt cuộc cái gì mới quan trọng? (phương ngữ Jeolla của '뭐가 중요한데'; phim 곡성 (2016) biến nó thành câu cửa miệng toàn quốc để nói 'bạn đang lạc đề rồi'. Thân mật, với bạn bè hoặc dùng làm bình luận/meme)",
    de: 'Was ist denn hier überhaupt wichtig? (Jeolla-Dialekt für „뭐가 중요한데“; der Film 곡성 (2016) machte es landesweit zum Spruch für „du verfehlst den Punkt“. Salopp — unter Freunden oder als Kommentar/Meme)' },
  { situation: 'cafe', dialect: true, ko: '워뗘? 환장하쥬?',
    en: "How is it? Drives you crazy, right? (Chungcheong dialect: 워뗘 = 어때, 환장하쥬 = 환장하겠죠 'it's crazy good'. The 용식 character's signature style in the 2019 drama 동백꽃 필 무렵. Playful — friends or people you're close to)",
    ja: 'どう?たまんないでしょ?(忠清道方言。워뗘=어때、환장하쥬=たまらないでしょ。2019年ドラマ『椿の花咲く頃』のヨンシク流の言い回し。おどけた言い方なので友達や親しい相手に)',
    es: "¿Qué tal? Es una locura, ¿a que sí? (dialecto de Chungcheong: 워뗘 = 어때, 환장하쥬 = 'te vuelve loco', en buen sentido. El estilo del personaje 용식 en la serie de 2019 동백꽃 필 무렵. Es juguetón: con amigos o gente de confianza)",
    vi: "Sao? Mê luôn đúng không? (phương ngữ Chungcheong: 워뗘 = 어때, 환장하쥬 = 'phát cuồng lên đấy' theo nghĩa tốt. Kiểu nói của nhân vật 용식 trong phim 2019 동백꽃 필 무렵. Vui đùa — dùng với bạn bè hoặc người thân thiết)",
    de: 'Und? Der Wahnsinn, oder? (Chungcheong-Dialekt: 워뗘 = 어때, 환장하쥬 = „macht dich verrückt“, positiv gemeint. Der Sprechstil der Figur 용식 aus der Serie 동백꽃 필 무렵 (2019). Verspielt — unter Freunden oder Vertrauten)' },
  { situation: 'cafe', ko: '카페인 수혈 좀 해야겠다',
    en: 'I need a caffeine transfusion (수혈 = a blood transfusion; Koreans joke that coffee goes straight into the vein. Banmal — say it to friends)',
    ja: 'カフェイン“輸血”しなきゃ(수혈=輸血。コーヒーを血管に直接入れる勢いで飲む、という定番の冗談。タメ口なので友達に)',
    es: 'Necesito una transfusión de cafeína (수혈 = transfusión de sangre; en Corea se bromea con que el café se inyecta en vena. Informal, entre amigos)',
    vi: "Phải đi 'truyền' cà phê thôi (수혈 = truyền máu; người Hàn hay đùa rằng cà phê được truyền thẳng vào ven. Thân mật, nói với bạn bè)",
    de: 'Ich brauche eine Koffein-Transfusion (수혈 = Bluttransfusion; in Korea scherzt man, der Kaffee komme direkt in die Vene. Salopp — unter Freunden)' },
  { situation: 'sns', ko: '나 읽씹당했어',
    en: 'I got left on read (읽씹 = 읽다 read + 씹다 ignore; the message shows as read but no reply ever comes). Banmal — friends only',
    ja: '既読スルーされた(읽씹=읽다 読む+씹다 無視する。既読はついたのに返信が来ない状態。タメ口なので友達だけに)',
    es: 'Me dejaron en visto (읽씹 = 읽다 leer + 씹다 ignorar; el mensaje aparece leído pero nunca llega respuesta. Informal, solo entre amigos)',
    vi: 'Tớ bị seen không rep (읽씹 = 읽다 đọc + 씹다 lơ đi; tin nhắn đã xem nhưng không có hồi âm. Thân mật, chỉ dùng với bạn bè)',
    de: 'Ich wurde auf Gelesen sitzen gelassen (읽씹 = 읽다 lesen + 씹다 ignorieren; die Nachricht ist gelesen, aber es kommt keine Antwort. Salopp — nur unter Freunden)' },
  { situation: 'health', ko: '요즘 체력이 완전 방전됐어요',
    en: "My battery's completely dead lately (방전 = a battery running flat; Koreans describe burnout as being discharged. Polite -요 form, fine to say to a doctor)",
    ja: '最近、体力が完全に“放電”しました(방전=バッテリー切れ。疲れ果てた状態をバッテリーに例える。丁寧語なので医師にも使える)',
    es: 'Últimamente tengo la batería a cero (방전 = batería descargada; en Corea el agotamiento se describe así. Forma cortés en -요, apropiada con el médico)',
    vi: 'Dạo này thể lực cạn sạch pin rồi ạ (방전 = hết pin; người Hàn ví kiệt sức như pin cạn. Thể lịch sự -요, nói với bác sĩ được)',
    de: 'In letzter Zeit ist mein Akku völlig leer (방전 = entladener Akku; Erschöpfung wird in Korea so beschrieben. Höfliche -요-Form, auch beim Arzt passend)' },
  { situation: 'meal', ko: '우리 N빵하자',
    en: "Let's just split it evenly (N빵 = divide the bill by N people; what 20s–30s say instead of 더치페이. Note: N빵 splits the total equally, while 더치페이 means each pays for what they ate. Banmal — friends)",
    ja: '割り勘にしよう(N빵=人数Nで割る。20~30代が더치페이の代わりに使う言い方。N빵は総額を等分、더치페이は各自が食べた分を払う、という違いがある。タメ口なので友達に)',
    es: 'Vamos a dividirlo entre todos (N빵 = dividir la cuenta entre N; así lo dicen los de 20-30 años en vez de 더치페이. Ojo: N빵 reparte el total a partes iguales; 더치페이 es que cada uno pague lo suyo. Informal, entre amigos)',
    vi: 'Mình chia đều tiền đi (N빵 = chia hóa đơn cho N người; giới 20-30 tuổi dùng thay cho 더치페이. Lưu ý: N빵 là chia đều tổng tiền, còn 더치페이 là ai ăn gì trả nấy. Thân mật, với bạn bè)',
    de: 'Lass uns einfach durch alle teilen (N빵 = die Rechnung durch N teilen; so sagen es 20- bis 30-Jährige statt 더치페이. Achtung: Bei N빵 wird die Gesamtsumme gleich geteilt, bei 더치페이 zahlt jeder das Eigene. Salopp — unter Freunden)' },
  { situation: 'work', dialect: true, ko: '니가 가라 하와이',
    en: "You go to Hawaii yourself (Busan/Gyeongsang dialect, from the 2001 film 친구; now the stock way to bounce back a suggestion you don't want — 'after you'. Joking banmal — close friends only, never to a boss)",
    ja: 'ハワイにはお前が行けよ(釜山・慶尚道方言。2001年の映画『友へ チング』の名台詞で、今は自分がやりたくない提案を相手に投げ返す決まり文句。ふざけたタメ口なので親しい友達だけ、上司には厳禁)',
    es: "A Hawái vas tú (dialecto de Busan/Gyeongsang, de la película 친구 (2001); hoy es la frase hecha para devolverle a alguien una propuesta que no te apetece: 've tú'. Informal y en broma: solo entre amigos íntimos, nunca con un superior)",
    vi: "Hawaii thì cậu đi đi (phương ngữ Busan/Gyeongsang, thoại phim 친구 (2001); nay thành câu cửa miệng để đẩy ngược lại đề nghị mình không muốn — 'cậu đi trước đi'. Đùa, thân mật — chỉ với bạn thân, tuyệt đối không nói với cấp trên)",
    de: 'Nach Hawaii gehst du selbst (Busan/Gyeongsang-Dialekt, aus dem Film 친구 (2001); heute die Standardantwort, um einen unerwünschten Vorschlag zurückzugeben — „geh doch selbst“. Scherzhaft und salopp — nur unter engen Freunden, nie zum Chef)' },
  { situation: 'sns', dialect: true, ko: '뭐랜 고람시니?',
    en: 'What are you saying? (Jeju dialect for 뭐라고 하는 거예요?; from the boat scene in the 2025 Netflix series 폭싹 속았수다. Jeju speech is close to a separate language — islanders use it among themselves, and trying it on Jeju usually gets a delighted reaction)',
    ja: '何て言ってるの?(済州方言で「뭐라고 하는 거예요?」。2025年Netflix『폭싹 속았수다』の船上の場面の台詞。済州の言葉はほぼ別言語で、島の人同士で使う。済州で言ってみると喜ばれる)',
    es: "¿Qué estás diciendo? (dialecto de Jeju para '뭐라고 하는 거예요?'; aparece en la escena del barco de la serie de Netflix 폭싹 속았수다 (2025). El habla de Jeju es casi otra lengua: los isleños la usan entre ellos y les hace mucha ilusión que un visitante lo intente)",
    vi: "Đang nói gì vậy? (phương ngữ Jeju của '뭐라고 하는 거예요?'; trong cảnh trên thuyền của phim Netflix 폭싹 속았수다 (2025). Tiếng Jeju gần như một ngôn ngữ riêng, người trên đảo dùng với nhau — thử nói khi đến Jeju sẽ được đón nhận rất vui)",
    de: 'Was sagst du gerade? (Jeju-Dialekt für „뭐라고 하는 거예요?“; aus der Bootsszene der Netflix-Serie 폭싹 속았수다 (2025). Das Jeju-Idiom ist fast eine eigene Sprache — Einheimische nutzen es untereinander und freuen sich, wenn Besucher es versuchen)' },
  { situation: 'cafe', ko: '여긴 재방문 의사 있음',
    en: "Coming back here for sure (음슴체 = the '-음/-ㅁ' style: sentences chopped down to a bare noun ending, no verb politeness at all. It sounds flat and unbothered, so Koreans use it for reviews, captions and notes to themselves — '재방문 의사 있음' is the stock way to end a good cafe review. Never use it when speaking to someone senior)",
    ja: 'ここはまた来る(음슴체=語尾を「-음/-ㅁ」で言い切る文体。敬語を全部そぎ落とした素っ気ない響きで、レビューやキャプション、自分用メモに使う。「재방문 의사 있음(再訪の意思あり)」はカフェ・グルメ評の定番の締め。目上の人に話す時には使わない)',
    es: "Aquí vuelvo seguro (음슴체 = el estilo '-음/-ㅁ': frases recortadas hasta terminar en un sustantivo, sin ninguna marca de cortesía. Suena plano y despreocupado, por eso se usa en reseñas, pies de foto y notas para uno mismo; '재방문 의사 있음' es el cierre típico de una buena reseña de cafetería. Nunca al hablar con un superior)",
    vi: "Chỗ này nhất định quay lại (음슴체 = lối viết kết câu bằng '-음/-ㅁ', cắt sạch đuôi lịch sự chỉ còn danh từ. Nghe cụt lủn, tỉnh bơ nên hay dùng cho review, caption và ghi chú cho chính mình; '재방문 의사 있음' là câu chốt quen thuộc của một review quán cà phê khen. Đừng dùng khi nói với người lớn tuổi hơn)",
    de: 'Hier komme ich definitiv wieder her (음슴체 = der „-음/-ㅁ“-Stil: Sätze auf eine bloße Nominalendung gekürzt, ganz ohne Höflichkeitsform. Das klingt nüchtern und beiläufig, deshalb nutzt man ihn für Bewertungen, Bildunterschriften und Notizen an sich selbst; „재방문 의사 있음“ ist der Standardschluss einer guten Café-Rezension. Nie gegenüber Höhergestellten)' },
  { situation: 'sns', ko: '이 장면에서 진짜 가슴에 국밥 쏟았다',
    en: "That scene absolutely wrecked me (가슴에 국밥 쏟다, lit. 'spill gukbap on your chest' — your chest goes hot, i.e. you were deeply moved. Spread on X around 2022-23. Joking banmal, for comments and chats with friends)",
    ja: 'あの場面で本当に胸が熱くなった(가슴에 국밥 쏟다=直訳「胸にクッパをこぼす」。熱いスープをこぼしたように胸が熱くなる、つまり激しく感動したということ。2022〜23年頃Xで拡散。ふざけたタメ口で、コメントや友達とのやりとりに)',
    es: "Esa escena me dejó hecho polvo (가슴에 국밥 쏟다, lit. 'derramarse gukbap en el pecho': el pecho se te pone ardiendo, o sea que te emocionó muchísimo. Se difundió en X hacia 2022-23. Informal y en broma, para comentarios y charlas con amigos)",
    vi: "Cảnh đó làm mình xúc động dữ dội (가슴에 국밥 쏟다, nghĩa đen 'đổ gukbap lên ngực': ngực nóng ran, tức là cảm động nghẹn ngào. Lan trên X khoảng 2022-23. Đùa, thân mật — dùng cho bình luận và trò chuyện với bạn bè)",
    de: 'Diese Szene hat mich völlig umgehauen (가슴에 국밥 쏟다, wörtlich „sich Gukbap über die Brust schütten“ — die Brust wird heiß, man ist also zutiefst gerührt. Verbreitete sich um 2022-23 auf X. Scherzhaft und salopp, für Kommentare und Chats mit Freunden)' },
  { situation: 'daily', ko: '이 노래 미쳤다 진짜',
    en: "This song is insane (미쳤다 as praise, not an insult — 'unbelievably good'. Banmal, for things: a song, food, the weather. Aimed at a person it goes back to meaning 'you're crazy', so keep it on things)",
    ja: 'この曲やばすぎる(미쳤다は「最高」の意味の褒め言葉で悪口ではない。タメ口で、曲・食べ物・天気など「モノ」に使う。人に向けると「頭おかしい」の意味に戻るので、モノ限定で)',
    es: "Esta canción está una locura (미쳤다 aquí es elogio, no insulto: 'increíblemente bueno'. Informal y para cosas — una canción, una comida, el tiempo. Dirigido a una persona vuelve a significar 'estás loco', así que úsalo solo con cosas)",
    vi: "Bài này đỉnh thật sự (미쳤다 ở đây là lời khen chứ không phải chửi: 'hay điên rồ'. Thân mật, dùng cho đồ vật — bài hát, món ăn, thời tiết. Nhắm vào người thì lại thành 'mày điên à', nên chỉ dùng cho vật)",
    de: 'Dieser Song ist der Wahnsinn (미쳤다 ist hier Lob, keine Beleidigung — „unglaublich gut“. Salopp und auf Dinge bezogen: ein Song, Essen, das Wetter. Auf eine Person gemünzt heißt es wieder „du spinnst“, also lieber bei Dingen bleiben)' },
];
