-- Follow-up to the 2026-09-10 morning review (operator instructions).
-- 1) 지리다 (446): removed from the dictionary and moved to the home "오늘의 실전 표현"
--    expressions (src/features/home/model/dailyPicks.ts) → delete the words row.
-- 2) Add 금수저·은수저·커엽다·띵곡 (457-460). Filling in the spoon-class pair (gold/silver)
--    and the 야민정음 pair (커엽다/띵곡) restores the related_words dropped from 흙수저·댕댕이
--    as dead refs in 20260910090000_add_thirteen_slang_words.sql.
--    These four were authored in-session at the operator's request, not collected by the scout.
--
-- NOTE: filename timestamp differs from the production migration version
-- (MCP apply time becomes the version) — repo-wide convention, see CLAUDE.md.
begin;

delete from public.words where id = '446';

insert into public.words (id, word, romanization, category, short_desc, short_desc_i18n, pronunciation, meanings, origin, origin_i18n, usage, usage_i18n, related_words, aliases, likes, saves, translations) values
('457', '금수저', 'Geum-Su-Jeo', 'new-slang', '부모 덕에 출발선이 앞서 있는 사람',
 '{"en":"Someone born ahead of the pack thanks to their parents","ja":"親のおかげで最初から有利な人","es":"Alguien que arranca con ventaja gracias a sus padres","vi":"Người sinh ra đã ở vạch đích nhờ cha mẹ","de":"Wer dank der Eltern schon vorne startet"}'::jsonb,
 '[금수저]',
 '[{"type":"명사","definition":"''금''과 ''수저''를 합친 말. 부모의 재산·인맥에 따라 출발선이 정해진다는 ''수저계급론''(금-은-동-흙)에서 맨 위를 가리킨다. 본인 능력과 상관없이 태어날 때부터 유리한 조건을 쥔 사람이라는 뜻이다.","definition_i18n":{"en":"''Gold'' + ''spoon''. The top rung of the ''spoon class theory'' (gold, silver, bronze, dirt): someone whose starting line was set by their parents'' wealth and connections, regardless of their own ability.","ja":"「金」と「スプーン」の合成語。親の財産や人脈で出発点が決まるという「スプーン階級論」(金・銀・銅・土)の最上位。本人の実力とは関係なく生まれつき有利な条件を持つ人。","es":"''Oro'' + ''cuchara''. El escalón más alto de la ''teoría de las clases de cuchara'' (oro, plata, bronce, tierra): alguien cuya línea de salida la fijaron la riqueza y los contactos de sus padres, al margen de su propio mérito.","vi":"''Vàng'' + ''thìa''. Bậc cao nhất trong ''thuyết giai cấp thìa'' (vàng, bạc, đồng, đất): người có vạch xuất phát do tài sản và quan hệ của cha mẹ quyết định, không liên quan đến năng lực bản thân.","de":"''Gold'' + ''Löffel''. Die oberste Stufe der ''Löffelklassen-Theorie'' (Gold, Silber, Bronze, Erde): jemand, dessen Startlinie durch Vermögen und Beziehungen der Eltern bestimmt ist, unabhängig vom eigenen Können."},"examples":[{"kor":"쟤는 금수저라 취업 걱정은 안 하더라.","eng":"He''s a gold spoon — job hunting isn''t something he worries about.","ja":"あの子は金スプーンだから就職の心配はしてないみたい。","es":"Él es cuchara de oro, así que no se preocupa por encontrar trabajo.","vi":"Cậu ấy là thìa vàng nên chẳng lo chuyện xin việc.","de":"Er ist ein Goldlöffel — um die Jobsuche macht er sich keine Sorgen."},{"kor":"금수저 흙수저 얘기는 이제 그만하자.","eng":"Let''s drop the gold-spoon-dirt-spoon talk already.","ja":"金スプーン土スプーンの話はもうやめよう。","es":"Dejemos ya el tema de cucharas de oro y de tierra.","vi":"Thôi đừng nói chuyện thìa vàng thìa đất nữa.","de":"Lass uns das Gold-und-Erdlöffel-Thema endlich lassen."}]}]'::jsonb,
 '영어 관용구 ''born with a silver spoon in one''''s mouth''(은수저를 물고 태어나다)가 바탕이다. 한국에서는 은보다 값진 금으로 바뀌어 ''금수저''가 됐고, 2015년 청년층 사이에서 수저계급론 담론이 퍼지며 흙수저와 짝을 이루는 말로 굳었다.',
 '{"en":"Rooted in the English idiom ''born with a silver spoon in one''s mouth''. In Korea the silver was upgraded to gold, and the 2015 ''spoon class'' discourse locked it in as the counterpart of 흙수저 (dirt spoon).","ja":"英語の慣用句「born with a silver spoon in one''s mouth」が土台。韓国では銀より価値の高い金に置き換わり、2015年のスプーン階級論の広まりで「土スプーン」と対になる語として定着した。","es":"Nace del modismo inglés ''born with a silver spoon in one''s mouth''. En Corea la plata pasó a ser oro, y el discurso de las clases de cuchara de 2015 lo fijó como opuesto de 흙수저 (cuchara de tierra).","vi":"Bắt nguồn từ thành ngữ tiếng Anh ''born with a silver spoon in one''s mouth''. Ở Hàn, bạc được nâng thành vàng, và làn sóng ''thuyết giai cấp thìa'' năm 2015 khiến nó thành cặp đối với 흙수저 (thìa đất).","de":"Geht auf die englische Redewendung ''born with a silver spoon in one''s mouth'' zurück. In Korea wurde Silber zu Gold, und der Löffelklassen-Diskurs von 2015 machte es zum Gegenstück von 흙수저 (Erdlöffel)."}'::jsonb,
 '주로 남을 두고 부러움 반 비꼼 반으로 쓴다. 자신을 가리켜 ''나 금수저야''라고 하면 자랑으로 들리니 조심할 것.',
 '{"en":"Usually said about other people, half envy and half dig. Calling yourself one sounds like bragging, so tread carefully.","ja":"たいてい他人について、うらやみ半分・皮肉半分で使う。自分を「金スプーン」と言うと自慢に聞こえるので注意。","es":"Se dice sobre todo de otros, mitad envidia mitad pulla. Aplicarlo a uno mismo suena a presumir, así que con cuidado.","vi":"Thường nói về người khác, nửa ghen tị nửa mỉa. Tự nhận mình là thìa vàng nghe như khoe, nên cẩn thận.","de":"Meist über andere gesagt, halb neidisch, halb spöttisch. Sich selbst so zu nennen klingt nach Angeberei — also Vorsicht."}'::jsonb,
 array['흙수저','은수저','헬조선'], '{}'::text[], 0, 0,
 '[{"lang":"🇺🇸 EN","text":"Gold spoon (born rich)"},{"lang":"🇯🇵 JA","text":"金スプーン(生まれつき裕福)"},{"lang":"🇨🇳 ZH","text":"金汤匙(含着金汤匙出生)"},{"lang":"🇻🇳 VI","text":"Thìa vàng (sinh ra đã giàu)"},{"lang":"🇪🇸 ES","text":"Cuchara de oro (nacer rico)"},{"lang":"🇩🇪 DE","text":"Goldlöffel (reich geboren)"}]'::jsonb),
('458', '은수저', 'Eun-Su-Jeo', 'new-slang', '수저계급론에서 금수저 바로 아래, 넉넉한 집안',
 '{"en":"One rung below gold on the spoon ladder — comfortably off","ja":"スプーン階級論で金の一つ下、余裕のある家","es":"Un escalón bajo el oro: familia acomodada","vi":"Dưới thìa vàng một bậc — gia đình khá giả","de":"Eine Stufe unter Gold — gut situiert"}'::jsonb,
 '[은수저]',
 '[{"type":"명사","definition":"수저계급론(금-은-동-흙)의 두 번째 등급. 금수저만큼 압도적이진 않아도 걱정 없이 자랄 만큼 넉넉한 집안을 가리킨다. 실제 대화에서는 금수저·흙수저만큼 자주 쓰이지 않고, 주로 계급을 나눠 설명할 때 등장한다.","definition_i18n":{"en":"The second rung of the spoon ladder (gold, silver, bronze, dirt): a family comfortable enough that money was never a worry, though not in gold-spoon territory. It comes up mostly when people spell out the whole ladder rather than in everyday talk.","ja":"スプーン階級論(金・銀・銅・土)の二番目。金スプーンほど圧倒的ではないが、不自由なく育つ程度に裕福な家を指す。日常会話では金・土ほど使われず、階級を並べて説明するときに出てくることが多い。","es":"El segundo escalón de la escala de cucharas (oro, plata, bronce, tierra): una familia lo bastante acomodada como para no pasar apuros, aunque sin llegar al oro. Aparece sobre todo al explicar la escala entera, no tanto en la conversación diaria.","vi":"Bậc thứ hai trong thang thìa (vàng, bạc, đồng, đất): gia đình đủ khá giả để không phải lo tiền, tuy chưa tới mức thìa vàng. Chủ yếu xuất hiện khi người ta liệt kê cả thang, ít dùng trong hội thoại thường ngày.","de":"Die zweite Stufe der Löffelleiter (Gold, Silber, Bronze, Erde): eine Familie, in der Geld nie ein Problem war, aber kein Goldlöffel. Taucht vor allem auf, wenn jemand die ganze Leiter aufzählt, seltener im Alltagsgespräch."},"examples":[{"kor":"금수저까진 아니고 은수저 정도래.","eng":"Not quite a gold spoon — more like silver, they say.","ja":"金スプーンってほどじゃなくて銀スプーンくらいらしい。","es":"Dicen que no llega a cuchara de oro, más bien de plata.","vi":"Nghe nói chưa tới thìa vàng, cỡ thìa bạc thôi.","de":"Kein Goldlöffel, eher Silberlöffel, heißt es."}]}]'::jsonb,
 '영어 관용구 ''born with a silver spoon in one''''s mouth''의 은수저가 그대로 옮겨온 말이다. 한국의 수저계급론이 금-은-동-흙 4단계로 정리되면서 금 다음 등급으로 자리 잡았다.',
 '{"en":"A direct carry-over of the silver spoon from the English idiom ''born with a silver spoon in one''s mouth''. When Korea''s spoon class theory settled into four rungs — gold, silver, bronze, dirt — silver took the slot below gold.","ja":"英語の慣用句「born with a silver spoon in one''s mouth」の銀スプーンがそのまま移った語。韓国のスプーン階級論が金・銀・銅・土の4段階に整理される中で、金の次の等級に落ち着いた。","es":"Es la cuchara de plata del modismo inglés ''born with a silver spoon in one''s mouth'', trasladada tal cual. Cuando la teoría coreana de las cucharas se fijó en cuatro escalones —oro, plata, bronce, tierra—, la plata quedó justo debajo del oro.","vi":"Chính là chiếc thìa bạc trong thành ngữ tiếng Anh ''born with a silver spoon in one''s mouth'' được chuyển nguyên sang. Khi thuyết giai cấp thìa của Hàn định hình thành bốn bậc — vàng, bạc, đồng, đất — bạc nằm ngay dưới vàng.","de":"Der Silberlöffel der englischen Redewendung ''born with a silver spoon in one''s mouth'', direkt übernommen. Als sich Koreas Löffelklassen-Theorie auf vier Stufen einpendelte — Gold, Silber, Bronze, Erde —, landete Silber direkt unter Gold."}'::jsonb,
 '금수저·흙수저를 설명하다 함께 나오는 말이라, 단독으로 쓰는 일은 드물다.',
 '{"en":"Rarely used on its own — it mostly shows up while explaining gold and dirt spoons.","ja":"単独で使うことは少なく、金スプーン・土スプーンを説明する流れで出てくる。","es":"Rara vez se usa solo; suele salir al explicar las cucharas de oro y de tierra.","vi":"Hiếm khi dùng riêng — thường xuất hiện khi giải thích thìa vàng và thìa đất.","de":"Wird selten allein verwendet — meist fällt es beim Erklären von Gold- und Erdlöffel."}'::jsonb,
 array['금수저','흙수저'], '{}'::text[], 0, 0,
 '[{"lang":"🇺🇸 EN","text":"Silver spoon (well-off, below gold)"},{"lang":"🇯🇵 JA","text":"銀スプーン(金の一つ下)"},{"lang":"🇨🇳 ZH","text":"银汤匙(仅次于金汤匙)"},{"lang":"🇻🇳 VI","text":"Thìa bạc (khá giả, dưới thìa vàng)"},{"lang":"🇪🇸 ES","text":"Cuchara de plata (acomodado)"},{"lang":"🇩🇪 DE","text":"Silberlöffel (wohlhabend)"}]'::jsonb),
('459', '커엽다', 'Keo-Yeop-Da', 'new-slang', '''귀엽다''를 글자 모양대로 비튼 야민정음 표기',
 '{"en":"''Cute'' rewritten with look-alike letters (야민정음 style)","ja":"「かわいい」を字の形で崩した야민정음表記","es":"''Mono'' escrito con letras parecidas (estilo 야민정음)","vi":"''Dễ thương'' viết bằng chữ nhìn giống (kiểu 야민정음)","de":"„Süß“ mit ähnlich aussehenden Buchstaben geschrieben (야민정음)"}'::jsonb,
 '[커엽따]',
 '[{"type":"형용사","definition":"''귀엽다''의 ''귀''를 모양이 닮은 ''커''로 바꿔 쓴 야민정음 표기. 뜻은 귀엽다와 똑같고, 일부러 틀리게 쓴 데서 오는 장난스러운 어감이 얹힌다. 소리 내 읽으면 원말과 달라지므로 어디까지나 글로 쓰는 말이다.","definition_i18n":{"en":"''Cute'' (귀엽다) with 귀 swapped for the look-alike 커 — a 야민정음 respelling. The meaning is identical to 귀엽다; the deliberate misspelling just adds a playful wink. Read aloud it no longer matches the original, so it lives in writing.","ja":"「귀엽다(かわいい)」の「귀」を形の似た「커」に置き換えた야민정음表記。意味は귀엽다と同じで、わざと崩したことによるおどけた響きが加わる。声に出すと元の語と別物になるため、あくまで文字で使う言葉。","es":"''Mono'' (귀엽다) con 귀 cambiado por el parecido 커: una reescritura al estilo 야민정음. El significado es el mismo; la falta deliberada solo añade un guiño juguetón. Leído en voz alta ya no coincide con el original, así que es cosa de texto.","vi":"''Dễ thương'' (귀엽다) đổi 귀 thành 커 nhìn na ná — cách viết kiểu 야민정음. Nghĩa y hệt 귀엽다, chỉ thêm chút tinh nghịch vì cố tình viết sai. Đọc lên thì không còn giống từ gốc, nên đây là từ để viết.","de":"„Süß“ (귀엽다), bei dem 귀 durch das ähnlich aussehende 커 ersetzt wird — eine 야민정음-Schreibung. Die Bedeutung bleibt gleich, der bewusste Fehler fügt nur einen verspielten Ton hinzu. Vorgelesen passt es nicht mehr zum Original, es ist also Schriftsprache."},"examples":[{"kor":"이 짤 진짜 커엽다ㅋㅋ","eng":"This pic is seriously cute lol","ja":"この画像マジでかわいいww","es":"Esta foto es monísima jajaja","vi":"Cái ảnh này dễ thương thật hahaha","de":"Das Bild ist echt süß haha"}]}]'::jsonb,
 '디시인사이드 야구 갤러리에서 시작된 표기 놀이 ''야민정음''(야갤+훈민정음)의 대표 사례다. 글자 모양이 비슷한 한글끼리 바꿔 쓰는 방식으로, 같은 계열에 멍멍이→댕댕이, 명곡→띵곡이 있다.',
 '{"en":"A flagship case of 야민정음 (야갤 + 훈민정음), the respelling game born on DC Inside''s baseball board: swap Hangul letters that look alike. Same family as 멍멍이 → 댕댕이 and 명곡 → 띵곡.","ja":"ディシインサイド野球ギャラリー発の表記遊び「야민정음」(야갤+訓民正音)の代表例。形の似たハングル同士を入れ替える方式で、同系に멍멍이→댕댕이、명곡→띵곡がある。","es":"Un caso emblemático del 야민정음 (야갤 + 훈민정음), el juego de reescritura nacido en el foro de béisbol de DC Inside: cambiar letras del hangul que se parecen. De la misma familia que 멍멍이 → 댕댕이 y 명곡 → 띵곡.","vi":"Ví dụ tiêu biểu của 야민정음 (야갤 + 훈민정음), trò viết lệch khởi nguồn từ diễn đàn bóng chày DC Inside: đổi các chữ Hangul trông giống nhau. Cùng họ với 멍멍이 → 댕댕이 và 명곡 → 띵곡.","de":"Ein Paradebeispiel für 야민정음 (야갤 + 훈민정음), das Umschreibspiel vom Baseball-Board auf DC Inside: ähnlich aussehende Hangul-Zeichen werden getauscht. Gleiche Familie wie 멍멍이 → 댕댕이 und 명곡 → 띵곡."}'::jsonb,
 '온라인 게시글·댓글·메시지에서만 쓴다. 문서나 격식 있는 자리에서는 그냥 ''귀엽다''로 쓸 것.',
 '{"en":"Posts, comments and DMs only. In documents or any formal setting, just write 귀엽다.","ja":"ネットの投稿・コメント・メッセージ専用。文書や改まった場では素直に「귀엽다」を使うこと。","es":"Solo para publicaciones, comentarios y mensajes. En documentos o contextos formales, escribe 귀엽다 sin más.","vi":"Chỉ dùng khi đăng bài, bình luận, nhắn tin. Trong văn bản hay tình huống trang trọng thì viết 귀엽다.","de":"Nur für Posts, Kommentare und Nachrichten. In Dokumenten oder förmlichen Kontexten einfach 귀엽다 schreiben."}'::jsonb,
 array['댕댕이','띵곡'], array['커여워','커염'], 0, 0,
 '[{"lang":"🇺🇸 EN","text":"''Cute'' in look-alike letters"},{"lang":"🇯🇵 JA","text":"「かわいい」の字形崩し表記"},{"lang":"🇨🇳 ZH","text":"用形近字改写的「可爱」"},{"lang":"🇻🇳 VI","text":"''Dễ thương'' viết chữ nhìn giống"},{"lang":"🇪🇸 ES","text":"''Mono'' con letras parecidas"},{"lang":"🇩🇪 DE","text":"„Süß“ in Ähnlich-Schreibweise"}]'::jsonb),
('460', '띵곡', 'Tting-Gok', 'new-slang', '''명곡''을 글자 모양대로 비튼 말 — 진짜 좋은 노래',
 '{"en":"''Masterpiece song'' respelled — a genuinely great track","ja":"「名曲」を字の形で崩した語 — 本当にいい曲","es":"''Canción maestra'' reescrita — un temazo de verdad","vi":"''Danh khúc'' viết lệch — bài hát hay thật sự","de":"„Meisterstück-Song“ umgeschrieben — ein echt starker Track"}'::jsonb,
 '[띵곡]',
 '[{"type":"명사","definition":"''명곡(名曲)''의 ''명''을 모양이 닮은 ''띵''으로 바꿔 쓴 야민정음 표기. 정말 좋은 노래를 가리키며, 원말보다 가볍고 열광적인 느낌이라 댓글·플레이리스트 제목에서 자주 보인다.","definition_i18n":{"en":"''명곡'' (a masterpiece song) with 명 swapped for the look-alike 띵 — a 야민정음 respelling. It means a genuinely great track, but lands lighter and more excitable than the original, so it fills comment sections and playlist titles.","ja":"「명곡(名曲)」の「명」を形の似た「띵」に替えた야민정음表記。本当にいい曲を指すが、元の語より軽くテンションの高い響きで、コメント欄やプレイリスト名でよく見かける。","es":"''명곡'' (canción maestra) con 명 cambiado por el parecido 띵: reescritura al estilo 야민정음. Significa un tema realmente bueno, pero suena más ligero y entusiasta que el original, así que abunda en comentarios y títulos de playlist.","vi":"''명곡'' (danh khúc) đổi 명 thành 띵 nhìn na ná — cách viết kiểu 야민정음. Nghĩa là bài hát hay thật sự, nhưng nghe nhẹ và phấn khích hơn từ gốc, nên hay gặp ở bình luận và tên playlist.","de":"''명곡'' (Meisterwerk-Song) mit 명 ersetzt durch das ähnlich aussehende 띵 — eine 야민정음-Schreibung. Gemeint ist ein wirklich großartiger Track, klingt aber lockerer und begeisterter als das Original — daher überall in Kommentaren und Playlist-Titeln."},"examples":[{"kor":"이 노래 띵곡이다 진짜.","eng":"This song is a straight-up banger.","ja":"この曲まじで名曲。","es":"Esta canción es un temazo de verdad.","vi":"Bài này đúng là bản hay thật sự.","de":"Der Song ist wirklich ein Brett."}]}]'::jsonb,
 '디시인사이드 야구 갤러리발 표기 놀이 ''야민정음''(야갤+훈민정음)에서 나왔다. 세로로 붙은 ''ㅁ''이 ''ㄸ''처럼 보이는 데서 명→띵 치환이 생겼고, 같은 방식의 ''띵작''(명작)과 짝처럼 쓰인다.',
 '{"en":"Comes from 야민정음 (야갤 + 훈민정음), the respelling game from DC Inside''s baseball board: ㅁ read as ㄸ turns 명 into 띵. It pairs with 띵작 (명작, ''masterpiece'') built the same way.","ja":"ディシインサイド野球ギャラリー発の表記遊び「야민정음」(야갤+訓民正音)から。「ㅁ」が「ㄸ」に見えることから명→띵の置換が生まれ、同じ作りの「띵작(名作)」と対で使われる。","es":"Viene del 야민정음 (야갤 + 훈민정음), el juego de reescritura del foro de béisbol de DC Inside: la ㅁ leída como ㄸ convierte 명 en 띵. Va de la mano con 띵작 (명작, ''obra maestra''), formado igual.","vi":"Xuất phát từ 야민정음 (야갤 + 훈민정음), trò viết lệch của diễn đàn bóng chày DC Inside: chữ ㅁ trông như ㄸ nên 명 thành 띵. Đi cặp với 띵작 (명작, ''kiệt tác'') tạo theo cùng cách.","de":"Stammt aus 야민정음 (야갤 + 훈민정음), dem Umschreibspiel vom Baseball-Board auf DC Inside: ㅁ wirkt wie ㄸ, also wird 명 zu 띵. Es bildet ein Paar mit dem gleich gebauten 띵작 (명작, „Meisterwerk“)."}'::jsonb,
 '온라인에서 노래를 추천하거나 감탄할 때 쓴다. 글로 쓰는 표기라 격식 있는 글에는 ''명곡''을 쓴다.',
 '{"en":"Used online when recommending or gushing over a song. It''s a written respelling, so use 명곡 in anything formal.","ja":"ネットで曲を勧めたり感嘆したりするときに使う。文字表記の遊びなので、改まった文章では「명곡」を使う。","es":"Se usa en internet al recomendar una canción o alucinar con ella. Es una grafía de broma, así que en textos formales escribe 명곡.","vi":"Dùng trên mạng khi giới thiệu hoặc trầm trồ về một bài hát. Đây là cách viết chơi chữ, nên văn bản trang trọng thì dùng 명곡.","de":"Wird online benutzt, wenn man einen Song empfiehlt oder abfeiert. Es ist eine Schreibspielerei — in förmlichen Texten 명곡 verwenden."}'::jsonb,
 array['댕댕이','커엽다','최애'], '{}'::text[], 0, 0,
 '[{"lang":"🇺🇸 EN","text":"Banger (''masterpiece song'' respelled)"},{"lang":"🇯🇵 JA","text":"名曲(字形崩し表記)"},{"lang":"🇨🇳 ZH","text":"神曲(形近字改写的「名曲」)"},{"lang":"🇻🇳 VI","text":"Bài hát đỉnh (viết lệch từ 명곡)"},{"lang":"🇪🇸 ES","text":"Temazo (''명곡'' reescrito)"},{"lang":"🇩🇪 DE","text":"Kracher (umgeschriebenes 명곡)"}]'::jsonb);

-- Restore references that the new rows make valid again.
update public.words set related_words = array['금수저','헬조선','이생망'] where id = '449';
update public.words set related_words = array['커엽다','띵곡','잼민이'] where id = '454';

commit;

-- After apply: select count(*) from public.words; → 377
