-- 잠수 / 애자일 / 고문관 / 급식체 추가 (495-498, 2026-09-14 아침 검수 중 운영자 직접 추가 지시).
-- 잠수: [표준사전: 뜻다름] 사전에는 물에 잠김(潛水)·해녀(潛嫂)뿐. 출처 나무위키 '잠수(은어)'·백뉴스 요즘 것들 용어사전·wordrow.
--   PC통신 채팅방 유래는 통설로만 적고 첫 사용 시점은 적지 않았다. '잠수 타다'가 실사용 형태라 aliases로 흡수.
-- 애자일: [표준사전: 없음] 출처 HBR코리아·투이컨설팅(2018 전후 도입 붐)·터치클래스·서울에일리언(형식만 도입 비판).
--   운영자가 적은 '아자일'도 검색되게 alias에 넣었다.
-- 고문관: [표준사전: 뜻다름] 사전에는 자문 관리(顧問官) 뜻뿐. 출처 아시아경제 전쟁사 칼럼(2018)·나무위키.
--   미군 군사고문단 유래는 널리 알려진 설명이라 그대로 적되 단원 이름·부대명은 넣지 않았다.
-- 급식체: [표준사전: 없음] 출처 한글문화연대(2017)·오마이뉴스·나무위키. 특정 방송인이 원조라는 설은 출처 한 곳뿐이라
--   '인터넷 방송인의 말투'로만 적었다. 이름 뿌리인 급식충은 비하어라 usage에 쓰지 말라고 명시.
--
-- NOTE: filename timestamp differs from the production migration version
-- (MCP apply time becomes the version) — repo-wide convention, see CLAUDE.md.

insert into public.words (id, word, romanization, category, secondary_category, short_desc, short_desc_i18n, pronunciation, meanings, origin, origin_i18n, usage, usage_i18n, related_words, aliases, likes, saves, translations) values
('495', '잠수', 'Jam-su', 'daily', 'love', '말없이 연락을 끊고 사라지는 것', '{"en": "Going quiet — vanishing without a word", "ja": "何も言わず連絡を絶つこと", "es": "Desaparecer del mapa sin decir nada", "vi": "Lặn mất tăm, cắt liên lạc không một lời", "de": "Abtauchen — ohne ein Wort verschwinden"}'::jsonb, '[잠수]',
 '[{"type": "명사", "definition": "물속으로 들어간다는 잠수(潛水)에 빗대, 아무 예고 없이 모든 연락을 끊고 자취를 감추는 것. 주로 잠수 타다·잠수를 타다 꼴로 쓴다. 연인·친구 사이는 물론, 단톡방이나 온라인 게임에서 한동안 대답이 없는 것까지 가리킨다.", "definition_i18n": {"en": "A figurative use of 잠수 (diving underwater): cutting off all contact without warning and dropping out of sight. Usually in the form 잠수 타다. Covers partners and friends going silent, and also someone not answering in a group chat or online game for a while.", "ja": "水に潜る잠수(潜水)にたとえ、予告なく連絡をすべて絶って姿を消すこと。主に잠수 타다の形で使う。恋人・友人間はもちろん、グループチャットやオンラインゲームでしばらく返事がないことも指す。", "es": "Uso figurado de 잠수 (bucear): cortar todo contacto sin aviso y desaparecer. Suele decirse 잠수 타다. Vale para parejas y amigos que dejan de responder, y también para quien no contesta un rato en un chat grupal o un juego online.", "vi": "Nghĩa bóng của 잠수 (lặn): cắt mọi liên lạc không báo trước rồi biến mất. Thường dùng dạng 잠수 타다. Dùng cho người yêu, bạn bè im bặt, và cả người không trả lời một lúc trong nhóm chat hay game online.", "de": "Übertragen von 잠수 (Tauchen): ohne Vorwarnung jeden Kontakt abbrechen und von der Bildfläche verschwinden. Meist als 잠수 타다. Gilt für Partner*innen und Freund*innen, die verstummen, aber auch für jemanden, der im Gruppenchat oder Onlinespiel eine Weile nicht reagiert."}, "examples": [{"kor": "시험 끝나고 일주일째 잠수 탔어. 연락이 하나도 안 돼.", "eng": "They have been off the grid for a week since exams ended — no reply at all.", "ja": "試験が終わってから1週間音信不通。全然連絡がつかない。", "es": "Desde que acabaron los exámenes lleva una semana sin dar señales de vida.", "vi": "Thi xong là lặn mất tăm cả tuần rồi, liên lạc không được.", "de": "Seit den Prüfungen herrscht eine Woche Funkstille — keine Antwort."}]}]'::jsonb,
 '1990년대 PC통신 채팅방에서 불러도 대답 없이 눈팅만 하거나 자리를 비운 사람을 물속에 잠긴 것에 빗대 부르던 말에서 퍼졌다는 설명이 일반적이다. 정확한 첫 사용 시점은 확인되지 않았다. 표준국어대사전의 잠수는 물에 들어간다는 뜻뿐이다.',
 '{"en": "Commonly traced to 1990s PC-network chat rooms, where someone who lurked or stopped answering was said to have gone underwater. The exact first use is undocumented. The Standard Korean Dictionary lists only the literal diving sense.", "ja": "1990年代のパソコン通信のチャットで、呼んでも返事せず見ているだけの人や席を外した人を水に潜ったとたとえた言い方から広まったとされる。初出は未確認。標準国語大辞典の잠수は潜水の意味のみ。", "es": "Suele atribuirse a los chats de las redes PC de los años 90, donde de quien solo miraba o dejaba de responder se decía que se había sumergido. No hay primer uso documentado. El diccionario estándar solo recoge el sentido literal de bucear.", "vi": "Thường được cho là bắt nguồn từ phòng chat mạng PC thập niên 1990, nơi người chỉ đọc lén hoặc không trả lời bị ví như đã lặn xuống nước. Chưa rõ lần dùng đầu tiên. Từ điển chuẩn chỉ ghi nghĩa đen là lặn.", "de": "Wird meist auf Chatrooms der PC-Netze der 1990er zurückgeführt: Wer nur mitlas oder nicht mehr antwortete, war abgetaucht. Die Erstverwendung ist nicht belegt. Das Standardwörterbuch kennt nur die wörtliche Bedeutung Tauchen."}'::jsonb,
 '잠수 타다·잠수 탔어 꼴로 쓴다. 말없이 사라진 쪽을 탓하는 뉘앙스지만, 시험 기간이라 잠깐 잠수 탈게처럼 스스로 미리 알리는 가벼운 용법도 흔하다. 영어 차용어 고스팅과 뜻이 거의 같다. 잠수·잠수 타다 어느 쪽으로 검색해도 이 항목 하나가 나온다.',
 '{"en": "Used as 잠수 타다 / 잠수 탔어. It usually blames the one who vanished, but a light self-announced use is common too, as in 시험 기간이라 잠깐 잠수 탈게 (going quiet for exam season). Nearly the same as the loanword 고스팅. Searching 잠수 or 잠수 타다 brings up this one entry.", "ja": "잠수 타다・잠수 탔어の形で使う。黙って消えた側を責めるニュアンスだが、시험 기간이라 잠깐 잠수 탈게(試験期間だからしばらく潜るね)のように自分から予告する軽い使い方も多い。外来語고스팅とほぼ同義。잠수でも잠수 타다でも検索するとこの項目が出る。", "es": "Se usa como 잠수 타다 / 잠수 탔어. Suele culpar a quien desaparece, pero también es común avisarlo uno mismo, como en 시험 기간이라 잠깐 잠수 탈게 (me desconecto por exámenes). Casi igual al préstamo 고스팅. Buscando 잠수 o 잠수 타다 sale esta misma entrada.", "vi": "Dùng dạng 잠수 타다 / 잠수 탔어. Thường trách người biến mất, nhưng cũng hay tự báo trước kiểu 시험 기간이라 잠깐 잠수 탈게 (mùa thi nên lặn một thời gian). Gần như cùng nghĩa với từ mượn 고스팅. Tìm 잠수 hay 잠수 타다 đều ra mục này.", "de": "Gebraucht als 잠수 타다 / 잠수 탔어. Meist ein Vorwurf an die verschwundene Person, aber auch als lockere Selbstankündigung üblich: 시험 기간이라 잠깐 잠수 탈게 (ich tauche für die Prüfungszeit ab). Fast gleichbedeutend mit dem Lehnwort 고스팅. Die Suche nach 잠수 oder 잠수 타다 führt zu diesem einen Eintrag."}'::jsonb,
 '{고스팅,잠수이별,읽씹,안읽씹}'::text[], '{잠수 타다,잠수타다,잠수를 타다}'::text[], 0, 0,
 '[{"lang": "🇺🇸 EN", "text": "Going off the grid / ghosting"}, {"lang": "🇯🇵 JA", "text": "音信不通になる"}, {"lang": "🇨🇳 ZH", "text": "玩失踪 / 潜水"}, {"lang": "🇻🇳 VI", "text": "Lặn mất tăm"}, {"lang": "🇪🇸 ES", "text": "Desaparecer del mapa"}, {"lang": "🇩🇪 DE", "text": "Abtauchen"}]'::jsonb),
('496', '애자일', 'Ae-ja-il', 'work', null, '빠르게 만들고 고치며 일하는 방식', '{"en": "Agile — build fast, ship, then adjust", "ja": "素早く作って直しながら進める働き方", "es": "Ágil: construir rápido, lanzar y ajustar", "vi": "Agile — làm nhanh, ra sản phẩm rồi chỉnh", "de": "Agil — schnell bauen, liefern, nachbessern"}'::jsonb, '[애자일]',
 '[{"type": "명사", "definition": "영어 agile(민첩한)에서 온 말. 원래는 계획을 길게 세우지 않고 작은 팀이 짧은 주기로 만들어 보고 피드백을 받아 고쳐 나가는 소프트웨어 개발 방법론이다. 한국 회사에서는 조직 운영 방식 전반을 가리키는 유행어가 되어, 애자일하게처럼 붙여 빠르고 유연하게라는 뜻으로도 쓴다.", "definition_i18n": {"en": "From English agile. Originally a software method where small teams skip long upfront plans, build in short cycles, take feedback and adjust. In Korean companies it became a buzzword for how the whole organisation runs, and 애자일하게 is used like an adverb meaning quickly and flexibly.", "ja": "英語agile(機敏な)から。本来は長い計画を立てず、小さなチームが短いサイクルで作ってフィードバックを受け改善していくソフトウェア開発手法。韓国の会社では組織運営全般を指す流行語になり、애자일하게と付けて素早く柔軟にという意味でも使う。", "es": "Del inglés agile. En origen, un método de desarrollo de software: equipos pequeños, sin grandes planes previos, que construyen en ciclos cortos y ajustan según el feedback. En las empresas coreanas se volvió palabra de moda para la gestión en general, y 애자일하게 se usa como adverbio: rápido y con flexibilidad.", "vi": "Từ agile (nhanh nhẹn) tiếng Anh. Vốn là phương pháp phát triển phần mềm: nhóm nhỏ không lập kế hoạch dài, làm theo chu kỳ ngắn, nhận phản hồi rồi sửa. Ở công ty Hàn, nó thành từ thời thượng chỉ cả cách vận hành tổ chức, và 애자일하게 được dùng như trạng từ nghĩa là nhanh và linh hoạt.", "de": "Von englisch agile. Ursprünglich eine Softwaremethode: kleine Teams verzichten auf lange Vorabplanung, bauen in kurzen Zyklen, holen Feedback ein und passen an. In koreanischen Firmen wurde es zum Modewort für die ganze Organisationsführung; 애자일하게 dient als Adverb für schnell und flexibel."}, "examples": [{"kor": "이번 건은 보고서 말고 애자일하게 일단 만들어 보죠.", "eng": "This time, no report — let us go agile and just build something first.", "ja": "今回は報告書じゃなくて、アジャイルにまず作ってみましょう。", "es": "Esta vez nada de informe: hagámoslo ágil y construyamos algo primero.", "vi": "Lần này khỏi báo cáo, làm kiểu agile, cứ làm thử trước đã.", "de": "Diesmal kein Bericht — lass uns agil vorgehen und erst mal etwas bauen."}]}]'::jsonb,
 '2001년 미국 개발자들이 발표한 애자일 선언에서 시작된 소프트웨어 개발 방법론이다. 한국에서는 2018년 전후 디지털 전환 바람과 함께 대기업과 은행이 앞다퉈 애자일 조직을 도입하면서 사무실 용어로 퍼졌다.',
 '{"en": "A software development approach that began with the Agile Manifesto published by US developers in 2001. In Korea it spread into office vocabulary around 2018, when large companies and banks rushed to set up agile organisations amid the digital-transformation boom.", "ja": "2001年に米国の開発者たちが発表したアジャイル宣言に始まるソフトウェア開発手法。韓国では2018年前後、デジタル転換ブームとともに大企業や銀行が競ってアジャイル組織を導入し、オフィス用語として広まった。", "es": "Enfoque de desarrollo de software que nace con el Manifiesto Ágil publicado por desarrolladores estadounidenses en 2001. En Corea pasó al vocabulario de oficina hacia 2018, cuando grandes empresas y bancos se lanzaron a crear organizaciones ágiles en plena ola de transformación digital.", "vi": "Phương pháp phát triển phần mềm bắt đầu từ Tuyên ngôn Agile do các lập trình viên Mỹ công bố năm 2001. Ở Hàn, nó thành từ công sở quanh năm 2018, khi các tập đoàn lớn và ngân hàng đua nhau lập tổ chức agile giữa làn sóng chuyển đổi số.", "de": "Ein Ansatz der Softwareentwicklung, der mit dem 2001 von US-Entwickler*innen veröffentlichten Agilen Manifest begann. In Korea wurde er um 2018 zum Bürowort, als Großkonzerne und Banken im Zuge der digitalen Transformation eilig agile Organisationen einführten."}'::jsonb,
 '보고와 결재가 많은 회사에서 형식을 줄이자는 뜻으로 애자일하게 가자고 한다. 다만 위계는 그대로 둔 채 이름만 애자일을 붙여 실무자 부담만 늘었다는 비판도 자주 나온다. 애자일·애자일하게 어느 쪽으로 검색해도 이 항목 하나가 나온다.',
 '{"en": "In report-heavy companies, 애자일하게 가자 means let us cut the formalities. A frequent criticism is that firms keep the hierarchy intact and only borrow the label, which just adds to the workload of the people doing the work. Searching 애자일 or 애자일하게 brings up this one entry.", "ja": "報告や決裁が多い会社で、形式を減らそうという意味で애자일하게 가자と言う。ただ上下関係はそのままに名前だけアジャイルにして、現場の負担だけ増えたという批判もよく出る。애자일でも애자일하게でも検索するとこの項目が出る。", "es": "En empresas llenas de informes y firmas, 애자일하게 가자 significa recortemos formalidades. Es frecuente la crítica de que se mantiene la jerarquía y solo se toma la etiqueta, lo que sobrecarga a quien hace el trabajo. Buscando 애자일 o 애자일하게 sale esta misma entrada.", "vi": "Ở công ty nhiều báo cáo, phê duyệt, câu 애자일하게 가자 nghĩa là bớt thủ tục đi. Nhưng cũng hay bị chê là giữ nguyên thứ bậc, chỉ gắn mác agile khiến người làm thêm gánh nặng. Tìm 애자일 hay 애자일하게 đều ra mục này.", "de": "In berichtslastigen Firmen heißt 애자일하게 가자 so viel wie weniger Formalitäten. Häufige Kritik: Die Hierarchie bleibt, nur das Etikett wird übernommen, und die Last landet bei den Mitarbeitenden. Die Suche nach 애자일 oder 애자일하게 führt zu diesem einen Eintrag."}'::jsonb,
 '{컨펌,디벨롭,일잘러,야근각}'::text[], '{애자일하게,agile,아자일}'::text[], 0, 0,
 '[{"lang": "🇺🇸 EN", "text": "Agile"}, {"lang": "🇯🇵 JA", "text": "アジャイル"}, {"lang": "🇨🇳 ZH", "text": "敏捷"}, {"lang": "🇻🇳 VI", "text": "Agile (linh hoạt)"}, {"lang": "🇪🇸 ES", "text": "Ágil"}, {"lang": "🇩🇪 DE", "text": "Agil"}]'::jsonb),
('497', '고문관', 'Go-mun-gwan', 'daily', 'work', '눈치 없고 어리숙해 일을 그르치는 사람', '{"en": "The clueless one who keeps messing things up", "ja": "要領が悪く足を引っ張る人", "es": "El despistado que siempre la lía", "vi": "Người ngơ ngác hay làm hỏng việc", "de": "Der Ahnungslose, der alles vermasselt"}'::jsonb, '[고문관]',
 '[{"type": "명사", "definition": "원래 군대 은어로, 눈치가 없고 어리숙해 시키는 일을 제대로 못 하고 부대에 민폐를 끼치는 병사. 군대를 다녀온 사람들을 통해 일상에서도 쓰이면서 회사나 모임에서 적응하지 못하고 일을 그르치는 사람을 가리키는 말로 넓어졌다. 표준국어대사전의 고문관(顧問官)은 자문에 응하는 관리라는 뜻뿐이다.", "definition_i18n": {"en": "Originally army slang for a soldier who is clueless and clumsy, cannot do what they are told, and drags the unit down. Through people who served it spread into everyday speech for anyone at work or in a group who cannot adapt and keeps botching things. The Standard Korean Dictionary lists 고문관(顧問官) only as an official advisor.", "ja": "もとは軍隊の隠語で、気が利かず要領が悪く、命じられたことをまともにできず部隊に迷惑をかける兵士。兵役経験者を通じて日常でも使われ、会社や集まりでなじめず仕事をしくじる人を指す語に広がった。標準国語大辞典の고문관(顧問官)は諮問に応じる官吏の意味のみ。", "es": "En origen, jerga militar para el soldado despistado y torpe que no cumple lo que se le manda y perjudica a la unidad. A través de quienes hicieron la mili pasó al habla cotidiana para cualquiera que en el trabajo o un grupo no se adapta y lo estropea todo. El diccionario estándar solo recoge 고문관(顧問官) como funcionario asesor.", "vi": "Vốn là tiếng lóng quân đội chỉ người lính ngơ ngác, vụng về, không làm nổi việc được giao và gây phiền cho đơn vị. Qua những người từng đi lính, từ này lan ra đời thường để chỉ ai ở công ty hay nhóm không thích nghi được và cứ làm hỏng việc. Từ điển chuẩn chỉ ghi 고문관(顧問官) là quan cố vấn.", "de": "Ursprünglich Armee-Slang für einen ahnungslosen, ungeschickten Soldaten, der Befehle nicht hinbekommt und die Einheit belastet. Über Gediente gelangte es in den Alltag für alle, die sich im Job oder in einer Gruppe nicht einfinden und ständig etwas vermasseln. Das Standardwörterbuch kennt 고문관(顧問官) nur als Berater-Beamten."}, "examples": [{"kor": "우리 소대 고문관이 또 사고 쳤대.", "eng": "Our platoon screw-up has messed up again.", "ja": "うちの小隊のお荷物がまたやらかしたって。", "es": "El patoso del pelotón la ha vuelto a liar.", "vi": "Cậu ngơ ngác của trung đội lại gây chuyện nữa rồi.", "de": "Unser Zug-Tollpatsch hat schon wieder Mist gebaut."}, {"kor": "새로 온 인턴이 고문관인 줄 알았는데 알고 보니 일잘러더라.", "eng": "I thought the new intern was hopeless, but it turns out they are a real ace.", "ja": "新しいインターン、ポンコツかと思ったら仕事できる人だった。", "es": "Pensaba que el nuevo becario era un desastre, pero resulta que es un crack.", "vi": "Tưởng thực tập sinh mới là đứa vụng về, hóa ra lại làm việc giỏi.", "de": "Ich hielt den neuen Praktikanten für hoffnungslos, dabei ist er ein echter Arbeitsprofi."}]}]'::jsonb,
 '미군정과 6·25 전쟁 시기에 한국군을 지도하러 온 미군 군사고문관들이 한국말을 거의 못 하고 현지 사정에 어두워 어수룩해 보였던 데서 나왔다는 설명이 널리 알려져 있다. 군사고문관 파견은 1960년대까지 이어졌다.',
 '{"en": "The widely told explanation: US military advisers sent to train the Korean army during the US military government and the Korean War barely spoke Korean and did not know local conditions, so they came across as clueless. Adviser postings continued into the 1960s.", "ja": "米軍政期と朝鮮戦争の頃、韓国軍の指導に来た米軍の軍事顧問官たちが韓国語をほとんど話せず現地事情にも疎く、間抜けに見えたことに由来するという説明が広く知られている。顧問官の派遣は1960年代まで続いた。", "es": "La explicación más difundida: los asesores militares estadounidenses enviados a instruir al ejército coreano durante el gobierno militar de EE. UU. y la guerra de Corea apenas hablaban coreano y desconocían el terreno, así que parecían despistados. Los envíos de asesores siguieron hasta los años 60.", "vi": "Cách giải thích phổ biến: các cố vấn quân sự Mỹ sang huấn luyện quân đội Hàn thời chính quyền quân quản Mỹ và Chiến tranh Triều Tiên hầu như không nói được tiếng Hàn, lại mù mờ tình hình địa phương nên trông ngờ nghệch. Việc cử cố vấn kéo dài đến thập niên 1960.", "de": "Die verbreitete Erklärung: US-Militärberater, die während der US-Militärregierung und des Koreakriegs die koreanische Armee ausbilden sollten, sprachen kaum Koreanisch und kannten die Lage vor Ort nicht — sie wirkten ahnungslos. Berater wurden bis in die 1960er entsandt."}'::jsonb,
 '사람을 깎아내리는 말이라 본인 앞에서 쓰면 모욕이 된다. 주로 뒤에서 흉을 보거나, 나 오늘 완전 고문관이었어처럼 자기 실수를 자조할 때 쓴다.',
 '{"en": "It puts people down, so saying it to someone face to face is an insult. It mostly comes up behind someone''s back, or as self-mockery: 나 오늘 완전 고문관이었어 (I was a total screw-up today).", "ja": "人をけなす言葉なので本人の前で使うと侮辱になる。主に陰で悪口を言うときや、나 오늘 완전 고문관이었어(今日の私、完全にポンコツだった)のように自分の失敗を自嘲するときに使う。", "es": "Rebaja a la persona, así que decirlo a la cara es un insulto. Suele usarse a espaldas de alguien o para reírse de uno mismo: 나 오늘 완전 고문관이었어 (hoy he sido un desastre total).", "vi": "Đây là từ hạ thấp người khác nên nói trước mặt là xúc phạm. Thường dùng khi nói xấu sau lưng, hoặc tự giễu kiểu 나 오늘 완전 고문관이었어 (hôm nay tớ vụng về hết chỗ nói).", "de": "Es setzt Menschen herab — jemandem ins Gesicht gesagt ist es eine Beleidigung. Meist hinter dem Rücken oder als Selbstironie: 나 오늘 완전 고문관이었어 (ich war heute ein totaler Tollpatsch)."}'::jsonb,
 '{일잘러}'::text[], '{}'::text[], 0, 0,
 '[{"lang": "🇺🇸 EN", "text": "The hopeless one / screw-up (army slang)"}, {"lang": "🇯🇵 JA", "text": "お荷物・ポンコツ(軍隊スラング)"}, {"lang": "🇨🇳 ZH", "text": "拖后腿的笨蛋(军队俚语)"}, {"lang": "🇻🇳 VI", "text": "Kẻ vụng về (tiếng lóng quân đội)"}, {"lang": "🇪🇸 ES", "text": "El patoso (jerga militar)"}, {"lang": "🇩🇪 DE", "text": "Tollpatsch (Armee-Slang)"}]'::jsonb),
('498', '급식체', 'Geup-sik-che', 'daily', null, '급식 먹는 10대들의 인터넷 말투', '{"en": "School-lunch speak — the teen internet slang style", "ja": "給食世代(10代)のネット口調", "es": "Habla de comedor escolar: la jerga adolescente de internet", "vi": "Giọng học sinh — kiểu nói lóng trên mạng của tuổi teen", "de": "Schulkantinen-Sprech — der Internet-Slang von Teenagern"}'::jsonb, '[급씩체]',
 '[{"type": "명사", "definition": "학교 급식을 먹는 초·중·고등학생이 쓰는 말투라는 뜻. ㅇㅈ? ㅇ ㅇㅈ, 실화냐, 오지다처럼 인터넷 방송과 커뮤니티에서 퍼진 줄임말·초성·말놀이를 몰아 쓰는 10대 특유의 문체를 통틀어 이른다. 같은 틀로 직장인 말투를 가리키는 급여체가 뒤이어 생겼다.", "definition_i18n": {"en": "Literally the speech of students who eat school lunch. It covers the whole teen style that piles up abbreviations, initial-consonant shorthand and wordplay spread by internet streamers and communities, such as ㅇㅈ? ㅇ ㅇㅈ, 실화냐 and 오지다. The same pattern later gave 급여체 for office-worker speak.", "ja": "学校給食を食べる小中高生の口調という意味。ㅇㅈ? ㅇ ㅇㅈ、실화냐、오지다のように、ネット放送やコミュニティで広まった略語・初声・言葉遊びを詰め込む10代特有の文体を総称する。同じ型で会社員の口調を指す급여체が後に生まれた。", "es": "Literalmente, el habla de los alumnos que comen en el comedor escolar. Engloba el estilo adolescente que acumula abreviaturas, iniciales consonánticas y juegos de palabras difundidos por streamers y foros, como ㅇㅈ? ㅇ ㅇㅈ, 실화냐 u 오지다. Con el mismo molde surgió después 급여체 para el habla de oficina.", "vi": "Nghĩa đen là giọng của học sinh ăn cơm trưa ở trường. Chỉ chung lối viết đặc trưng tuổi teen dồn từ viết tắt, phụ âm đầu và chơi chữ lan từ các streamer và cộng đồng mạng, như ㅇㅈ? ㅇ ㅇㅈ, 실화냐, 오지다. Theo cùng khuôn, sau này có 급여체 chỉ giọng dân văn phòng.", "de": "Wörtlich die Sprechweise von Schüler*innen, die in der Schulkantine essen. Gemeint ist der ganze Teenie-Stil voller Abkürzungen, Anfangskonsonanten und Wortspiele aus Streams und Online-Foren, etwa ㅇㅈ? ㅇ ㅇㅈ, 실화냐 oder 오지다. Nach demselben Muster entstand später 급여체 für Bürosprech."}, "examples": [{"kor": "요즘 중학생들 카톡 보면 완전 급식체라 반은 못 알아듣겠어.", "eng": "Middle schoolers'' texts these days are pure school-lunch speak — I cannot follow half of it.", "ja": "最近の中学生のカトク、完全に給食体で半分は分からない。", "es": "Los mensajes de los chavales de secundaria son puro habla de comedor: no entiendo ni la mitad.", "vi": "Tin nhắn của học sinh cấp hai bây giờ toàn giọng teen, nửa phần tớ đọc không hiểu.", "de": "Die Chats von Mittelschüler*innen heute sind purer Kantinen-Sprech — die Hälfte verstehe ich nicht."}]}]'::jsonb,
 '2010년대 중반 인터넷 방송인의 말투와 온라인 커뮤니티 표현이 SNS를 타고 10대에게 퍼졌고, 2017년 무렵 언론과 방송이 급식체라는 이름으로 소개하면서 널리 알려졌다. 이름은 10대를 낮잡아 부르는 급식충에서 나왔다는 설명이 있다.',
 '{"en": "In the mid-2010s, internet streamers'' catchphrases and online-community expressions spread to teens via social media; around 2017 the press and TV introduced the style as 급식체 and the name caught on. The name is said to come from 급식충, a slur for teenagers.", "ja": "2010年代半ば、ネット放送者の口調やオンラインコミュニティの表現がSNSを通じて10代に広まり、2017年頃に報道や放送が급식체の名で紹介して広く知られた。名前は10代を見下す呼び方급식충から来たという説明がある。", "es": "A mediados de los 2010, las muletillas de streamers y expresiones de foros llegaron a los adolescentes por redes sociales; hacia 2017 la prensa y la televisión lo presentaron como 급식체 y el nombre cuajó. Se dice que viene de 급식충, un insulto para adolescentes.", "vi": "Giữa thập niên 2010, câu cửa miệng của streamer và cách nói trên cộng đồng mạng lan tới tuổi teen qua mạng xã hội; khoảng năm 2017 báo chí, truyền hình giới thiệu với tên 급식체 và cái tên phổ biến từ đó. Tên gọi được cho là từ 급식충, từ miệt thị tuổi teen.", "de": "Mitte der 2010er gelangten Sprüche von Streamern und Ausdrücke aus Online-Foren über soziale Medien zu Teenagern; um 2017 stellten Presse und Fernsehen den Stil als 급식체 vor, und der Name setzte sich durch. Er soll von 급식충 stammen, einem Schimpfwort für Teenager."}'::jsonb,
 '10대 말투를 통틀어 가리키는 이름이라, 누군가의 말투를 두고 완전 급식체네처럼 평가할 때 주로 쓴다. 이름의 뿌리인 급식충은 10대를 낮잡는 비하어라 쓰지 않는다.',
 '{"en": "As a label for teen speech as a whole, it mostly appears when commenting on how someone talks: 완전 급식체네 (that is total school-lunch speak). Its root 급식충 is a slur against teenagers — do not use it.", "ja": "10代の口調を総称する名前なので、완전 급식체네(完全に給食体だね)のように誰かの話し方を評するときに主に使う。名前の元の급식충は10代を見下す蔑称なので使わない。", "es": "Como etiqueta del habla adolescente en general, suele salir al comentar cómo habla alguien: 완전 급식체네 (eso es puro habla de comedor). Su raíz 급식충 es un insulto contra los adolescentes: no la uses.", "vi": "Vì là tên gọi chung cho giọng tuổi teen, từ này chủ yếu dùng khi nhận xét cách nói của ai đó: 완전 급식체네 (đúng chuẩn giọng teen). Gốc của nó là 급식충, từ miệt thị tuổi teen — đừng dùng.", "de": "Als Sammelbegriff für Teenie-Sprech fällt es meist, wenn man jemandes Ausdrucksweise kommentiert: 완전 급식체네 (voll Kantinen-Sprech). Die Wurzel 급식충 ist ein Schimpfwort für Teenager — nicht verwenden."}'::jsonb,
 '{ㅇㅈ,실화냐,오지다}'::text[], '{}'::text[], 0, 0,
 '[{"lang": "🇺🇸 EN", "text": "Teen internet slang style"}, {"lang": "🇯🇵 JA", "text": "給食体(10代のネット口調)"}, {"lang": "🇨🇳 ZH", "text": "学生党网络用语"}, {"lang": "🇻🇳 VI", "text": "Kiểu nói lóng tuổi teen"}, {"lang": "🇪🇸 ES", "text": "Jerga adolescente de internet"}, {"lang": "🇩🇪 DE", "text": "Teenie-Internetslang"}]'::jsonb);
