-- 난리자베스/테무인간 추가 (2026-08-31, 운영자 승인 — slang_candidates native_review_pending 배치).

begin;

insert into public.words (id, word, romanization, category, short_desc, short_desc_i18n, pronunciation, meanings, origin, origin_i18n, usage, usage_i18n, related_words, likes, saves, translations) values
('112', '난리자베스', 'Nal-Li-Ja-Be-Seu', 'new-slang', '정신없이 난리 난 상황을 부르는 말',
$j${"de":"Ein Wort für totales Chaos","en":"A word for when everything is total chaos","es":"Palabra para cuando todo es un caos","ja":"てんやわんやの大混乱を指す言葉","vi":"Từ chỉ lúc mọi thứ loạn hết cả lên"}$j$::jsonb,
'[날리자베스]',
$j$[{"type":"명사","examples":[{"de":"Auf der Arbeit ist heute das totale Chaos.","es":"Hoy la oficina es un caos total.","ja":"今日の会社、完全にナンリザベスだわ。","vi":"Hôm nay công ty loạn hết cả lên.","eng":"Work is absolute chaos today.","kor":"오늘 회사 완전 난리자베스야."},{"de":"Kaum ging der Ticketverkauf los, stürzte der Server ab – totales Chaos haha","es":"En cuanto abrieron la venta se cayó el servidor: un caos jaja","ja":"チケット販売開始した瞬間サーバー落ちてナンリザベスw","vi":"Vừa mở bán vé là sập server, loạn hết ㅋㅋ","eng":"The server crashed the second ticketing opened — total chaos lol","kor":"티켓팅 시작하자마자 서버 터져서 난리자베스ㅋㅋ"}],"definition":"'난리'에 영국 여왕 이름 '엘리자베스'를 붙여 만든 말. 상황이 몹시 어수선하고 정신없을 때 '난리 났다'를 더 과장되고 우스꽝스럽게 표현한다.","definition_i18n":{"de":"난리 (Chaos, Tumult) verschmolzen mit dem Namen Elisabeth. Eine albernere, übertriebenere Art zu sagen, dass alles drunter und drüber geht.","en":"난리 (chaos, a riot) fused with the name Elizabeth. A goofier, more over-the-top way of saying things have gone completely haywire.","es":"난리 (jaleo, caos) pegado al nombre Isabel. Una forma más exagerada y payasa de decir que todo se ha desmadrado.","ja":"「난리(大騒ぎ)」に英国女王の名「エリザベス」をくっつけた語。「大騒ぎだ」をより大げさで滑稽に言う表現。","vi":"난리 (loạn, náo động) ghép với tên nữ hoàng Elizabeth. Cách nói phóng đại và hài hước hơn của 'loạn hết rồi'."}}]$j$::jsonb,
'인스타그램 유저 @oh_sangchu가 ''2026을 강타할 유행어 배포''라는 릴스로 직접 만들어 퍼뜨린 이른바 셀프 유행어. 어울리지 않는 두 단어를 붙인 아재개그식 말맛이 재미 포인트다.',
$j${"de":"Ein selbstgemachtes Modewort: Instagram-Nutzer @oh_sangchu prägte es in einem Reel mit dem Titel 'Ich verteile den Spruch, der 2026 einschlägt'. Der Witz ist der Papa-Witz, zwei völlig unpassende Wörter zusammenzukleben.","en":"A self-made buzzword: Instagram user @oh_sangchu coined it in a reel billed as 'handing out the catchphrase that will hit in 2026'. The joke is the dad-joke mismatch of gluing two unrelated words together.","es":"Una palabra de moda autofabricada: el usuario de Instagram @oh_sangchu la acuñó en un reel titulado 'repartiendo la expresión que arrasará en 2026'. La gracia está en el chiste de padre de juntar dos palabras que no pegan.","ja":"インスタグラムのユーザー@oh_sangchuが「2026年を席巻する流行語を配布」というリールで自ら作って広めた、いわゆるセルフ流行語。かみ合わない二語をくっつけたおやじギャグ的な語感が面白さの核心。","vi":"Một từ thời thượng tự chế: người dùng Instagram @oh_sangchu tạo ra trong một reel với tiêu đề 'phát hành câu cửa miệng sẽ càn quét 2026'. Cái vui nằm ở kiểu đùa nhạt khi ghép hai từ chẳng liên quan."}$j$::jsonb,
'감탄사처럼 문장 끝이나 단독으로 쓴다. ''완전 난리자베스'', ''난리자베스네'' 형태가 흔하다. 유행 초기 단어라 아는 사람만 알아듣는다.',
$j${"de":"Wird wie ein Ausruf verwendet, allein oder am Satzende: '완전 난리자베스', '난리자베스네'. Noch sehr frisch – nicht jeder versteht es.","en":"Used like an exclamation, on its own or at the end of a sentence — '완전 난리자베스', '난리자베스네'. Still fresh, so not everyone will get it.","es":"Se usa como exclamación, sola o al final de la frase: '완전 난리자베스', '난리자베스네'. Aún es muy nueva, así que no todo el mundo la pilla.","ja":"感嘆詞のように文末や単独で使う。「완전 난리자베스」「난리자베스네」の形が多い。まだ新しい語なので通じない相手もいる。","vi":"Dùng như thán từ, đứng một mình hoặc cuối câu: '완전 난리자베스', '난리자베스네'. Còn rất mới nên không phải ai cũng hiểu."}$j$::jsonb,
array['헐','갑분싸'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Absolute chaos / a total mess"},{"lang":"🇯🇵 JA","text":"てんやわんや、大混乱"},{"lang":"🇨🇳 ZH","text":"一片混乱、鸡飞狗跳"},{"lang":"🇻🇳 VI","text":"Loạn hết cả lên"},{"lang":"🇪🇸 ES","text":"Un caos total"},{"lang":"🇩🇪 DE","text":"Totales Chaos"}]$j$::jsonb),

('113', '테무인간', 'Te-Mu-In-Gan', 'new-slang', '공은 들였는데 결과물이 못 미더운 사람',
$j${"de":"Jemand, der sich müht, dessen Ergebnis aber nicht überzeugt","en":"Someone who puts in the work but whose output you cannot trust","es":"Alguien que se esfuerza pero cuyo resultado no convence","ja":"努力はするのに出来がいまいちな人","vi":"Người chăm làm nhưng kết quả không đáng tin"}$j$::jsonb,
'[테무인간]',
$j$[{"type":"명사","examples":[{"de":"Ich habe massenhaft Folien gemacht und keine ist brauchbar … ich bin echt ein Temu-Mensch.","es":"Hice un montón de diapositivas y no sirve ninguna… soy un humano Temu total.","ja":"資料は山ほど作ったのに使えるのがない…完全にテムー人間だわ。","vi":"Làm cả đống tài liệu mà chẳng dùng được cái nào… đúng là người Temu.","eng":"I made tons of slides and none of them are usable… I am such a Temu human.","kor":"자료는 잔뜩 만들었는데 쓸 게 없어… 나 완전 테무인간이네."}],"definition":"중국 초저가 쇼핑앱 '테무'에서 딴 말. 테무 상품처럼 싸지만 품질을 믿기 어렵다는 데 빗대, 열심히는 하는데 결과물이 별로인 사람을 가리킨다. 출처에 따라 '겉만 번지르르하고 알맹이가 없는 사람', '싸구려로 도배한 사람'으로도 쓰여 뜻이 아직 하나로 굳지 않았다.","definition_i18n":{"de":"Von Temu, der chinesischen Ultra-Billig-Shopping-App: wie ein Temu-Produkt — billig, aber von unberechenbarer Qualität — jemand, der sich müht und doch schwach abliefert. Andere Quellen meinen damit Menschen, die auffällig wirken, aber nichts dahinter haben, oder die sich komplett in Billigware kleiden; die Bedeutung ist noch nicht gefestigt.","en":"From Temu, the Chinese ultra-budget shopping app: like a Temu product, cheap but of unpredictable quality — someone who works hard yet delivers poorly. Some sources instead use it for people who look flashy but have no substance, or who dress entirely in cheap knock-offs; the meaning has not settled into one.","es":"Viene de Temu, la app china de compras ultrabaratas: como un producto de Temu, barato pero de calidad impredecible — alguien que se esfuerza pero entrega mal. Otras fuentes lo usan para quien aparenta mucho y no tiene fondo, o para quien va vestido entero de imitaciones baratas; el significado aún no está fijado.","ja":"中国の激安ショッピングアプリ「Temu」から来た語。テムの商品のように安いが品質が当てにならないことに例え、頑張ってはいるが出来がいまいちな人を指す。出典によっては「見た目だけで中身がない人」「安物ずくめの人」の意でも使われ、意味はまだ一つに定まっていない。","vi":"Từ Temu, ứng dụng mua sắm siêu rẻ của Trung Quốc: như hàng Temu, rẻ nhưng chất lượng hên xui — người chăm làm mà kết quả kém. Có nguồn lại dùng cho người trông hào nhoáng mà rỗng ruột, hoặc người mặc toàn đồ rẻ tiền; nghĩa vẫn chưa thống nhất."}}]$j$::jsonb,
'''테무(Temu)'' + ''인간''. 누가 처음 만들었는지는 확인되지 않았고, 2025~2026년 SNS 신조어 목록과 신조어 사전 사이트를 통해 퍼졌다. 뜻풀이가 출처마다 갈리는 정착 중인 말이다.',
$j${"de":"Temu + 인간 (Mensch). Wer es geprägt hat, ist nicht belegt; es verbreitete sich 2025-26 über Social-Media-Slanglisten und Slang-Wörterbuchseiten. Die Definitionen unterscheiden sich je nach Quelle – das Wort festigt sich noch.","en":"Temu + 인간 (human). No individual coiner has been verified; it spread through 2025-26 social-media slang roundups and slang-dictionary sites. Definitions differ across sources — it is still settling.","es":"Temu + 인간 (humano). No se ha verificado quién lo acuñó; se difundió por recopilaciones de argot en redes y webs de diccionarios de jerga en 2025-26. Las definiciones varían entre fuentes: aún se está asentando.","ja":"「Temu」+「인간(人間)」。誰が最初に作ったかは確認されておらず、2025~26年のSNSの新語まとめや新語辞典サイトを通じて広まった。出典ごとに語釈が分かれる、定着途上の語。","vi":"Temu + 인간 (con người). Chưa xác minh được ai đặt ra; lan qua các bài tổng hợp tiếng lóng trên mạng xã hội và trang từ điển tiếng lóng 2025-26. Các nguồn định nghĩa khác nhau — từ này còn đang định hình."}$j$::jsonb,
'사람을 깎아내리는 말이라 당사자 앞에서 쓰면 실례다. 주로 뒷담화나 자조에 쓰고, 뜻이 갈리는 말이라 상대가 다르게 알아들을 수 있다.',
$j${"de":"Das Wort setzt jemanden herab – ins Gesicht gesagt ist es unhöflich; es taucht meist beim Lästern oder in Selbstironie auf. Da die Bedeutung schwankt, kann das Gegenüber es anders verstehen.","en":"It puts someone down, so saying it to their face is rude — it mostly shows up in venting or self-deprecation. Because the meaning varies, the other person may read it differently than you meant.","es":"Menosprecia a alguien, así que decírselo a la cara es de mala educación; suele aparecer en desahogos o en autocrítica. Como el sentido varía, el otro puede entenderlo distinto.","ja":"人をけなす語なので本人の前で使うのは失礼。主に陰口や自虐に使う。語義が割れているため、相手が別の意味に取ることもある。","vi":"Đây là lời chê nên nói thẳng mặt là bất lịch sự; thường dùng khi nói sau lưng hoặc tự giễu. Vì nghĩa chưa thống nhất, người nghe có thể hiểu khác ý bạn."}$j$::jsonb,
array['좋좋소','뇌절'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Temu-tier person (cheap, unreliable output)"},{"lang":"🇯🇵 JA","text":"テムー人間(安かろう悪かろうな人)"},{"lang":"🇨🇳 ZH","text":"Temu人(廉价低质的人)"},{"lang":"🇻🇳 VI","text":"Người kiểu Temu (rẻ mà không đáng tin)"},{"lang":"🇪🇸 ES","text":"Persona nivel Temu"},{"lang":"🇩🇪 DE","text":"Temu-Mensch"}]$j$::jsonb);

commit;
