-- 두존크/젬민이/밤티 추가 (2026-08-31, 운영자 승인 — slang_candidates native_review_pending 배치).
-- 두쫀쿠/잼민이도 함께 추가 (운영자 지시 — 두존크/젬민이의 어원에 등장하는 원 단어).
-- 두쫀쿠/잼민이는 candidates 파이프라인을 거치지 않은 신규 항목이라, 삽입 전 웹 검색으로
-- 독립 출처 2개 이상 교차 확인함(위키백과·나무위키·브런치·하퍼스바자 등). 잼민이 어원은
-- 여러 출처가 공통으로 드는 설이나 공식 확정은 아니라 "설이 널리 퍼져 있다"로 표기.
--
-- NOTE: filename timestamp differs from the production migration version
-- (MCP apply time becomes the version) — repo-wide convention, see CLAUDE.md.

begin;

insert into public.words (id, word, romanization, category, short_desc, short_desc_i18n, pronunciation, meanings, origin, origin_i18n, usage, usage_i18n, related_words, likes, saves, translations) values
('106', '두존크', 'Du-Jon-Keu', 'slang', '두상이 크다고 놀리는 비속어',
$j${"en":"A crude joke about someone having a big head","ja":"頭がでかいとからかう俗語","es":"Una pulla vulgar sobre tener la cabeza grande","vi":"Tiếng lóng thô trêu người đầu to","de":"Ein derber Spruch über einen großen Kopf"}$j$::jsonb,
'[두존크]',
$j$[{"type":"명사","examples":[{"de":"Alter, warum passt die Mütze nicht … Großkopf bestätigt?","es":"Tío, ¿por qué no te entra la gorra?… ¿admites que tienes cabezón?","ja":"おい帽子入らないじゃん…頭でかいの認める?","vi":"Ê sao cái mũ không vừa… công nhận đầu to chưa?","eng":"Bro why does the cap not fit… big-head confirmed?","kor":"야 모자 왜 안 맞냐… 두존크 인정?"}],"definition":"'두상이 존나 크다'의 줄임말로, 머리 크기를 두고 장난스럽게 놀릴 때 쓰는 비속어. '두쫀쿠(두바이 쫀득 쿠키)'처럼 세 글자로 줄이는 유행에 얹은 말장난이다. '존나'가 들어간 욕설 계열이라 공적인 자리에서는 쓰지 않는다.","definition_i18n":{"de":"Kurzform von 두상이 존나 크다 (dein Kopf ist verdammt groß) – ein derber, spielerischer Spruch über die Kopfgröße, im Sog der Mode dreisilbiger Abkürzungen wie 두쫀쿠 (zäher Dubai-Keks). Enthält das Schimpfwort 존나 und passt daher nicht in förmliche Situationen.","en":"Short for 두상이 존나 크다 (your head is damn huge) — a crude, playful dig at someone's head size, riding the trend of three-syllable abbreviations like 두쫀쿠 (Dubai chewy cookie). It contains the swear 존나, so it is not for polite settings.","es":"Abreviatura de 두상이 존나 크다 (tienes la cabeza jodidamente grande): una burla vulgar y juguetona sobre el tamaño de la cabeza, montada sobre la moda de las siglas de tres sílabas como 두쫀쿠 (galleta chiclosa de Dubái). Lleva la palabrota 존나, así que no vale para contextos formales.","ja":"「두상이 존나 크다(頭がクソでかい)」の略で、頭の大きさをふざけてからかう俗語。「두쫀쿠(ドバイもちもちクッキー)」のような三文字略語の流行に乗った言葉遊び。「존나」という罵り語を含むので公の場では使わない。","vi":"Viết tắt của 두상이 존나 크다 (đầu mày to vãi) — câu trêu thô mà vui về kích cỡ đầu, ăn theo trào lưu viết tắt ba âm tiết như 두쫀쿠 (bánh quy dẻo Dubai). Có chứa từ chửi 존나 nên không dùng nơi trang trọng."}}]$j$::jsonb,
'''두쫀쿠(두바이 쫀득 쿠키)''처럼 세 글자로 줄이는 유행을 따라 만들어진 말장난. 2026년 초 신조어 정리 기사와 SNS 카드뉴스를 통해 퍼졌다. 누가 처음 썼는지는 확인되지 않았다.',
$j${"de":"Ein Wortspiel im Zuge der Mode dreisilbiger Abkürzungen wie 두쫀쿠 (zäher Dubai-Keks). Es verbreitete sich Anfang 2026 über Presseübersichten zu neuem Slang und Social-Media-Cardnews. Wer es zuerst benutzte, ist ungeklärt.","en":"A pun built on the fad for three-syllable abbreviations such as 두쫀쿠 (Dubai chewy cookie). It spread in early 2026 through news round-ups of new slang and social-media card news. Who used it first is unverified.","es":"Un juego de palabras nacido de la moda de abreviar en tres sílabas, como 두쫀쿠 (galleta chiclosa de Dubái). Se difundió a principios de 2026 por artículos que recopilaban jerga nueva y por tarjetas informativas en redes. No está verificado quién lo usó primero.","ja":"「두쫀쿠(ドバイもちもちクッキー)」のような三文字略語の流行に乗って作られた言葉遊び。2026年初めの新語まとめ記事やSNSのカードニュースで広まった。誰が最初に使ったかは未確認。","vi":"Một trò chơi chữ ăn theo mốt viết tắt ba âm tiết như 두쫀쿠 (bánh quy dẻo Dubai). Lan rộng đầu năm 2026 qua các bài báo tổng hợp từ mới và card news trên mạng xã hội. Chưa rõ ai dùng đầu tiên."}$j$::jsonb,
'''존나''가 들어간 비속어라 아주 친한 사이의 농담에서만 쓴다. 외모를 놀리는 말이므로 처음 만난 사람이나 윗사람에게는 절대 쓰지 않는다.',
$j${"de":"Es enthält das Schimpfwort 존나 – also nur als Scherz unter engen Freunden. Es macht sich über das Aussehen lustig: nie bei Fremden oder Höhergestellten.","en":"It contains the swear 존나, so keep it to jokes among close friends. It mocks someone's appearance — never use it with strangers or anyone senior to you.","es":"Lleva la palabrota 존나, así que resérvalo para bromas entre amigos muy cercanos. Se mete con el físico: nunca con desconocidos ni con alguien mayor o superior.","ja":"「존나」という罵り語を含むので、ごく親しい間柄の冗談でのみ使う。外見をからかう語なので、初対面の相手や目上の人には絶対に使わない。","vi":"Có chứa từ chửi 존나 nên chỉ dùng đùa giữa bạn rất thân. Đây là lời chê ngoại hình — tuyệt đối không dùng với người lạ hay người trên."}$j$::jsonb,
array['존버','존맛탱'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Damn big head (crude tease)"},{"lang":"🇯🇵 JA","text":"頭クソでかい(からかい)"},{"lang":"🇨🇳 ZH","text":"头贼大(粗俗玩笑)"},{"lang":"🇻🇳 VI","text":"Đầu to vãi (trêu thô)"},{"lang":"🇪🇸 ES","text":"Cabezón de cojones (burla vulgar)"},{"lang":"🇩🇪 DE","text":"Verdammt großer Kopf (derb)"}]$j$::jsonb),

('107', '젬민이', 'Jem-Mi-Ni', 'new-slang', '사소한 결정까지 AI에게 맡기는 사람',
$j${"de":"Jemand, der selbst Kleinigkeiten von der KI entscheiden lässt","en":"Someone who lets AI decide even the little things","es":"Alguien que deja hasta las decisiones más nimias en manos de la IA","ja":"些細な決断までAIに任せる人","vi":"Người giao cả những quyết định nhỏ nhặt cho AI"}$j$::jsonb,
'[젬미니]',
$j$[{"type":"명사","examples":[{"de":"Du hast sie auch gefragt, was du essen sollst? Du bist echt ein Jemmini haha","es":"¿También le preguntaste qué comer? Eres un jemmini total jaja","ja":"昼ごはんまで聞いたの?完全にジェムミニじゃんw","vi":"Ăn trưa gì cũng hỏi luôn à? Đúng là jemmini thật ㅋㅋ","eng":"You asked it what to have for lunch too? You're such a jemmini lol","kor":"점심 뭐 먹을지도 물어봤어? 너 완전 젬민이네ㅋㅋ"},{"de":"Ich bin neuerdings ein echter Jemmini – ich frage sie sogar, was ich anziehen soll.","es":"Últimamente soy un jemmini de manual: hasta le pregunto qué ropa comprar.","ja":"最近ジェムミニになっちゃった。服買うときも聞いてる。","vi":"Dạo này mình thành jemmini luôn, mua áo cũng hỏi nó.","eng":"I've turned into a total jemmini lately — I even ask it what clothes to buy.","kor":"나 요즘 젬민이 다 됐어. 옷 살 때도 물어봄."}],"definition":"구글 AI '제미나이(Gemini)'와 어린아이를 뜻하는 '잼민이'를 합친 말. 점심 메뉴부터 여행 계획까지 크고 작은 결정을 AI에게 물어보고 그대로 따르는 사람을 가리킨다. 놀리는 뉘앙스와 자조적 뉘앙스가 함께 있다.","definition_i18n":{"de":"Mischung aus Googles KI Gemini und 잼민이 (nerviges Kind): jemand, der die KI zu allem befragt – vom Mittagessen bis zur Reiseplanung – und ihrem Rat einfach folgt. Neckisch wie auch selbstironisch.","en":"A blend of Google's AI Gemini and 잼민이 (a bratty kid) — someone who asks AI about everything from what to eat for lunch to travel plans and just goes with the answer. Used both teasingly and self-deprecatingly.","es":"Mezcla de la IA Gemini de Google y 잼민이 (crío pesado): alguien que consulta a la IA desde qué comer hasta sus vacaciones y hace lo que le diga. Se usa en broma y para reírse de uno mismo.","ja":"GoogleのAI「Gemini」と、生意気な子どもを指す「잼민이」を合わせた語。昼食から旅行の計画まで何でもAIに聞いてその通りにする人。からかいにも自虐にも使う。","vi":"Ghép giữa AI Gemini của Google và 잼민이 (nhóc ranh): người hỏi AI mọi thứ từ ăn trưa gì đến kế hoạch du lịch rồi làm y vậy. Dùng để trêu và cũng để tự giễu."}}]$j$::jsonb,
'구글 AI ''제미나이(Gemini)''와 기존 신조어 ''잼민이''를 합성한 말. 생성형 AI가 일상 깊숙이 들어온 2026년 세태를 꼬집는 단어로, 언론의 ''요즘말 사전'' 코너와 SNS 신조어 목록을 통해 퍼졌다.',
$j${"de":"Kofferwort aus Googles Gemini und dem bestehenden Slang 잼민이 (Kind). Verbreitete sich 2026 über Zeitungskolumnen zu neuen Wörtern und Social-Media-Listen – als Seitenhieb darauf, wie alltäglich generative KI geworden ist.","en":"A portmanteau of Google's Gemini and the existing slang 잼민이 (a kid). It spread in 2026 through newspaper new-word columns and social-media slang roundups, as a jab at how deeply generative AI has entered daily life.","es":"Acrónimo de Gemini (la IA de Google) y el argot ya existente 잼민이 (crío). Se difundió en 2026 por secciones de prensa sobre palabras nuevas y recopilaciones en redes, como pulla a lo cotidiana que se ha vuelto la IA generativa.","ja":"GoogleのAI「Gemini」と既存の俗語「잼민이」の合成語。生成AIが日常に入り込んだ2026年の世相を皮肉る語として、新聞の流行語コーナーやSNSの新語まとめで広まった。","vi":"Ghép từ Gemini (AI của Google) và tiếng lóng có sẵn 잼민이 (nhóc con). Lan rộng năm 2026 qua các bài tổng hợp từ mới trên báo và các bài tổng hợp tiếng lóng trên mạng xã hội, châm biếm việc AI tạo sinh len vào đời sống."}$j$::jsonb,
'AI에 지나치게 의존하는 친구를 놀릴 때, 또는 ''나 젬민이야''처럼 스스로를 낮춰 말할 때 쓴다. 심한 비난이 아니라 가벼운 농담에 가깝다.',
$j${"de":"Um Freunde zu necken, die zu sehr auf KI setzen, oder über sich selbst ('Ich bin so ein Jemmini'). Leichter Scherz, keine echte Kritik.","en":"Used to tease a friend who leans on AI too much, or about yourself ('I'm such a jemmini'). A light joke, not a real insult.","es":"Para picar a un amigo que abusa de la IA, o sobre uno mismo ('soy un jemmini'). Es broma ligera, no un insulto.","ja":"AIに頼りすぎる友達をからかうとき、または「私、젬민이だから」と自虐的に使う。強い非難ではなく軽い冗談。","vi":"Dùng trêu bạn quá phụ thuộc AI, hoặc tự nói về mình ('tôi jemmini lắm'). Là đùa nhẹ, không phải chê bai."}$j$::jsonb,
array['핑프','갓생'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"AI-dependent person (Gemini kid)"},{"lang":"🇯🇵 JA","text":"AI丸投げ人間"},{"lang":"🇨🇳 ZH","text":"凡事都问AI的人"},{"lang":"🇻🇳 VI","text":"Người gì cũng hỏi AI"},{"lang":"🇪🇸 ES","text":"Adicto a preguntarle todo a la IA"},{"lang":"🇩🇪 DE","text":"KI-hörige Person"}]$j$::jsonb),

('108', '밤티', 'Bam-Ti', 'new-slang', '촌스럽고 어설퍼서 오히려 웃긴 것',
$j${"de":"So kitschig und schlampig, dass es wieder lustig ist","en":"So tacky and clumsy that it loops back to funny","es":"Tan hortera y chapucero que acaba haciendo gracia","ja":"ダサくて雑すぎて逆に面白いもの","vi":"Quê và vụng đến mức thành buồn cười"}$j$::jsonb,
'[밤티]',
$j$[{"type":"명사","examples":[{"de":"Das Poster ist ziemlich kitschig – genau deshalb mag ich es.","es":"Este cartel es un poco hortera, y por eso mismo me encanta.","ja":"このポスター、ちょっとダサいけどそこがいい。","vi":"Cái poster này hơi quê mà chính vì vậy mới thích.","eng":"This poster is kind of tacky, and that is exactly why I like it.","kor":"이 포스터 좀 밤티한데 그래서 더 좋아."},{"de":"Mein Profilbild ist der Gipfel an Kitsch haha, aber ich ändere es nicht.","es":"Mi foto de perfil es lo más hortera que hay jaja, pero no la cambio.","ja":"私のアイコン、ダサさの極みだけど変えないw","vi":"Ảnh đại diện của mình quê hết nấc ㅋㅋㅋ mà không đổi đâu.","eng":"My profile pic is peak tacky lol but I am not changing it.","kor":"내 프사 밤티 그 자체ㅋㅋㅋ 근데 안 바꿀 거야."}],"definition":"원래는 '못생겼다·촌스럽다'는 뜻이었으나, 지금은 어설프고 과장된 키치한 분위기를 가리키며 그 어설픔 자체를 즐기는 말로 쓰인다. 놀림과 애정이 섞여 있다. '밤티하다', '밤티 감성'처럼도 쓴다.","definition_i18n":{"de":"Ursprünglich schlicht 'hässlich' oder 'kitschig', heute eine schlampig-übertriebene Kitsch-Ästhetik, die man gerade wegen ihrer Machart mag. Halb Spott, halb Zuneigung; auch als 밤티하다 oder 밤티 감성.","en":"It started out meaning simply 'ugly' or 'tacky', but now points to a clumsy, over-the-top kitsch vibe that people enjoy precisely because it is badly done. Half mockery, half affection; also used as 밤티하다 or 밤티 감성.","es":"Empezó significando simplemente 'feo' u 'hortera', pero ahora apunta a una estética kitsch, chapucera y exagerada que gusta justo por estar mal hecha. Mitad burla, mitad cariño; también 밤티하다 o 밤티 감성.","ja":"元は「ブサイク・ダサい」の意だったが、今は雑で大げさなキッチュな雰囲気を指し、その雑さ自体を楽しむ語として使われる。からかいと愛着が混ざる。「밤티하다」「밤티 감성」の形でも使う。","vi":"Ban đầu chỉ nghĩa 'xấu, quê', nay chỉ cái vibe kitsch vụng về, lố mà người ta thích chính vì nó làm dở. Nửa trêu nửa thương; còn dùng dạng 밤티하다, 밤티 감성."}}]$j$::jsonb,
'온라인 아바타 게임 ''라인플레이''에서 ''밤티''라는 아이디를 쓰던 유저의 아바타 외모가 2020~2021년 커뮤니티 짤로 돌면서 시작됐다. 서비스 종료 뒤 2025년 X(트위터)에서 다시 퍼졌고, 2026년에는 신문 문화면에서 의도된 어설픔의 미학으로 다뤄질 만큼 자리 잡았다.',
$j${"de":"Es begann mit dem Avatar eines Nutzers namens 밤티 im Spiel LinePlay, dessen Aussehen 2020-21 als Community-Meme kursierte. Nach dem Aus des Spiels tauchte es 2025 auf X wieder auf; 2026 behandelten Zeitungen es als Ästhetik der bewussten Unbeholfenheit.","en":"It began with a LinePlay avatar belonging to a user named 밤티, whose look circulated as a community meme in 2020-21. After the game shut down it resurfaced on X in 2025, and by 2026 newspapers were covering it as an aesthetic of deliberate clumsiness.","es":"Nació del avatar de un usuario llamado 밤티 en el juego LinePlay, cuya pinta circuló como meme comunitario en 2020-21. Tras el cierre del juego reapareció en X en 2025, y en 2026 la prensa ya lo trataba como una estética de torpeza deliberada.","ja":"アバターゲーム「LINE Play」で「밤티」というIDのユーザーのアバターの見た目が2020~21年にコミュニティのネタ画像として広まったのが始まり。サービス終了後の2025年にX(旧Twitter)で再流行し、2026年には新聞の文化面で意図された雑さの美学として扱われるまでになった。","vi":"Bắt đầu từ avatar của một người dùng tên 밤티 trong game LinePlay, ngoại hình đó lan thành meme cộng đồng năm 2020-21. Sau khi game đóng cửa, từ này trở lại trên X năm 2025, và đến 2026 báo chí đã bàn về nó như một thẩm mỹ vụng về có chủ đích."}$j$::jsonb,
'옷차림·사진·디자인이 촌스럽거나 어설플 때 쓴다. 자기 것이나 사물에 쓰면 유머지만, 원래 외모를 놀리던 말에서 나왔으므로 친하지 않은 사람의 외모에는 쓰지 않는 게 좋다.',
$j${"de":"Für Kleidung, Fotos oder Designs, die kitschig oder schlampig wirken. Über eigene Sachen oder Objekte ist es witzig, aber da es aus dem Spott über jemandes Aussehen entstand, besser nicht auf Menschen anwenden, die man kaum kennt.","en":"Use it for clothes, photos or designs that look tacky or clumsy. It is funny about your own stuff or about objects, but since it grew out of mocking someone's looks, do not aim it at people you are not close to.","es":"Úsalo para ropa, fotos o diseños horteras o chapuceros. Sobre tus propias cosas u objetos hace gracia, pero como nació burlándose del físico de alguien, mejor no dirigirlo a gente con la que no tienes confianza.","ja":"服装・写真・デザインがダサい、雑なときに使う。自分のものや物に対してならユーモアだが、元は人の外見をからかう語なので、親しくない相手の外見には使わないほうがいい。","vi":"Dùng cho quần áo, ảnh, thiết kế trông quê hay vụng. Nói về đồ của mình hay vật thì vui, nhưng vì từ này vốn để chê ngoại hình, đừng dùng với người không thân."}$j$::jsonb,
array['킹받다','레전드'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Tacky / cheugy-but-charming"},{"lang":"🇯🇵 JA","text":"ダサかわ、キッチュ"},{"lang":"🇨🇳 ZH","text":"土到有趣、土味审美"},{"lang":"🇻🇳 VI","text":"Quê mà duyên, kitsch"},{"lang":"🇪🇸 ES","text":"Hortera con encanto"},{"lang":"🇩🇪 DE","text":"Kitschig-charmant"}]$j$::jsonb),

('109', '두쫀쿠', 'Du-Jjon-Ku', 'new-slang', '두바이 쫀득 쿠키를 줄인 말, 요즘 핫한 디저트',
$j${"en":"Short for Dubai chewy cookie, the trendy dessert everyone wants","ja":"「ドバイもちもちクッキー」の略、今大人気のスイーツ","es":"Abreviatura de galleta chiclosa de Dubái, el postre de moda","vi":"Viết tắt của bánh quy dẻo Dubai, món tráng miệng đang hot","de":"Kurzform für Dubai-Keks, das angesagte Dessert"}$j$::jsonb,
'[두쫀쿠]',
$j$[{"type":"명사","examples":[{"kor":"오늘 두쫀쿠 사려고 줄 섰는데 결국 완판됐어.","eng":"I stood in line for dujjonku today but it sold out anyway.","ja":"今日ドゥジョンク買うために並んだけど結局売り切れた。","es":"Hoy hice cola para comprar dujjonku pero se agotó igual.","vi":"Hôm nay xếp hàng mua dujjonku mà cuối cùng vẫn hết hàng.","de":"Ich habe heute für Dujjonku angestanden, aber es war trotzdem ausverkauft."}],"definition":"'두바이 쫀득 쿠키'의 줄임말. 마시멜로 반죽으로 감싼 쫀득한 겉면 안에 피스타치오 크림과 카다이프를 채운 중동식 디저트로, 2025년 하반기 한국에서 품절 대란이 날 만큼 유행했다. 사러 갔다가 못 사는 상황을 빗댄 '두케팅(두쫀쿠+티케팅)'이라는 말도 함께 퍼졌다.","definition_i18n":{"en":"Short for 'Dubai chewy cookie' — a Middle Eastern-style dessert with a marshmallow-based chewy shell filled with pistachio cream and crispy kadayif, which triggered sellout frenzies across Korea in late 2025. The buying rush spawned the pun 두케팅 (dujjonku + ticketing).","ja":"「ドバイもちもちクッキー」の略。マシュマロ生地のもちもちした外側にピスタチオクリームとカダイフを詰めた中東風スイーツで、2025年後半に韓国で売り切れ続出の人気を呼んだ。買うための争奪戦から「두케팅(두쫀쿠+チケッティング)」という言葉も生まれた。","es":"Abreviatura de galleta chiclosa de Dubái, un postre de estilo centro-oriental con una capa chiclosa a base de malvavisco rellena de crema de pistacho y kadayif crujiente, que provocó ventas agotadas en toda Corea a finales de 2025. La carrera por comprarla dio origen al juego de palabras 두케팅 (dujjonku + ticketing).","vi":"Viết tắt của bánh quy dẻo Dubai — món tráng miệng kiểu Trung Đông với lớp vỏ dẻo làm từ marshmallow, nhân kem pistachio và kadayif giòn, gây sốt cháy hàng khắp Hàn Quốc cuối năm 2025. Cuộc đua mua hàng sinh ra cách chơi chữ 두케팅 (dujjonku + ticketing).","de":"Kurzform für Dubai-Keks, ein nahöstlich inspiriertes Dessert mit einer zähen Marshmallow-Hülle gefüllt mit Pistaziencreme und knusprigem Kadayif, das Ende 2025 in Korea für ausverkaufte Regale sorgte. Der Kaufrausch brachte das Wortspiel 두케팅 (dujjonku + Ticketing) hervor."}}]$j$::jsonb,
'아랍에미리트 두바이의 초콜릿 디저트(카다이프+피스타치오 크림)를 한국식 쿠키로 재해석한 제품 이름 ''두바이 쫀득 쿠키''를 세 글자로 줄인 말. 2025년 하반기 SNS를 타고 전국적인 소비 열풍이 되면서 줄임말도 함께 퍼졌다.',
$j${"en":"A three-syllable shortening of 'Dubai chewy cookie', a Korean reinterpretation of Dubai's chocolate-and-kadayif dessert as a cookie. It spread nationwide via social media in late 2025 as the treat became a sellout craze.","ja":"アラブ首長国連邦ドバイのチョコレートスイーツ(カダイフ+ピスタチオクリーム)を韓国式クッキーとして再解釈した商品名「두바이 쫀득 쿠키」を三文字に略した語。2025年後半にSNSを通じて全国的な消費ブームとなり、略語も一緒に広まった。","es":"Abreviatura de tres sílabas de 'galleta chiclosa de Dubái', una reinterpretación coreana del postre de chocolate y kadayif de Dubái en forma de galleta. Se difundió por todo el país a través de redes sociales a finales de 2025 conforme el dulce se convertía en furor de ventas agotadas.","vi":"Cách viết tắt ba âm tiết của 'bánh quy dẻo Dubai', phiên bản Hàn Quốc hóa món tráng miệng sô-cô-la và kadayif của Dubai dưới dạng bánh quy. Lan rộng khắp cả nước qua mạng xã hội cuối năm 2025 khi món này trở thành cơn sốt cháy hàng.","de":"Eine dreisilbige Abkürzung von 'Dubai-Keks', einer koreanischen Neuinterpretation von Dubais Schokoladen-Kadayif-Dessert als Keks. Verbreitete sich Ende 2025 landesweit über soziale Medien, als der Snack zum Ausverkaufs-Hype wurde."}$j$::jsonb,
'친구와 디저트 얘기를 하거나, 사러 갔다가 품절돼서 못 샀다는 얘기를 할 때 쓴다. 구매 성공/실패를 말할 때 ''두쫀쿠 티케팅 성공/실패''처럼도 쓴다.',
$j${"en":"Used when chatting about desserts with friends, or complaining it sold out before you could buy it. Also used with buying-success slang, like '두쫀쿠 티케팅 성공/실패' (dujjonku-ticketing success/failure).","ja":"友達とスイーツの話をするときや、買いに行ったのに売り切れだったと言うときに使う。「두쫀쿠 티케팅 성공/실패」のように購入の成否を言うときにも使う。","es":"Se usa al hablar de postres con amigos, o para quejarte de que se agotó antes de poder comprarlo. También se combina con jerga de 'éxito/fracaso en el ticketing', como '두쫀쿠 티케팅 성공/실패'.","vi":"Dùng khi nói chuyện tráng miệng với bạn bè, hoặc than phiền đi mua mà hết hàng. Cũng dùng kèm tiếng lóng 'thành công/thất bại khi mua', như '두쫀쿠 티케팅 성공/실패'.","de":"Wird verwendet, wenn man mit Freunden über Desserts spricht, oder um sich zu beschweren, dass es ausverkauft war. Auch kombiniert mit dem Slang für Kauferfolg/-misserfolg, etwa '두쫀쿠 티케팅 성공/실패'."}$j$::jsonb,
array['두케팅'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Dubai chewy cookie (trendy dessert)"},{"lang":"🇯🇵 JA","text":"ドバイもちもちクッキー(人気スイーツ)"},{"lang":"🇨🇳 ZH","text":"迪拜软心饼干(网红甜点)"},{"lang":"🇻🇳 VI","text":"Bánh quy dẻo Dubai (món tráng miệng hot)"},{"lang":"🇪🇸 ES","text":"Galleta chiclosa de Dubái (postre de moda)"},{"lang":"🇩🇪 DE","text":"Dubai-Keks (angesagtes Dessert)"}]$j$::jsonb),

('110', '잼민이', 'Jaem-Min-I', 'frequently-used', '무례하거나 유치하게 구는 어린 학생을 낮잡아 부르는 말',
$j${"en":"A put-down for a rude or bratty young kid","ja":"無礼で子どもっぽい年下をけなす言葉","es":"Un apodo despectivo para un niño maleducado o infantil","vi":"Từ miệt thị chỉ đứa trẻ hỗn láo hoặc trẻ con","de":"Ein abwertendes Wort für ein freches, kindisches Kind"}$j$::jsonb,
'[잼미니]',
$j$[{"type":"명사","examples":[{"kor":"게임에서 욕하는 애 있길래 봤더니 완전 잼민이더라.","eng":"Someone was swearing in the game, and turned out to be a total jaemmini.","ja":"ゲームで暴言吐いてる子がいて見たら完全にジェムミニだった。","es":"Alguien soltaba palabrotas en el juego, y resultó ser un jaemmini total.","vi":"Có đứa chửi bậy trong game, hóa ra đúng là jaemmini chính hiệu.","de":"Da hat jemand im Spiel geflucht, und es stellte sich heraus: ein totaler Jaemmini."}],"definition":"무례하거나 인성이 안 좋게 구는 어린 학생, 주로 초등학생 또래를 낮잡아 부르는 인터넷 속어. 온라인 게임이나 커뮤니티에서 무례하게 구는 상대를 가리키기도 하고, 나이와 상관없이 유치하게 구는 사람을 놀릴 때도 쓴다.","definition_i18n":{"en":"An internet put-down for a young, typically elementary-school-aged kid who acts rude or bratty. Used both for actually young kids acting up online (games, forums) and, more loosely, to tease anyone — any age — for acting childish.","ja":"無礼で人格が良くない年少者、主に小学生くらいの子を指す俗語。オンラインゲームやコミュニティで無礼にふるまう相手を指すこともあり、年齢に関係なく子どもっぽくふるまう人をからかうときにも使う。","es":"Un apodo despectivo de internet para un niño, normalmente de edad de primaria, que se comporta de forma maleducada o mimada. Se usa tanto para niños de verdad que se portan mal en línea (juegos, foros) como, más sueltamente, para burlarse de cualquiera, sin importar la edad, por actuar de forma infantil.","vi":"Từ miệt thị trên mạng chỉ đứa trẻ, thường cỡ tuổi tiểu học, cư xử hỗn láo hoặc trẻ con. Dùng cho trẻ con thật sự quậy phá trên mạng (game, diễn đàn), và cũng dùng rộng ra để trêu bất kỳ ai, không phân biệt tuổi, vì hành xử trẻ con.","de":"Ein abwertender Internetbegriff für ein Kind, meist im Grundschulalter, das sich frech oder kindisch benimmt. Wird sowohl für tatsächlich junge Kinder verwendet, die sich online (Spiele, Foren) daneben benehmen, als auch lockerer, um jeden – unabhängig vom Alter – wegen kindischen Verhaltens zu necken."}}]$j$::jsonb,
'2019년 하반기 트위치 스트리밍 커뮤니티에서 생긴 말. 후원 메시지를 읽어주는 TTS(문자 음성 변환) 서비스 ''투네이션''의 목소리 이름 ''재민''에, 트위치에서 흔히 붙이는 접두 ''잼(재미)-''을 합쳐 ''잼민이''가 됐다는 설이 널리 퍼져 있다. 2020년 3월 이후 사용이 크게 늘며 정착했다.',
$j${"en":"Coined on Twitch streaming communities in late 2019. The widely circulated theory: it fuses the Twitch prefix 잼- (from 재미, 'fun') with 재민, the name of a text-to-speech voice used by the donation-alert service Toonation, whose childish-sounding voice amused viewers. Usage surged from March 2020 onward.","ja":"2019年後半、Twitchの配信コミュニティで生まれた語。広く言われている説では、Twitchでよく付く接頭辞「잼-(재미=面白いから)」に、後援メッセージ読み上げサービス「トゥーネーション」のTTS音声名「재민」を合わせたもの。その子どもっぽい声が視聴者に笑いを誘ったという。2020年3月以降、使用が急増して定着した。","es":"Acuñado en comunidades de streaming de Twitch a finales de 2019. La teoría más citada: combina el prefijo de Twitch 잼- (de 재미, 'diversión') con 재민, el nombre de una voz de texto a voz usada por el servicio de alertas de donación Toonation, cuya voz de sonido infantil hacía gracia a los espectadores. El uso se disparó a partir de marzo de 2020.","vi":"Ra đời trong cộng đồng streaming Twitch cuối năm 2019. Giả thuyết phổ biến: ghép tiền tố 잼- trên Twitch (từ 재미, 'vui') với 재민, tên giọng đọc chuyển văn bản thành giọng nói của dịch vụ thông báo donate Toonation, giọng nghe trẻ con của nó khiến người xem thấy buồn cười. Cách dùng tăng vọt từ tháng 3/2020.","de":"Entstand Ende 2019 in Twitch-Streaming-Communitys. Die verbreitete Theorie: Es verschmilzt das Twitch-Präfix 잼- (von 재미, 'Spaß') mit 재민, dem Namen einer Text-zu-Sprache-Stimme des Spenden-Alert-Dienstes Toonation, deren kindlich klingende Stimme die Zuschauer amüsierte. Ab März 2020 stieg die Nutzung stark an."}$j$::jsonb,
'온라인 게임이나 커뮤니티에서 무례하게 구는 상대를 비하할 때, 혹은 유치하게 구는 친구를 장난스레 놀릴 때 쓴다. 상대를 낮잡아 부르는 말이라 본인 앞에서 대놓고 쓰면 무례할 수 있다.',
$j${"en":"Used to put down someone acting rude in an online game or community, or to teasingly mock a friend being childish. Since it talks down to the person, saying it straight to their face can come off rude.","ja":"オンラインゲームやコミュニティで無礼にふるまう相手をけなすとき、または子どもっぽい友達をからかうときに使う。相手を見下す言葉なので、本人に向かって直接言うと失礼になり得る。","es":"Se usa para menospreciar a alguien que se porta mal en un juego o comunidad en línea, o para burlarse en broma de un amigo infantil. Como rebaja a la persona, decírselo directamente a la cara puede resultar grosero.","vi":"Dùng để hạ thấp ai đó cư xử hỗn trong game hay cộng đồng mạng, hoặc trêu đùa bạn bè trẻ con. Vì là lời hạ thấp người khác, nói thẳng vào mặt có thể bị coi là bất lịch sự.","de":"Wird verwendet, um jemanden herabzusetzen, der sich in einem Online-Spiel oder einer Community daneben benimmt, oder um einen kindischen Freund necken. Da es die Person herabwürdigt, kann es unhöflich wirken, es ihr direkt ins Gesicht zu sagen."}$j$::jsonb,
array['젬민이'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Bratty kid (internet put-down)"},{"lang":"🇯🇵 JA","text":"生意気な子ども(ネットの俗語)"},{"lang":"🇨🇳 ZH","text":"熊孩子(网络贬称)"},{"lang":"🇻🇳 VI","text":"Nhóc ranh (tiếng lóng miệt thị)"},{"lang":"🇪🇸 ES","text":"Mocoso maleducado (apodo despectivo)"},{"lang":"🇩🇪 DE","text":"Frechdachs (abwertender Netzbegriff)"}]$j$::jsonb);

commit;

-- 적용 후 확인: select count(*) from public.words; → 39 (106~110 추가)
