-- 뇌이징 추가 (2026-08-31, 운영자 지시). candidates 파이프라인 밖 신규 항목이라
-- 삽입 전 웹 검색으로 독립 출처 2개 이상 교차 확인함(나무위키, 클리앙, CIVICNEWS, plus27 등).

begin;

insert into public.words (id, word, romanization, category, short_desc, short_desc_i18n, pronunciation, meanings, origin, origin_i18n, usage, usage_i18n, related_words, likes, saves, translations) values
('111', '뇌이징', 'Noe-I-Jing', 'new-slang', '낯설던 디자인이 자꾸 보다 보면 괜찮아 보이는 현상',
$j${"en":"When a design that looked off starts to look good the more you see it","ja":"見慣れないデザインが見るほど良く見えてくる現象","es":"Cuando un diseño raro empieza a gustarte de tanto verlo","vi":"Hiện tượng thiết kế lạ mắt dần thấy đẹp khi nhìn quen","de":"Wenn ein befremdliches Design mit der Zeit immer besser aussieht"}$j$::jsonb,
'[뇌이징]',
$j$[{"type":"명사","examples":[{"kor":"이 차 처음엔 진짜 이상했는데 요즘 자꾸 예뻐 보여… 나 뇌이징 왔나 봐.","eng":"This car looked so weird at first, but lately it looks good… I think I've been brain-aged.","ja":"この車最初すごい変だと思ったのに最近かっこよく見える…脳エイジング来たかも。","es":"Este coche me pareció rarísimo al principio, pero últimamente lo veo bien… creo que ya me acostumbré.","vi":"Xe này lúc đầu thấy dị vãi mà dạo này lại thấy đẹp… chắc mình bị 'não thích nghi' rồi.","de":"Das Auto sah anfangs so komisch aus, aber neuerdings finde ich es gut… ich glaube, ich habe mich dran gewöhnt."}],"definition":"'뇌'와 오디오 기기를 길들이는 과정을 뜻하는 '에이징(aging)'을 합친 말. 파격적인 자동차·전자기기 디자인을 처음엔 낯설어하다가, 자꾸 보다 보면 뇌가 적응해 점점 괜찮아 보이는 심리 현상을 가리킨다.","definition_i18n":{"en":"A blend of 뇌 (brain) and 에이징 (aging, as in 'breaking in' audio gear) — describes the psychological effect where an unconventional car or gadget design looks strange at first, but starts to look good once your brain gets used to seeing it.","ja":"「뇌(脳)」と、オーディオ機器を鳴らし込む工程を指す「에이징(エイジング)」を合わせた語。斬新な車や家電のデザインを最初は違和感を覚えるが、繰り返し見るうちに脳が慣れて良く見えてくる心理現象を指す。","es":"Mezcla de 뇌 (cerebro) y 에이징 (aging, como en el 'rodaje' de equipos de audio): describe el efecto psicológico por el que un diseño poco convencional de coche o gadget parece raro al principio, pero empieza a gustar cuando el cerebro se acostumbra a verlo.","vi":"Ghép giữa 뇌 (não) và 에이징 (aging, như khi 'chạy rốt-đa' cho thiết bị âm thanh) — mô tả hiệu ứng tâm lý khi một thiết kế xe hơi hay thiết bị điện tử khác thường trông lạ lúc đầu, nhưng dần thấy đẹp khi não quen mắt.","de":"Eine Mischung aus 뇌 (Gehirn) und 에이징 (Aging, wie beim 'Einspielen' von Audiogeräten) — beschreibt den psychologischen Effekt, dass ein unkonventionelles Auto- oder Gerätedesign zunächst befremdlich wirkt, mit der Zeit aber gut aussieht, sobald sich das Gehirn daran gewöhnt hat."}}]$j$::jsonb,
'오디오 애호가들 사이에서 스피커·헤드폰을 계속 틀어 소리가 길드는 과정을 뜻하던 ''에이징''이라는 말을, 디자인에 적응하는 뇌의 반응에 빗대 온라인 커뮤니티에서 쓰기 시작했다. 파격적인 신차·가전 디자인 공개 때마다 반복적으로 쓰이며 자리 잡았다.',
$j${"en":"Borrowed from audiophile jargon, where 에이징 (aging) describes speakers or headphones sounding better the more they are played in — online communities repurposed the word for the brain adapting to a design. It caught on as a recurring reaction whenever a bold new car or appliance design was unveiled.","ja":"スピーカーやヘッドホンを鳴らし込むほど音が良くなる過程を指すオーディオマニア用語「에이징」を、デザインに脳が慣れていく反応に見立ててオンラインコミュニティで使い始めた。斬新な新車や家電デザインの発表のたびに繰り返し使われて定着した。","es":"Tomado de la jerga audiófila, donde 에이징 (aging) describe cómo los altavoces o auriculares suenan mejor cuanto más se usan; las comunidades en línea reutilizaron la palabra para el cerebro adaptándose a un diseño. Se popularizó como reacción recurrente cada vez que se presentaba un diseño atrevido de coche o electrodoméstico.","vi":"Mượn từ tiếng lóng dân chơi âm thanh, nơi 에이징 (aging) mô tả loa hay tai nghe nghe hay hơn khi dùng lâu; các cộng đồng mạng dùng lại từ này cho việc não thích nghi với một thiết kế. Từ này phổ biến như một phản ứng lặp lại mỗi khi có thiết kế xe hơi hay đồ gia dụng táo bạo ra mắt.","de":"Aus dem Audiophilen-Jargon entlehnt, wo 에이징 (Aging) beschreibt, dass Lautsprecher oder Kopfhörer mit der Einspielzeit besser klingen — Online-Communitys übertrugen das Wort auf das Gehirn, das sich an ein Design gewöhnt. Es setzte sich als wiederkehrende Reaktion durch, sooft ein gewagtes neues Auto- oder Gerätedesign vorgestellt wurde."}$j$::jsonb,
'새로 나온 자동차나 전자기기 디자인이 처음엔 낯설다가 점점 익숙해져 괜찮아 보일 때 쓴다. ''뇌이징 됐다'', ''뇌이징 오는 중''처럼 쓴다.',
$j${"en":"Used when a newly revealed car or gadget design looked off at first but is starting to grow on you. Said like '뇌이징 됐다' (I've been brain-aged) or '뇌이징 오는 중' (the brain-aging is kicking in).","ja":"新しく発表された車や家電のデザインが最初は違和感があったのに、だんだん見慣れてよく見えてきたときに使う。「뇌이징 됐다」「뇌이징 오는 중」のように使う。","es":"Se usa cuando el diseño recién revelado de un coche o gadget parecía raro al principio pero te va gustando. Se dice como '뇌이징 됐다' (ya me acostumbré) o '뇌이징 오는 중' (se me está pegando).","vi":"Dùng khi thiết kế xe hơi hay thiết bị mới ra mắt lúc đầu thấy lạ nhưng dần thấy quen mắt và đẹp. Nói như '뇌이징 됐다' (đã quen rồi) hoặc '뇌이징 오는 중' (đang dần quen).","de":"Wird verwendet, wenn ein neu vorgestelltes Auto- oder Gerätedesign zunächst befremdlich wirkte, einem aber allmählich gefällt. Man sagt '뇌이징 됐다' (ich habe mich daran gewöhnt) oder '뇌이징 오는 중' (die Gewöhnung setzt gerade ein)."}$j$::jsonb,
array[]::text[], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Brain-aging (grows on you over time)"},{"lang":"🇯🇵 JA","text":"脳エイジング(見慣れて好きになる現象)"},{"lang":"🇨🇳 ZH","text":"脑适应(越看越顺眼)"},{"lang":"🇻🇳 VI","text":"Não thích nghi (nhìn quen rồi thấy đẹp)"},{"lang":"🇪🇸 ES","text":"Adaptación cerebral (te va gustando con el tiempo)"},{"lang":"🇩🇪 DE","text":"Hirn-Eingewöhnung (wird einem mit der Zeit sympathisch)"}]$j$::jsonb);

commit;
