-- 엠창/느금마 추가 (2026-09-01, 운영자 지시). 극단적 비속어(어머니 비하/모욕)이므로
-- category='slang'(성인 게이트 대상)으로 등록. 삽입 전 웹 검색으로 독립 출처 2개 이상
-- 교차 확인함(나무위키·위키백과 Korean profanity 항목·루리웹 등). 실사용 금지를 usage에
-- 명확히 명시 — 사전 수록 목적은 학습자가 마주쳤을 때 이해하기 위함이지 사용 권장이 아님.

begin;

insert into public.words (id, word, romanization, category, short_desc, short_desc_i18n, pronunciation, meanings, origin, origin_i18n, usage, usage_i18n, related_words, likes, saves, translations) values

('141', '엠창', 'Em-Chang', 'slang', '심한 자기비하·비하성 욕설, 인생 낙오자를 가리키는 비속어',
$j${"en":"A harsh self-deprecating curse now used to call someone a loser","ja":"自虐的な誓いから来た、負け犬を意味する強い罵り言葉","es":"Una maldición autodespectiva ahora usada para llamar perdedor a alguien","vi":"Lời chửi tự hạ thấp bản thân, nay dùng để gọi ai đó là kẻ thất bại","de":"Ein selbstherabsetzender Fluch, der heute jemanden als Verlierer bezeichnet"}$j$::jsonb,
'[엠창]',
$j$[{"type":"명사","examples":[{"kor":"그렇게 쉬운 것도 못 하다니 완전 엠창이네.","eng":"Can't even do something that easy — total loser (em-chang).","ja":"あんな簡単なこともできないなんて完全に엠창だな。","es":"No poder hacer algo tan fácil… eres un perdedor total (em-chang).","vi":"Cái dễ vậy mà không làm được, đúng kiểu thất bại (em-chang).","de":"So etwas Einfaches nicht hinzukriegen — totaler Verlierer (em-chang)."}],"definition":"'이게 거짓말이면 우리 엄마는 창녀다'라는 극단적 자기비하식 맹세 표현의 줄임말('엄창'이 원형). 원래는 이런 맹세를 하는 사람의 처지를 비하하는 뜻이었으나, 많이 쓰이면서 의미가 무뎌져 지금은 '찌질이', '루저', '인생 패배자'와 비슷한 뜻의 심한 비속어로 쓰인다.","definition_i18n":{"en":"Short for '이게 거짓말이면 우리 엄마는 창녀다' (if this is a lie, my mom is a prostitute) — an extreme self-deprecating oath, originally '엄창'. It originally mocked the person swearing it, but through overuse the meaning dulled into a harsh insult roughly equivalent to 'loser' or 'pathetic failure.'","ja":"「이게 거짓말이면 우리 엄마는 창녀다(これが嘘なら俺の母は娼婦だ)」という極端な自虐的な誓いの言葉「엄창」が変化した略語。もとは誓いを立てる人自身を貶める意味だったが、多用されるうちに意味が薄れ、今は「負け犬」「ダメ人間」に近い強い侮辱語として使われる。","es":"Abreviatura de '이게 거짓말이면 우리 엄마는 창녀다' (si esto es mentira, mi madre es una prostituta) — un juramento autodespectivo extremo, originalmente '엄창'. Originalmente se burlaba de quien lo juraba, pero con el uso excesivo el significado se diluyó hasta convertirse en un insulto duro equivalente a 'perdedor' o 'fracasado patético'.","vi":"Viết tắt của '이게 거짓말이면 우리 엄마는 창녀다' (nếu đây là lời nói dối thì mẹ tôi là gái mại dâm) — một lời thề tự hạ thấp cực đoan, ban đầu là '엄창'. Ban đầu nhằm chế giễu chính người thề, nhưng qua lạm dụng nghĩa nhạt dần thành lời sỉ nhục nặng nề tương đương 'kẻ thua cuộc' hay 'kẻ thất bại thảm hại'.","de":"Kurzform für '이게 거짓말이면 우리 엄마는 창녀다' (wenn das eine Lüge ist, ist meine Mutter eine Prostituierte) — ein extremer selbstherabsetzender Schwur, ursprünglich '엄창'. Ursprünglich verspottete es die schwörende Person selbst, doch durch übermäßigen Gebrauch verblasste die Bedeutung zu einer harten Beleidigung, etwa gleichbedeutend mit 'Verlierer' oder 'erbärmlicher Versager'."}}]$j$::jsonb,
'디시인사이드·일간베스트 등 남초 온라인 커뮤니티에서 생긴 자기비하식 맹세 표현 ''엄창''에서 변형됐다. 최초 사용자는 확인되지 않으며, 지나치게 노골적인 욕설이라 커뮤니티 안에서도 순화 표현으로 자주 검열된다.',
$j${"en":"A variant of '엄창,' a self-deprecating oath phrase that emerged on male-dominated online communities like DC Inside and Ilbe. No individual coiner has been confirmed, and because it is such blatant profanity, it is often censored even within those communities.","ja":"DCインサイドや日刊ベストなど男性中心のオンラインコミュニティで生まれた自虐的な誓いの言葉「엄창」の変形。最初に使い始めた人物は確認されておらず、あまりに露骨な罵倒語のため、コミュニティ内でも伏字にされることが多い。","es":"Una variante de '엄창,' una frase de juramento autodespectivo surgida en comunidades en línea dominadas por hombres como DC Inside e Ilbe. No se ha confirmado quién la acuñó, y por ser una grosería tan flagrante, a menudo se censura incluso dentro de esas comunidades.","vi":"Biến thể của '엄창,' một cụm từ thề tự hạ thấp xuất hiện trên các cộng đồng mạng nam giới chiếm đa số như DC Inside và Ilbe. Chưa xác nhận được ai đặt ra, và vì là lời chửi quá trắng trợn nên thường bị kiểm duyệt ngay cả trong các cộng đồng đó.","de":"Eine Variante von '엄창,' einer selbstherabsetzenden Schwurformel, die in männerdominierten Online-Communitys wie DC Inside und Ilbe entstand. Kein einzelner Urheber ist bestätigt, und weil es sich um so unverhohlene Obszönität handelt, wird es selbst innerhalb dieser Communitys oft zensiert."}$j$::jsonb,
'매우 공격적인 비속어로, 상대를 심하게 비하하는 말이다. 실제 대화나 공개적 자리에서 쓰면 안 되고, 이 사전에는 뜻을 알아두어 인터넷에서 마주쳤을 때 이해하기 위한 목적으로만 수록한다.',
$j${"en":"An extremely aggressive insult that harshly demeans someone. Never use it in real conversation or in public — it is included here only so learners can recognize and understand it if they encounter it online.","ja":"相手を強く貶める非常に攻撃的な罵倒語。実際の会話や公の場では絶対に使ってはいけない。この辞典には、インターネットで見かけたときに意味を理解できるようにという目的のみで収録している。","es":"Un insulto extremadamente agresivo que degrada duramente a alguien. Nunca lo uses en una conversación real ni en público — se incluye aquí solo para que los estudiantes puedan reconocerlo y entenderlo si lo encuentran en internet.","vi":"Lời sỉ nhục cực kỳ hung hăng, hạ thấp nặng nề người khác. Tuyệt đối không dùng trong giao tiếp thực tế hay nơi công cộng — từ này được đưa vào đây chỉ để người học nhận ra và hiểu nghĩa khi gặp trên mạng.","de":"Eine extrem aggressive Beleidigung, die jemanden hart herabwürdigt. Niemals in echten Gesprächen oder in der Öffentlichkeit verwenden — es ist hier nur aufgenommen, damit Lernende es online erkennen und verstehen können."}$j$::jsonb,
array[]::text[], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Loser (extremely harsh insult)"},{"lang":"🇯🇵 JA","text":"負け犬(非常に強い罵倒語)"},{"lang":"🇨🇳 ZH","text":"废物(极其严重的骂人话)"},{"lang":"🇻🇳 VI","text":"Kẻ thất bại (lời chửi cực nặng)"},{"lang":"🇪🇸 ES","text":"Perdedor (insulto extremadamente fuerte)"},{"lang":"🇩🇪 DE","text":"Verlierer (extrem harte Beleidigung)"}]$j$::jsonb),

('142', '느금마', 'Neu-Geum-Ma', 'slang', '''너희 엄마''를 뜻하는, 상대 어머니를 모욕하는 게임·인터넷 욕설',
$j${"en":"'Your mom' — a gaming/internet insult about someone's mother","ja":"「お前の母さん」という意味の、ゲーム・ネットでの母親侮辱の罵倒語","es":"'Tu mamá' — un insulto de videojuegos/internet sobre la madre de alguien","vi":"'Mẹ mày' — lời chửi trong game/mạng xúc phạm mẹ người khác","de":"'Deine Mutter' — eine Gaming-/Internet-Beleidigung über jemandes Mutter"}$j$::jsonb,
'[느금마]',
$j$[{"type":"명사","examples":[{"kor":"게임 지고 나서 상대가 느금마라고 욕했어.","eng":"After losing the game, the other player cursed at me with neu-geum-ma.","ja":"試合に負けたら相手に느금마って罵られた。","es":"Después de perder la partida, el otro jugador me insultó con neu-geum-ma.","vi":"Thua trận xong đối thủ chửi mình bằng neu-geum-ma.","de":"Nach der verlorenen Partie hat mich der Gegner mit neu-geum-ma beschimpft."}],"definition":"경상도 사투리로 '너희(느그)'와 '엄마'를 합친 '느금마'가 게임·온라인 채팅에서 상대의 어머니를 모욕하는 욕설로 변질돼 쓰이는 말. 글자 자체의 뜻은 '너희 엄마'일 뿐이지만, 실제로는 상대를 자극하는 심한 비속어로 통한다.","definition_i18n":{"en":"'느금마' combines the Gyeongsang-dialect '느그' (you/your) with '엄마' (mom). It literally just means 'your mom,' but in gaming and online chat it has warped into an insult targeting someone's mother. Though the words themselves are innocuous, in practice it functions as a harsh curse meant to provoke.","ja":"慶尚道方言の「느그(お前ら)」と「엄마(母)」を合わせた語。文字通りには「お前の母さん」という意味に過ぎないが、ゲームやオンラインチャットでは相手の母親を侮辱する罵倒語として定着した。言葉自体は無害でも、実際には相手を挑発する強い罵倒語として機能する。","es":"'느금마' combina el dialecto de Gyeongsang '느그' (ustedes/tu) con '엄마' (mamá). Literalmente solo significa 'tu mamá', pero en juegos y chats en línea se ha transformado en un insulto dirigido a la madre de alguien. Aunque las palabras en sí son inocuas, en la práctica funciona como una maldición dura pensada para provocar.","vi":"'느금마' ghép phương ngữ Gyeongsang '느그' (các bạn/của bạn) với '엄마' (mẹ). Nghĩa đen chỉ là 'mẹ mày', nhưng trong game và chat trực tuyến nó đã biến thành lời sỉ nhục nhắm vào mẹ người khác. Dù bản thân từ ngữ vô hại, trên thực tế nó hoạt động như một lời chửi nặng nhằm khiêu khích.","de":"'느금마' kombiniert den Gyeongsang-Dialektbegriff '느그' (ihr/dein) mit '엄마' (Mama). Wörtlich bedeutet es nur 'deine Mutter', hat sich aber in Gaming- und Online-Chats zu einer Beleidigung entwickelt, die sich gegen die Mutter einer Person richtet. Obwohl die Wörter selbst harmlos sind, fungiert es in der Praxis als harter, provozierender Fluch."}}]$j$::jsonb,
'경상도 방언 ''느그(너희)''와 ''엄마''가 합쳐진 말이 온라인 게임·채팅 문화에서 욕설로 굳어졌다. 특히 게임 중 다툼이 벌어졌을 때 반사적으로 주고받는 욕설로 널리 퍼졌다.',
$j${"en":"Formed from the Gyeongsang dialect word '느그' (you/your) plus '엄마' (mom), and became entrenched as profanity through online gaming and chat culture — especially as a reflexive curse traded back and forth when arguments broke out during games.","ja":"慶尚道方言の「느그(お前ら)」に「엄마(母)」を合わせた語が、オンラインゲームやチャット文化の中で罵倒語として定着した。特にゲーム中に口論になったとき、反射的にやり取りされる罵倒語として広く広まった。","es":"Formado por la palabra dialectal de Gyeongsang '느그' (ustedes/tu) más '엄마' (mamá), se afianzó como grosería a través de la cultura de juegos y chats en línea — especialmente como una maldición reflexiva que se intercambia cuando estallan discusiones durante las partidas.","vi":"Hình thành từ từ phương ngữ Gyeongsang '느그' (các bạn/của bạn) cộng '엄마' (mẹ), và trở thành lời tục tĩu bám rễ qua văn hóa game và chat trực tuyến — đặc biệt như lời chửi phản xạ trao đổi qua lại khi xảy ra cãi vã trong lúc chơi game.","de":"Entstanden aus dem Gyeongsang-Dialektwort '느그' (ihr/dein) plus '엄마' (Mama), etablierte es sich durch Online-Gaming- und Chat-Kultur als Obszönität — besonders als reflexartiger Fluch, der bei Streitigkeiten während des Spielens hin und her geworfen wird."}$j$::jsonb,
'매우 공격적인 비속어로, 상대의 부모를 모욕하는 말이다. 실제 대화에서 절대 써서는 안 되며, 이 사전에는 뜻을 알아두어 게임·인터넷에서 마주쳤을 때 이해하기 위한 목적으로만 수록한다.',
$j${"en":"An extremely aggressive insult targeting someone's parent. Never use it in real conversation — it is included here only so learners can recognize and understand it if they encounter it in gaming or online.","ja":"相手の親を侮辱する非常に攻撃的な罵倒語。実際の会話では絶対に使ってはいけない。この辞典には、ゲームやネットで見かけたときに意味を理解できるようにという目的のみで収録している。","es":"Un insulto extremadamente agresivo dirigido al padre o la madre de alguien. Nunca lo uses en una conversación real — se incluye aquí solo para que los estudiantes puedan reconocerlo y entenderlo si lo encuentran en videojuegos o internet.","vi":"Lời sỉ nhục cực kỳ hung hăng nhắm vào cha mẹ người khác. Tuyệt đối không dùng trong giao tiếp thực tế — từ này được đưa vào đây chỉ để người học nhận ra và hiểu nghĩa khi gặp trong game hay trên mạng.","de":"Eine extrem aggressive Beleidigung, die sich gegen das Elternteil einer Person richtet. Niemals in echten Gesprächen verwenden — es ist hier nur aufgenommen, damit Lernende es beim Gaming oder online erkennen und verstehen können."}$j$::jsonb,
array[]::text[], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Your mom (mother-insult curse)"},{"lang":"🇯🇵 JA","text":"お前の母さん(母親侮辱の罵倒語)"},{"lang":"🇨🇳 ZH","text":"你妈(侮辱母亲的骂人话)"},{"lang":"🇻🇳 VI","text":"Mẹ mày (chửi xúc phạm mẹ)"},{"lang":"🇪🇸 ES","text":"Tu mamá (insulto a la madre)"},{"lang":"🇩🇪 DE","text":"Deine Mutter (Mutterbeleidigung)"}]$j$::jsonb);

commit;
