-- 일못러 추가 (499, 2026-09-14 아침 검수 중 운영자 직접 추가 지시). 일잘러(492)의 반대말.
-- [표준사전: 없음] 출처 ppss.kr '회사는 일잘러만 필요하지 않아'·브런치 '일못러 일잘러'·블라인드 일잘러 vs 일못러 글.
-- 일잘러와 같은 -러 조어라 등장 시점은 따로 특정하지 않았다. 일잘러의 related_words에 이미 일못러가 있어 이 추가로 링크가 살아난다.
--
-- NOTE: filename timestamp differs from the production migration version
-- (MCP apply time becomes the version) — repo-wide convention, see CLAUDE.md.

insert into public.words (id, word, romanization, category, secondary_category, short_desc, short_desc_i18n, pronunciation, meanings, origin, origin_i18n, usage, usage_i18n, related_words, aliases, likes, saves, translations) values
('499', '일못러', 'Il-mot-leo', 'work', null, '일 못하는 사람', '{"en": "Someone who is bad at their job", "ja": "仕事ができない人", "es": "Alguien que trabaja mal", "vi": "Người làm việc kém", "de": "Jemand, der seinen Job nicht hinkriegt"}'::jsonb, '[일몬너]',
 '[{"type": "명사", "definition": "일 + 못 + -러(∼하는 사람). 일잘러의 반대말로, 일의 맥락이나 우선순위를 보지 못해 같이 일하는 사람을 힘들게 하는 사람을 가리킨다. 능력 자체보다 요령과 소통이 부족하다는 뉘앙스가 강하다.", "definition_i18n": {"en": "From 일(work) + 못(badly) + -러(-er). The opposite of 일잘러: someone who misses the context and priorities of the job and makes life hard for the people working with them. The nuance is less about raw ability and more about lacking savvy and communication.", "ja": "일(仕事)+못(できない)+-러(∼する人)。일잘러の反対語で、仕事の文脈や優先順位が見えず、一緒に働く人を困らせる人。能力そのものより要領や意思疎通が足りないというニュアンスが強い。", "es": "De 일(trabajo) + 못(mal) + -러(-dor). Lo contrario de 일잘러: quien no ve el contexto ni las prioridades y complica la vida a sus compañeros. El matiz apunta más a la falta de mano izquierda y comunicación que a la capacidad en sí.", "vi": "Từ 일(công việc) + 못(kém) + -러(người ∼). Trái nghĩa với 일잘러: người không nắm bối cảnh và thứ tự ưu tiên, làm khổ những người làm cùng. Sắc thái nghiêng về thiếu khéo léo và giao tiếp hơn là thiếu năng lực.", "de": "Aus 일(Arbeit) + 못(schlecht) + -러(-er). Das Gegenteil von 일잘러: jemand, der Kontext und Prioritäten übersieht und den Kolleg*innen das Leben schwer macht. Gemeint ist eher fehlendes Gespür und Kommunikation als fehlendes Können."}, "examples": [{"kor": "보고 없이 혼자 진행하다 다 엎었어. 완전 일못러 짓이지.", "eng": "Went ahead alone without reporting and had to scrap it all — classic il-mot-leo move.", "ja": "報告なしで一人で進めて全部やり直し。完全に仕事できない人のやり方だよ。", "es": "Siguió solo sin avisar y hubo que tirarlo todo: típico de alguien que trabaja mal.", "vi": "Tự làm không báo cáo rồi phải làm lại hết, đúng kiểu người làm việc kém.", "de": "Ohne Rückmeldung allein weitergemacht und alles verworfen — typisch für jemanden, der seinen Job nicht hinkriegt."}]}]'::jsonb,
 '일잘러가 퍼지면서 같은 -러 틀로 반대말이 함께 쓰이게 됐다. 직장인 커뮤니티와 칼럼에서 일잘러 vs 일못러 식으로 짝지어 쓰이는 경우가 많다. 따로 등장 시점을 밝힌 자료는 찾지 못했다.',
 '{"en": "As 일잘러 spread, its opposite came into use on the same -러 pattern. Office-worker communities and columns often pair them as 일잘러 vs 일못러. No source dates its first appearance separately.", "ja": "일잘러が広まるにつれ、同じ-러の型で反対語も使われるようになった。会社員コミュニティやコラムで일잘러 vs 일못러と対にして使われることが多い。登場時期を示す資料は見当たらない。", "es": "Al extenderse 일잘러, su contrario se empezó a usar con el mismo molde -러. En foros y columnas de oficinistas suelen emparejarse como 일잘러 vs 일못러. Ninguna fuente fecha su aparición por separado.", "vi": "Khi 일잘러 lan rộng, từ trái nghĩa theo cùng khuôn -러 cũng được dùng theo. Cộng đồng dân văn phòng và các bài bình luận hay đặt cặp 일잘러 vs 일못러. Không có nguồn nào xác định thời điểm xuất hiện riêng.", "de": "Mit der Verbreitung von 일잘러 kam das Gegenteil nach demselben -러-Muster in Gebrauch. In Büro-Communities und Kolumnen stehen sie oft als 일잘러 vs 일못러 nebeneinander. Ein eigenes Entstehungsdatum nennt keine Quelle."}'::jsonb,
 '남을 평가하는 험담이라 본인 앞에서는 절대 쓰지 않는다. 나 오늘 좀 일못러였다처럼 자기 실수를 자조할 때나, 일잘러와 비교하는 글에서 주로 쓴다.',
 '{"en": "It is a put-down, so never say it to someone face to face. It mostly appears as self-mockery, as in 나 오늘 좀 일못러였다 (I was pretty useless at work today), or in pieces comparing it with 일잘러.", "ja": "人を評価する悪口なので本人の前では絶対に使わない。나 오늘 좀 일못러였다(今日はちょっと仕事できなかった)のように自分の失敗を自嘲するときや、일잘러と比べる記事で主に使う。", "es": "Es un comentario despectivo: nunca se dice a la cara. Suele aparecer como autocrítica, 나 오늘 좀 일못러였다 (hoy he trabajado fatal), o en textos que lo comparan con 일잘러.", "vi": "Đây là lời chê người khác nên tuyệt đối không nói trước mặt. Thường dùng để tự giễu, như 나 오늘 좀 일못러였다 (hôm nay mình làm việc hơi tệ), hoặc trong bài so sánh với 일잘러.", "de": "Es ist abwertend — nie jemandem ins Gesicht sagen. Meist als Selbstironie, etwa 나 오늘 좀 일못러였다 (ich war heute ziemlich nutzlos), oder in Texten, die es mit 일잘러 vergleichen."}'::jsonb,
 '{일잘러,고문관,월급 루팡}'::text[], '{}'::text[], 0, 0,
 '[{"lang": "🇺🇸 EN", "text": "Someone useless at work"}, {"lang": "🇯🇵 JA", "text": "仕事ができない人"}, {"lang": "🇨🇳 ZH", "text": "工作能力差的人"}, {"lang": "🇻🇳 VI", "text": "Người làm việc kém"}, {"lang": "🇪🇸 ES", "text": "Alguien que trabaja mal"}, {"lang": "🇩🇪 DE", "text": "Arbeitsniete"}]'::jsonb);

-- 고문관(497)도 일못러와 이어 준다.
update public.words set related_words = array['일잘러','일못러'] where id = '497';
