-- 감다살/감다뒤/얼죽아/알잘딱깔쎈/레게노/이왜진/주먹자로 추가 (2026-09-01, 운영자 지시).
-- candidates 파이프라인 밖 신규 항목이라, 삽입 전 웹 검색으로 7개 전부 독립 출처 2개 이상
-- 교차 확인함(나무위키·SBS뉴스·모두피디아·신조어사전 등).

begin;

insert into public.words (id, word, romanization, category, short_desc, short_desc_i18n, pronunciation, meanings, origin, origin_i18n, usage, usage_i18n, related_words, likes, saves, translations) values

('134', '감다살', 'Gam-Da-Sal', 'new-slang', '예상 못한 놀라운 성과에 감탄할 때 쓰는 말',
$j${"en":"An exclamation for an unexpectedly impressive result","ja":"予想外の見事な結果に感嘆する言葉","es":"Una exclamación por un resultado sorprendentemente impresionante","vi":"Câu cảm thán khi thấy kết quả bất ngờ ấn tượng","de":"Ein Ausruf für ein unerwartet beeindruckendes Ergebnis"}$j$::jsonb,
'[감다살]',
$j$[{"type":"감탄사","examples":[{"kor":"그 짧은 시간에 발표 자료를 그렇게 완성하다니, 완전 감다살이다.","eng":"Finishing that presentation so well in such a short time — total gam-da-sal (skills fully alive).","ja":"あの短時間でプレゼン資料をあんなに仕上げるなんて、完全に감다살だね。","es":"Terminar esa presentación tan bien en tan poco tiempo… es un gam-da-sal total (el talento sigue vivo).","vi":"Làm xong bài thuyết trình hay vậy trong thời gian ngắn thế, đúng là gam-da-sal (sự nhạy bén vẫn còn sống).","de":"So eine Präsentation in so kurzer Zeit hinzukriegen — totaler Gam-da-sal (das Gespür lebt noch)."}],"definition":"'감 다 살았네'의 줄임말. 여기서 '감'은 감각·센스·직감을 뜻하며, 기대하지 않았던 뛰어난 성과나 재치 있는 행동을 보고 감탄할 때 쓴다. 반대로 센스가 완전히 죽었다는 뜻의 '감다죽', 더 강하게 실망을 표현하는 '감다뒤'도 함께 쓰인다.","definition_i18n":{"en":"Short for '감 다 살았네' (the sense/skill is fully alive). Here '감' means intuition, sense, or form — used to marvel at an unexpectedly great result or witty move. Its negative counterparts, '감다죽' (sense totally dead) and the even stronger '감다뒤', are used alongside it.","ja":"「감 다 살았네(感が全部生きてるね)」の略。ここでの「감」は感覚・センス・直感を意味し、予想していなかった見事な成果や機転を見て感嘆するときに使う。反対の否定表現として「감다죽(感が完全に死んだ)」、それをさらに強めた「감다뒤」も一緒に使われる。","es":"Abreviatura de '감 다 살았네' (el sentido/talento está completamente vivo). Aquí '감' significa intuición, sentido o forma — se usa para maravillarse ante un resultado inesperadamente genial o una jugada ingeniosa. Sus contrapartes negativas, '감다죽' (el sentido está muerto) y la más fuerte '감다뒤', se usan junto a ella.","vi":"Viết tắt của '감 다 살았네' (cảm giác/sự nhạy bén vẫn sống trọn vẹn). '감' ở đây nghĩa là trực giác, khiếu thẩm mỹ hay phong độ — dùng để trầm trồ trước kết quả bất ngờ xuất sắc hay cách xử lý khéo léo. Từ trái nghĩa '감다죽' (cảm giác đã chết) và bản mạnh hơn '감다뒤' cũng được dùng song song.","de":"Kurzform für '감 다 살았네' (das Gespür/die Fähigkeit lebt voll und ganz). '감' bedeutet hier Intuition, Gespür oder Form — wird verwendet, um sich über ein unerwartet großartiges Ergebnis oder einen cleveren Zug zu wundern. Die negativen Gegenstücke '감다죽' (Gespür ist tot) und das noch stärkere '감다뒤' werden ebenfalls verwendet."}}]$j$::jsonb,
'2020년대 초반 트위치·아프리카TV 등 인터넷 방송과 온라인 커뮤니티에서 생겨난 말. ''감다죽(감이 다 죽었다)''이 먼저 쓰이다가, 반대 뜻인 ''감다살''이 뒤이어 생겨 짝을 이루게 됐다.',
$j${"en":"A term born in the early 2020s on livestreaming platforms like Twitch and AfreecaTV, as well as online communities. '감다죽' (sense totally dead) came first, and its positive opposite '감다살' followed to form a pair.","ja":"2020年代初頭にTwitchやAfreecaTVなどの配信プラットフォーム、オンラインコミュニティで生まれた語。先に「감다죽(感が完全に死んだ)」が使われ、その後ポジティブな反対語として「감다살」が生まれてペアになった。","es":"Un término nacido a principios de la década de 2020 en plataformas de streaming como Twitch y AfreecaTV, así como en comunidades en línea. '감다죽' (el sentido está muerto) surgió primero, y su opuesto positivo '감다살' llegó después para formar un par.","vi":"Từ ra đời đầu thập niên 2020 trên các nền tảng livestream như Twitch, AfreecaTV và các cộng đồng mạng. '감다죽' (cảm giác đã chết hẳn) xuất hiện trước, rồi từ trái nghĩa tích cực '감다살' ra đời sau để tạo thành cặp.","de":"Ein Begriff, der Anfang der 2020er auf Streaming-Plattformen wie Twitch und AfreecaTV sowie in Online-Communitys entstand. '감다죽' (Gespür ist tot) kam zuerst, und das positive Gegenstück '감다살' folgte, um ein Paar zu bilden."}$j$::jsonb,
'누군가 예상 밖의 센스 있는 대처나 뛰어난 결과물을 보였을 때 ''와 감다살이네''처럼 쓴다.',
$j${"en":"Used when someone shows unexpectedly sharp judgment or a great result — said like '와 감다살이네' (wow, sense fully alive).","ja":"誰かが予想外に鋭い判断や見事な結果を見せたときに「와 감다살이네」のように使う。","es":"Se usa cuando alguien muestra un juicio inesperadamente agudo o un gran resultado, diciendo '와 감다살이네' (vaya, el sentido está bien vivo).","vi":"Dùng khi ai đó thể hiện óc phán đoán sắc bén bất ngờ hay kết quả tuyệt vời, nói như '와 감다살이네' (ồ, sự nhạy bén vẫn còn sống).","de":"Wird verwendet, wenn jemand unerwartet scharfsinniges Urteilsvermögen oder ein großartiges Ergebnis zeigt — man sagt '와 감다살이네' (wow, das Gespür lebt voll)."}$j$::jsonb,
array['감다뒤'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Sense fully alive (impressive result)"},{"lang":"🇯🇵 JA","text":"感覚生きてる(見事な結果)"},{"lang":"🇨🇳 ZH","text":"感觉全活了(超出预期)"},{"lang":"🇻🇳 VI","text":"Cảm giác còn sống (kết quả ấn tượng)"},{"lang":"🇪🇸 ES","text":"El sentido está vivo (resultado genial)"},{"lang":"🇩🇪 DE","text":"Gespür lebt (beeindruckendes Ergebnis)"}]$j$::jsonb),

('135', '감다뒤', 'Gam-Da-Dwi', 'new-slang', '센스가 완전히 없을 때 쓰는 말, ''감다살''의 반대',
$j${"en":"Said when someone's sense is completely gone — the opposite of 감다살","ja":"センスが完全にない人に対して使う、감다살の反対語","es":"Se dice cuando a alguien le falta totalmente el sentido común — lo opuesto a 감다살","vi":"Nói khi ai đó hoàn toàn mất khiếu — từ trái nghĩa của 감다살","de":"Wird gesagt, wenn jemandem jedes Gespür fehlt — das Gegenteil von 감다살"}$j$::jsonb,
'[감다뒤]',
$j$[{"type":"감탄사","examples":[{"kor":"그 상황에서 그런 농담을 하다니… 완전 감다뒤다.","eng":"Cracking a joke like that in that situation… total gam-da-dwi (sense totally dead).","ja":"あの状況でそんな冗談を言うなんて…完全に감다뒤だね。","es":"Soltar ese chiste en esa situación… es un gam-da-dwi total (el tacto está muerto).","vi":"Nói đùa kiểu đó trong tình huống ấy… đúng là gam-da-dwi (sự nhạy cảm chết hẳn rồi).","de":"So einen Witz in dieser Situation zu machen … totaler Gam-da-dwi (das Gespür ist komplett tot)."}],"definition":"'감이 다 뒤졌네'의 줄임말로, '감다죽'보다 더 강한 어감으로 센스나 판단력이 전혀 없어 어이없을 때 쓴다. 긍정적 감탄사인 '감다살'과 짝을 이루는 부정적 표현이다.","definition_i18n":{"en":"Short for '감이 다 뒤졌네' (the sense has completely died). A stronger version of '감다죽', used when someone's judgment or tact is so absent it's absurd. The negative counterpart to the positive exclamation '감다살'.","ja":"「감이 다 뒤졌네(感が完全に死んだ)」の略。「감다죽」よりさらに強い言い方で、判断力やセンスが全くなくて呆れるときに使う。ポジティブな感嘆詞「감다살」と対をなす否定表現。","es":"Abreviatura de '감이 다 뒤졌네' (el sentido ha muerto por completo). Una versión más fuerte de '감다죽', usada cuando el juicio o el tacto de alguien brilla por su ausencia hasta resultar absurdo. La contraparte negativa de la exclamación positiva '감다살'.","vi":"Viết tắt của '감이 다 뒤졌네' (cảm giác đã chết hoàn toàn). Bản mạnh hơn của '감다죽', dùng khi óc phán đoán hay sự tinh tế của ai đó vắng bóng đến mức nực cười. Là từ trái nghĩa tiêu cực của thán từ tích cực '감다살'.","de":"Kurzform für '감이 다 뒤졌네' (das Gespür ist komplett gestorben). Eine stärkere Version von '감다죽', verwendet, wenn jemandem Urteilsvermögen oder Feingefühl so sehr fehlt, dass es absurd wirkt. Das negative Gegenstück zum positiven Ausruf '감다살'."}}]$j$::jsonb,
'''감다살''과 마찬가지로 2020년대 초반 인터넷 방송·SNS·온라인 커뮤니티에서 함께 퍼진 말. ''감다죽''의 더 센 버전으로 생겨났다.',
$j${"en":"Spread together with '감다살' from the early 2020s through livestreaming and social media, as a strengthened variant of '감다죽'.","ja":"「감다살」と同じく2020年代初頭から配信やSNSを通じて広まった、「감다죽」を強めたバリエーション。","es":"Se difundió junto con '감다살' desde principios de la década de 2020 a través del streaming y las redes sociales, como una variante reforzada de '감다죽'.","vi":"Lan truyền cùng với '감다살' từ đầu thập niên 2020 qua livestream và mạng xã hội, như một biến thể mạnh hơn của '감다죽'.","de":"Verbreitete sich zusammen mit '감다살' seit Anfang der 2020er über Livestreaming und soziale Medien, als verstärkte Variante von '감다죽'."}$j$::jsonb,
'누군가 눈치 없거나 센스 없는 행동을 했을 때 ''완전 감다뒤네''처럼 쓴다.',
$j${"en":"Used when someone acts clueless or tactless — said like '완전 감다뒤네' (totally sense-dead).","ja":"誰かが空気を読めなかったりセンスのない行動をしたときに「완전 감다뒤네」のように使う。","es":"Se usa cuando alguien actúa sin tacto o sin darse cuenta de nada, diciendo '완전 감다뒤네' (el sentido está totalmente muerto).","vi":"Dùng khi ai đó vô duyên hay không có mắt nhìn, nói như '완전 감다뒤네' (cảm giác chết hẳn rồi).","de":"Wird verwendet, wenn jemand ahnungslos oder taktlos handelt — man sagt '완전 감다뒤네' (das Gespür ist total tot)."}$j$::jsonb,
array['감다살'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Sense totally dead (no tact at all)"},{"lang":"🇯🇵 JA","text":"感覚死んでる(センスゼロ)"},{"lang":"🇨🇳 ZH","text":"感觉全死了(毫无眼力见)"},{"lang":"🇻🇳 VI","text":"Cảm giác chết hẳn (vô duyên)"},{"lang":"🇪🇸 ES","text":"El sentido está muerto (sin tacto)"},{"lang":"🇩🇪 DE","text":"Gespür tot (kein Feingefühl)"}]$j$::jsonb),

('136', '얼죽아', 'Eol-Juk-A', 'frequently-used', '얼어 죽어도 아이스 음료를 고집한다는 뜻',
$j${"en":"Sticking to iced drinks no matter how cold it is","ja":"どんなに寒くてもアイス飲料を貫くこと","es":"Insistir en bebidas frías sin importar el frío que haga","vi":"Kiên quyết uống đồ đá dù trời lạnh cỡ nào","de":"Auf Eisgetränken bestehen, egal wie kalt es ist"}$j$::jsonb,
'[얼죽아]',
$j$[{"type":"명사","examples":[{"kor":"한겨울에도 아이스 아메리카노 시키는 거 보면 나 진짜 얼죽아인 듯.","eng":"The fact that I order iced americano even in dead winter — I'm definitely eol-juk-a.","ja":"真冬でもアイスアメリカーノ頼むの見ると、私マジで얼죽아かも。","es":"Que pida americano con hielo hasta en pleno invierno… definitivamente soy eol-juk-a.","vi":"Giữa mùa đông mà vẫn gọi americano đá, chắc mình đúng kiểu eol-juk-a.","de":"Dass ich selbst im tiefsten Winter Eiskaffee bestelle — ich bin definitiv eol-juk-a."}],"definition":"'얼어 죽어도 아이스'의 줄임말. 아무리 추운 날씨에도 따뜻한 음료 대신 차가운 아메리카노 등 아이스 음료를 고집하는 사람이나 그런 성향을 가리킨다. 외신에서도 한국 특유의 커피 문화로 소개될 만큼 자리 잡았다. 비슷한 조어로 무조건 신축 아파트를 선호한다는 '얼죽신'도 있다.","definition_i18n":{"en":"Short for '얼어 죽어도 아이스' (iced even if I freeze to death). Refers to someone — or the tendency — of sticking to iced drinks like iced americano even in the coldest weather, instead of switching to something warm. Well-known enough that foreign media has covered it as a distinctly Korean coffee habit. A related term, '얼죽신', means insisting on newly built apartments no matter what.","ja":"「얼어 죽어도 아이스(凍え死んでもアイス)」の略。どんなに寒い季節でも温かい飲み物ではなくアイスアメリカーノなどの冷たい飲み物を貫く人、またはその傾向を指す。海外メディアが韓国特有のコーヒー文化として取り上げるほど広く知られている。関連語に、新築マンションを何が何でも選ぶという意味の「얼죽신」もある。","es":"Abreviatura de '얼어 죽어도 아이스' (helado aunque me muera de frío). Se refiere a alguien —o a la tendencia— de aferrarse a bebidas frías como el americano con hielo incluso en el clima más gélido, en vez de pasarse a algo caliente. Es tan conocido que medios extranjeros lo han cubierto como un hábito cafetero típicamente coreano. Un término relacionado, '얼죽신', significa insistir en apartamentos recién construidos pase lo que pase.","vi":"Viết tắt của '얼어 죽어도 아이스' (chết cóng cũng phải đá). Chỉ người — hay xu hướng — kiên quyết uống đồ đá như americano đá ngay cả khi trời lạnh nhất, thay vì chuyển sang đồ nóng. Nổi tiếng đến mức truyền thông nước ngoài từng đưa tin như một thói quen cà phê đặc trưng của Hàn Quốc. Từ liên quan '얼죽신' nghĩa là nhất quyết chọn chung cư mới xây dù thế nào.","de":"Kurzform für '얼어 죽어도 아이스' (eisgekühlt, auch wenn ich erfriere). Bezeichnet jemanden — oder die Neigung —, selbst bei eisigstem Wetter an Eisgetränken wie Eiskaffee festzuhalten, statt auf etwas Warmes umzusteigen. So bekannt, dass ausländische Medien es als typisch koreanische Kaffeegewohnheit aufgegriffen haben. Ein verwandter Begriff, '얼죽신', bedeutet, unbedingt auf Neubauwohnungen zu bestehen."}}]$j$::jsonb,
'겨울에도 아이스 아메리카노를 마시는 한국인들의 습관을 두고 SNS에서 생긴 말. 외신들이 ''Eoljukah''라고 음차 표기하며 소개할 정도로 널리 퍼졌다.',
$j${"en":"Coined on social media about Koreans' habit of drinking iced americanos even in winter. It spread widely enough that foreign outlets transliterated it as 'Eoljukah' when introducing it.","ja":"冬でもアイスアメリカーノを飲む韓国人の習慣を指してSNSで生まれた語。海外メディアが紹介の際「Eoljukah」と音訳するほど広く知られるようになった。","es":"Acuñado en redes sociales sobre el hábito de los coreanos de beber americano con hielo incluso en invierno. Se difundió tanto que medios extranjeros lo transcribieron como 'Eoljukah' al presentarlo.","vi":"Ra đời trên mạng xã hội nói về thói quen uống americano đá của người Hàn ngay cả mùa đông. Lan rộng đến mức truyền thông nước ngoài phiên âm thành 'Eoljukah' khi giới thiệu.","de":"Entstand in sozialen Medien über die Gewohnheit der Koreaner, selbst im Winter Eiskaffee zu trinken. Verbreitete sich so stark, dass ausländische Medien es bei der Vorstellung als 'Eoljukah' transkribierten."}$j$::jsonb,
'한겨울에도 아이스 음료만 마시는 사람을 보고 ''나 완전 얼죽아야''처럼 쓴다.',
$j${"en":"Used to describe yourself or someone who only drinks iced drinks even in deep winter — said like '나 완전 얼죽아야'.","ja":"真冬でもアイス飲料しか飲まない自分や他人を指して「나 완전 얼죽아야」のように使う。","es":"Se usa para describirte a ti mismo o a alguien que solo bebe cosas frías incluso en pleno invierno, diciendo '나 완전 얼죽아야'.","vi":"Dùng để mô tả bản thân hay ai đó chỉ uống đồ đá kể cả giữa mùa đông, nói như '나 완전 얼죽아야'.","de":"Wird verwendet, um sich selbst oder jemanden zu beschreiben, der selbst im tiefsten Winter nur Eisgetränke trinkt — man sagt '나 완전 얼죽아야'."}$j$::jsonb,
array[]::text[], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Iced no matter how cold (coffee habit)"},{"lang":"🇯🇵 JA","text":"凍えてもアイス(コーヒー習慣)"},{"lang":"🇨🇳 ZH","text":"冻死也要冰(咖啡习惯)"},{"lang":"🇻🇳 VI","text":"Chết cóng cũng phải đá (thói quen cà phê)"},{"lang":"🇪🇸 ES","text":"Helado pase lo que pase (hábito cafetero)"},{"lang":"🇩🇪 DE","text":"Eisgekühlt trotz Kälte (Kaffeegewohnheit)"}]$j$::jsonb),

('137', '알잘딱깔쎈', 'Al-Jal-Ttak-Kkal-Ssen', 'frequently-used', '알아서 잘 딱 깔끔하고 센스있게 처리하라는 뜻',
$j${"en":"Handle it smartly and smoothly without being told how","ja":"指示されなくても気を利かせてうまく処理してという意味","es":"Encárgate de algo con criterio y estilo sin que te lo expliquen","vi":"Tự biết xử lý khéo léo tinh tế mà không cần chỉ dẫn cụ thể","de":"Etwas klug und geschmeidig erledigen, ohne dass man es vorgeben muss"}$j$::jsonb,
'[알잘딱깔쎈]',
$j$[{"type":"부사","examples":[{"kor":"따로 설명 안 할 테니까 알잘딱깔쎈하게 처리해줘.","eng":"I won't explain further, just handle it al-jal-ttak-kkal-ssen (smart and smooth).","ja":"特に説明しないから알잘딱깔쎈にやっといて。","es":"No te voy a explicar más, encárgate de forma al-jal-ttak-kkal-ssen (con criterio y estilo).","vi":"Mình không giải thích thêm đâu, cứ xử lý kiểu al-jal-ttak-kkal-ssen (khéo léo tinh tế) nhé.","de":"Ich erklär's nicht weiter, mach es einfach al-jal-ttak-kkal-ssen (clever und stilvoll)."}],"definition":"'알아서 잘 딱 깔끔하고 센스 있게'의 줄임말. 구체적인 지시 없이도 상황을 파악해 눈치껏 센스 있게 처리해 달라는 뜻으로 쓴다.","definition_i18n":{"en":"Short for '알아서 잘 딱 깔끔하고 센스 있게' (figure it out and handle it neatly and tastefully on your own). Used to ask someone to read the situation and handle it well without needing detailed instructions.","ja":"「알아서 잘 딱 깔끔하고 센스 있게(自分で判断してきちんと洗練されたセンスで)」の略。具体的な指示がなくても状況を読んでセンスよく処理してほしいときに使う。","es":"Abreviatura de '알아서 잘 딱 깔끔하고 센스 있게' (resuélvelo tú mismo, con estilo y buen criterio). Se usa para pedirle a alguien que entienda la situación y la maneje bien sin instrucciones detalladas.","vi":"Viết tắt của '알아서 잘 딱 깔끔하고 센스 있게' (tự biết xử lý gọn gàng và tinh tế). Dùng để nhờ ai đó tự hiểu tình huống và xử lý tốt mà không cần chỉ dẫn chi tiết.","de":"Kurzform für '알아서 잘 딱 깔끔하고 센스 있게' (finde es selbst raus und erledige es sauber und geschmackvoll). Wird verwendet, um jemanden zu bitten, die Situation zu erfassen und sie gut zu handhaben, ohne genaue Anweisungen zu brauchen."}}]$j$::jsonb,
'2018년 6월 트위치·유튜브 스트리머 우왁굳이 생방송 중 시청자들의 뻔한 질문에 답답함을 표하며 ''알아서 잘 딱 깔끔하고 센스 있게''라고 말한 데서 유래했다. 2020년 방탄소년단이 한 신조어 퀴즈에서 이 단어를 언급하면서 더 널리 알려졌다.',
$j${"en":"Traces back to June 2018, when Twitch/YouTube streamer Uwaggud, frustrated by viewers' repetitive questions during a livestream, said 'figure it out and handle it neatly and tastefully.' It became more widely known after BTS mentioned it in a 2020 slang quiz.","ja":"2018年6月、Twitch・YouTubeストリーマーのウワクグッドが配信中、視聴者の代わり映えしない質問にうんざりして「알아서 잘 딱 깔끔하고 센스 있게(自分で判断してきちんと洗練されたセンスで)」と言ったことに由来する。2020年にBTSが新語クイズでこの語に言及したことでさらに広く知られるようになった。","es":"Se remonta a junio de 2018, cuando el streamer de Twitch/YouTube Uwaggud, frustrado por las preguntas repetitivas de los espectadores durante una transmisión, dijo 'resuélvelo tú mismo, con estilo y buen criterio'. Se hizo más conocido después de que BTS lo mencionara en un cuestionario de argot en 2020.","vi":"Bắt nguồn từ tháng 6/2018, khi streamer Twitch/YouTube Uwaggud, bực bội vì khán giả hỏi những câu lặp đi lặp lại trong buổi live, đã nói 'tự biết xử lý gọn gàng và tinh tế'. Trở nên nổi tiếng hơn sau khi BTS nhắc đến từ này trong một trò chơi đố tiếng lóng năm 2020.","de":"Geht zurück auf Juni 2018, als der Twitch/YouTube-Streamer Uwaggud, frustriert über sich wiederholende Zuschauerfragen während eines Livestreams, sagte 'finde es selbst raus und erledige es sauber und geschmackvoll'. Es wurde noch bekannter, nachdem BTS es 2020 in einem Slang-Quiz erwähnte."}$j$::jsonb,
'구체적으로 설명하기 귀찮거나 상대의 눈치를 믿을 때 ''알잘딱깔쎈하게 좀 해줘''처럼 쓴다.',
$j${"en":"Used when you don't want to spell things out and trust the other person's judgment — said like '알잘딱깔쎈하게 좀 해줘'.","ja":"細かく説明したくなかったり相手の判断力を信頼しているときに「알잘딱깔쎈하게 좀 해줘」のように使う。","es":"Se usa cuando no quieres explicarlo todo y confías en el criterio del otro, diciendo '알잘딱깔쎈하게 좀 해줘'.","vi":"Dùng khi không muốn giải thích chi tiết và tin vào óc phán đoán của đối phương, nói như '알잘딱깔쎈하게 좀 해줘'.","de":"Wird verwendet, wenn man nichts genau erklären möchte und dem Urteilsvermögen des anderen vertraut — man sagt '알잘딱깔쎈하게 좀 해줘'."}$j$::jsonb,
array[]::text[], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Handle it smart and smooth"},{"lang":"🇯🇵 JA","text":"気を利かせて上手にやって"},{"lang":"🇨🇳 ZH","text":"灵活妥善地处理"},{"lang":"🇻🇳 VI","text":"Tự xử lý khéo léo tinh tế"},{"lang":"🇪🇸 ES","text":"Encárgate con criterio y estilo"},{"lang":"🇩🇪 DE","text":"Clever und geschmeidig erledigen"}]$j$::jsonb),

('138', '레게노', 'Re-Ge-No', 'frequently-used', '레전드(전설)를 장난스럽게 바꿔 부르는 말',
$j${"en":"A playful respelling of 'legend'","ja":"「レジェンド」を茶目っ気たっぷりに言い換えた言葉","es":"Una forma juguetona de decir 'leyenda'","vi":"Cách nói vui của từ 'huyền thoại' (legend)","de":"Eine spielerische Umschreibung von 'Legende'"}$j$::jsonb,
'[레게노]',
$j$[{"type":"명사","examples":[{"kor":"이번 결승골 완전 레게노다.","eng":"That winning goal was an absolute legeno.","ja":"今回の決勝ゴール完全にレゲノだわ。","es":"Ese gol de la victoria fue un legeno total.","vi":"Bàn thắng quyết định lần này đúng là legeno.","de":"Das Siegtor eben war ein absoluter Legeno."}],"definition":"'레전드(LEGEND)'의 마지막 철자 D를 O로 바꿔 장난스럽게 부르는 인터넷 신조어. 초성만 따서 'ㄹㄱㄴ'라고도 쓴다.","definition_i18n":{"en":"An internet neologism that playfully swaps the final 'D' in 'LEGEND' for an 'O', making 'LEGENO'. Also written using just the initial consonants, 'ㄹㄱㄴ'.","ja":"「LEGEND(レジェンド)」の最後の文字「D」を「O」に変えて茶目っ気たっぷりに言い換えたインターネット新語。初声だけを取った「ㄹㄱㄴ」とも書く。","es":"Un neologismo de internet que cambia juguetonamente la 'D' final de 'LEGEND' por una 'O', formando 'LEGENO'. También se escribe usando solo las consonantes iniciales, 'ㄹㄱㄴ'.","vi":"Từ mới trên mạng đổi vui chữ 'D' cuối trong 'LEGEND' thành 'O', tạo thành 'LEGENO'. Cũng viết tắt bằng phụ âm đầu 'ㄹㄱㄴ'.","de":"Ein Internet-Neologismus, der das abschließende 'D' in 'LEGEND' spielerisch durch ein 'O' ersetzt und so 'LEGENO' ergibt. Wird auch nur mit den Anfangskonsonanten 'ㄹㄱㄴ' geschrieben."}}]$j$::jsonb,
'트위치 스트리머 우왁굳의 마인크래프트 방송에서, 피곤했던 우왁굳 대신 방송을 맡은 아내 엔젤님이 건축물에 쓰인 ''레전드(LEGEND)''를 ''레게노(LEGENO)''로 잘못 읽은 데서 시작됐다. 특유의 어감 덕분에 여러 스트리머 방송으로 퍼지며 ''레전드''를 대신하는 말이 됐다.',
$j${"en":"Originated on Twitch streamer Uwaggud's Minecraft broadcast: when he was too tired to continue and handed the stream to his wife Angel-nim, she misread the word 'LEGEND' written on a structure as 'LEGENO.' Thanks to its catchy sound, it spread from Uwaggud's channel to many other streamers and across the internet as a stand-in for 'legend.'","ja":"Twitchストリーマー、ウワクグッドのマインクラフト配信で生まれた。疲れて配信を続けられなくなったウワクグッドから配信を引き継いだ妻のエンジェルさんが、建築物に書かれた「LEGEND」を「LEGENO」と読み間違えたことがきっかけ。特有の語感のおかげでウワクグッドのチャンネルから他の多くのストリーマー、そしてインターネット全体へと広まり、「レジェンド」の代わりとして使われるようになった。","es":"Se originó en la transmisión de Minecraft del streamer de Twitch Uwaggud: cuando estaba demasiado cansado para continuar y le cedió el stream a su esposa Angel-nim, ella leyó mal la palabra 'LEGEND' escrita en una estructura como 'LEGENO'. Gracias a su sonido pegadizo, se difundió desde el canal de Uwaggud a muchos otros streamers y por todo internet como sustituto de 'leyenda'.","vi":"Bắt nguồn từ buổi live Minecraft của streamer Twitch Uwaggud: khi anh quá mệt không tiếp tục nổi và giao stream cho vợ là Angel-nim, cô đọc nhầm chữ 'LEGEND' viết trên một công trình thành 'LEGENO'. Nhờ âm điệu bắt tai, từ này lan từ kênh của Uwaggud sang nhiều streamer khác và khắp internet, thay thế cho 'huyền thoại'.","de":"Entstand während der Minecraft-Übertragung des Twitch-Streamers Uwaggud: Als er zu müde war, um weiterzumachen, und den Stream an seine Frau Angel-nim übergab, las sie das auf einem Bauwerk geschriebene Wort 'LEGEND' fälschlich als 'LEGENO'. Dank seines eingängigen Klangs verbreitete es sich von Uwaggud Kanal auf viele andere Streamer und das gesamte Internet als Ersatz für 'Legende'."}$j$::jsonb,
'정말 대단하거나 인상적인 일을 보고 ''이건 레게노다''처럼 쓴다.',
$j${"en":"Used for something truly amazing or impressive — said like '이건 레게노다' (this is legeno).","ja":"本当にすごい、印象的なことに対して「이건 레게노다」のように使う。","es":"Se usa para algo verdaderamente asombroso o impresionante, diciendo '이건 레게노다' (esto es legeno).","vi":"Dùng cho điều gì đó thực sự tuyệt vời hay ấn tượng, nói như '이건 레게노다' (đây đúng là legeno).","de":"Wird für etwas wirklich Erstaunliches oder Beeindruckendes verwendet — man sagt '이건 레게노다' (das ist legeno)."}$j$::jsonb,
array['레전드'], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Legeno (playful 'legend')"},{"lang":"🇯🇵 JA","text":"レゲノ(遊び心のあるレジェンド)"},{"lang":"🇨🇳 ZH","text":"Legeno(玩笑版传奇)"},{"lang":"🇻🇳 VI","text":"Legeno (huyền thoại kiểu vui)"},{"lang":"🇪🇸 ES","text":"Legeno (leyenda en broma)"},{"lang":"🇩🇪 DE","text":"Legeno (spielerische Legende)"}]$j$::jsonb),

('139', '이왜진', 'I-Wae-Jin', 'frequently-used', '믿기 힘든 일이 사실로 밝혀졌을 때 놀라는 말',
$j${"en":"Surprise when something unbelievable turns out to be true","ja":"信じ難いことが事実だと判明したときの驚き","es":"Sorpresa cuando algo increíble resulta ser verdad","vi":"Ngạc nhiên khi điều khó tin hóa ra là sự thật","de":"Überraschung, wenn sich etwas Unglaubliches als wahr herausstellt"}$j$::jsonb,
'[이왜진]',
$j$[{"type":"감탄사","examples":[{"kor":"오리너구리가 알을 낳는다는 거 처음 알았을 때 완전 이왜진이었어.","eng":"When I first found out platypuses lay eggs, it was a total 'wait, this is real?' moment.","ja":"カモノハシが卵を産むって初めて知ったとき完全に이왜진だった。","es":"Cuando descubrí que los ornitorrincos ponen huevos, fue un 'espera, ¿esto es real?' total.","vi":"Lúc lần đầu biết thú mỏ vịt đẻ trứng, đúng kiểu 'khoan, cái này có thật á?' luôn.","de":"Als ich zum ersten Mal erfuhr, dass Schnabeltiere Eier legen, war das ein totaler 'Moment, das ist echt?'-Moment."}],"definition":"'이게 왜 진짜임?'의 줄임말. 누가 봐도 가짜이거나 어그로성 제목처럼 보이는 글이 알고 보니 진짜였을 때 놀라움을 표현한다. 초성만 따서 'ㅇㅇㅈ'이라고도 쓴다.","definition_i18n":{"en":"Short for '이게 왜 진짜임?' (why is this actually real?). Used to express surprise when a post that looks obviously fake or clickbait turns out to be genuinely true. Also written with just the initial consonants, 'ㅇㅇㅈ'.","ja":"「이게 왜 진짜임?(これなんで本当なの?)」の略。明らかに偽物やアグロ(釣り)っぽく見える投稿が実は本当だったときの驚きを表す。初声だけを取った「ㅇㅇㅈ」とも書く。","es":"Abreviatura de '이게 왜 진짜임?' (¿por qué esto es real?). Se usa para expresar sorpresa cuando una publicación que parece obviamente falsa o clickbait resulta ser genuinamente cierta. También se escribe solo con las consonantes iniciales, 'ㅇㅇㅈ'.","vi":"Viết tắt của '이게 왜 진짜임?' (sao cái này lại có thật vậy?). Dùng để bày tỏ sự ngạc nhiên khi một bài đăng trông rõ là giả hay câu view hóa ra lại là thật. Cũng viết bằng phụ âm đầu 'ㅇㅇㅈ'.","de":"Kurzform für '이게 왜 진짜임?' (warum ist das echt?). Wird verwendet, um Überraschung auszudrücken, wenn sich ein offensichtlich gefälscht oder als Clickbait wirkender Beitrag als tatsächlich wahr herausstellt. Wird auch nur mit den Anfangskonsonanten 'ㅇㅇㅈ' geschrieben."}}]$j$::jsonb,
'디시인사이드에서 처음 생겨나 다양한 온라인 커뮤니티로 퍼진 말. 알을 낳는 포유류인 오리너구리처럼, 상식을 뒤엎는 사실을 접했을 때의 반응을 표현하는 대표적인 예로 자주 쓰인다.',
$j${"en":"Originated on DC Inside and spread to various online communities. The discovery that the platypus, a mammal, lays eggs is a classic example cited for the reaction — a fact that overturns common sense.","ja":"DCインサイドで生まれ、さまざまなオンラインコミュニティに広まった。哺乳類なのに卵を産むカモノハシの発見が、常識を覆す事実の代表例としてよく挙げられる。","es":"Se originó en DC Inside y se difundió a varias comunidades en línea. El descubrimiento de que el ornitorrinco, un mamífero, pone huevos es un ejemplo clásico citado para esta reacción — un hecho que desafía el sentido común.","vi":"Bắt nguồn từ DC Inside và lan sang nhiều cộng đồng mạng khác. Việc phát hiện thú mỏ vịt, một loài động vật có vú, lại đẻ trứng là ví dụ kinh điển hay được nhắc đến cho phản ứng này — một sự thật lật ngược lẽ thường.","de":"Entstand auf DC Inside und verbreitete sich in verschiedenen Online-Communitys. Die Entdeckung, dass das Schnabeltier, ein Säugetier, Eier legt, ist ein klassisches Beispiel, das für diese Reaktion angeführt wird — eine Tatsache, die den gesunden Menschenverstand auf den Kopf stellt."}$j$::jsonb,
'믿기 어려운 뉴스나 정보가 사실로 확인됐을 때 ''이왜진?''처럼 쓴다.',
$j${"en":"Used when unbelievable news or information turns out to be confirmed true — said like '이왜진?'.","ja":"信じられないニュースや情報が事実だと確認されたときに「이왜진?」のように使う。","es":"Se usa cuando una noticia o información increíble resulta confirmada como cierta, diciendo '이왜진?'.","vi":"Dùng khi tin tức hay thông tin khó tin được xác nhận là sự thật, nói như '이왜진?'.","de":"Wird verwendet, wenn sich eine unglaubliche Nachricht oder Information als bestätigt wahr herausstellt — man sagt '이왜진?'."}$j$::jsonb,
array[]::text[], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Wait, this is real? (shocking truth)"},{"lang":"🇯🇵 JA","text":"え、これ本当なの?(衝撃の事実)"},{"lang":"🇨🇳 ZH","text":"这居然是真的?(反常识真相)"},{"lang":"🇻🇳 VI","text":"Ơ, cái này thật á? (sự thật gây sốc)"},{"lang":"🇪🇸 ES","text":"¿Espera, esto es real? (verdad impactante)"},{"lang":"🇩🇪 DE","text":"Moment, das ist echt? (schockierende Wahrheit)"}]$j$::jsonb),

('140', '주먹자로', 'Ju-Meok-Ja-Ro', 'new-slang', '비만치료제 살 돈이 없어 주먹으로 배를 때리는 셀프 다이어트 드립',
$j${"en":"A joke about punching your own stomach instead of affording Mounjaro","ja":"マウンジャロを打つお金がなく自分の腹を殴るというギャグ","es":"Un chiste sobre golpearte el estómago con el puño en vez de poder pagar Mounjaro","vi":"Trò đùa về việc tự đấm bụng vì không đủ tiền chích Mounjaro","de":"Ein Scherz übers Bauchboxen, weil man sich Mounjaro nicht leisten kann"}$j$::jsonb,
'[주먹자로]',
$j$[{"type":"명사","examples":[{"kor":"야식 참느라 오늘도 주먹자로 중이야.","eng":"Trying to resist late-night snacks, doing my ju-meok-ja-ro (fist-Mounjaro) thing again today.","ja":"夜食我慢するのに今日も주먹자로中。","es":"Aguantando el antojo de comida nocturna, otra vez haciendo mi ju-meok-ja-ro (Mounjaro de puño) hoy.","vi":"Nhịn ăn khuya nên hôm nay lại đấm bụng kiểu ju-meok-ja-ro (Mounjaro nắm đấm).","de":"Um dem nächtlichen Snack zu widerstehen, mache ich heute wieder mein Ju-meok-ja-ro (Faust-Mounjaro)."}],"definition":"비만·당뇨 치료제 '마운자로(Mounjaro)'가 비싸서 맞을 돈이 없다는 걸 자조적으로 표현한 말. 마운자로 대신 스스로 주먹으로 배를 때려 식욕을 참는다는 뜻의 유머러스한 다이어트 신조어다.","definition_i18n":{"en":"A self-deprecating joke about not being able to afford the obesity/diabetes drug 'Mounjaro.' Punning on '주먹' (fist), it means punching your own stomach with your fist to suppress your appetite instead of getting the shot.","ja":"肥満・糖尿病治療薬「マウンジャロ(Mounjaro)」を打つお金がないことを自嘲的に表現した語。「주먹(こぶし)」と掛けて、注射の代わりに自分の腹をこぶしで叩いて食欲を抑えるという、ユーモラスなダイエット新語。","es":"Un chiste autoirónico sobre no poder pagarse el medicamento para la obesidad/diabetes 'Mounjaro'. Jugando con '주먹' (puño), significa golpearse el propio estómago con el puño para reprimir el apetito en lugar de ponerse la inyección.","vi":"Trò đùa tự giễu về việc không đủ tiền chích thuốc trị béo phì/tiểu đường 'Mounjaro'. Chơi chữ với '주먹' (nắm đấm), nghĩa là tự đấm bụng mình bằng nắm đấm để kìm cơn thèm ăn thay vì tiêm thuốc.","de":"Ein selbstironischer Scherz darüber, sich das Adipositas-/Diabetes-Medikament 'Mounjaro' nicht leisten zu können. Ein Wortspiel mit '주먹' (Faust) — bedeutet, sich mit der Faust selbst in den Bauch zu boxen, um den Appetit zu unterdrücken, statt sich die Spritze zu holen."}}]$j$::jsonb,
'체중 감량 효과로 인기를 끈 주사제 ''마운자로''의 높은 비용을 두고 SNS에서 생긴 드립으로, 2025~2026년 관련 신조어 목록에 함께 등장하며 퍼졌다.',
$j${"en":"A joke that emerged on social media about the high cost of the weight-loss injection 'Mounjaro,' which surged in popularity. It spread as part of a wave of 2025-2026 neologisms.","ja":"体重減少効果で人気を集めた注射剤「マウンジャロ」の高い費用をめぐってSNSで生まれたギャグ。2025~2026年の新語ブームの一環として広まった。","es":"Un chiste que surgió en redes sociales sobre el alto costo de la inyección para adelgazar 'Mounjaro', que se disparó en popularidad. Se difundió como parte de una ola de neologismos de 2025-2026.","vi":"Trò đùa ra đời trên mạng xã hội về chi phí cao của mũi tiêm giảm cân 'Mounjaro' đang gây sốt. Lan truyền như một phần của làn sóng từ mới 2025-2026.","de":"Ein Scherz, der in sozialen Medien über die hohen Kosten der Abnehmspritze 'Mounjaro' entstand, die stark an Beliebtheit gewann. Verbreitete sich als Teil einer Welle von Neologismen 2025-2026."}$j$::jsonb,
'다이어트 중 참기 힘들 때 ''나 오늘도 주먹자로 중''처럼 자조적으로 쓴다.',
$j${"en":"Used self-deprecatingly when resisting cravings during a diet — said like '나 오늘도 주먹자로 중' (doing my fist-Mounjaro thing again today).","ja":"ダイエット中に食欲を我慢するときに自嘲的に「나 오늘도 주먹자로 중」のように使う。","es":"Se usa de forma autoirónica al resistir antojos durante una dieta, diciendo '나 오늘도 주먹자로 중' (hoy también haciendo mi Mounjaro de puño).","vi":"Dùng tự giễu khi nhịn thèm ăn lúc ăn kiêng, nói như '나 오늘도 주먹자로 중' (hôm nay lại đấm bụng kiểu Mounjaro nắm đấm).","de":"Wird selbstironisch verwendet, wenn man während einer Diät Heißhunger widersteht — man sagt '나 오늘도 주먹자로 중' (ich mache heute wieder mein Faust-Mounjaro)."}$j$::jsonb,
array[]::text[], 0, 0,
$j$[{"lang":"🇺🇸 EN","text":"Fist-Mounjaro (punching your gut instead)"},{"lang":"🇯🇵 JA","text":"拳マウンジャロ(自分の腹パン)"},{"lang":"🇨🇳 ZH","text":"拳头版Mounjaro(自己捶肚子)"},{"lang":"🇻🇳 VI","text":"Mounjaro nắm đấm (tự đấm bụng)"},{"lang":"🇪🇸 ES","text":"Mounjaro de puño (te golpeas la panza)"},{"lang":"🇩🇪 DE","text":"Faust-Mounjaro (sich selbst in den Bauch boxen)"}]$j$::jsonb);

commit;
