-- 조용한 사직 추가 (id 504) — applied via office inbox 2026-09-14.
-- 대표가 픽셀 오피스 결재함에서 승인해 words INSERT가 이미 DB에 반영됨. 이 파일은 provenance 기록용으로
-- DB의 words 행을 그대로 옮긴 것이며 apply_migration은 하지 않았다(on conflict do nothing으로 재실행 안전).
-- 표제어는 조용한 사직, 조용한 퇴사는 aliases (통용도 비슷 — 2026-09-14 검수에서 보류했던 판단을 오피스 승인으로 확정).
--
-- NOTE: filename timestamp differs from the production migration version
-- (MCP apply time becomes the version) — repo-wide convention, see CLAUDE.md.

begin;

insert into public.words (id, word, romanization, category, secondary_category, short_desc, short_desc_i18n, pronunciation, meanings, origin, origin_i18n, usage, usage_i18n, related_words, aliases, likes, saves, translations) values
('504', '조용한 사직', 'Jo-yong-han Sa-jik', 'work', null, '퇴사는 안 하고 딱 시킨 일만 하기',
 '{"de": "Stille Kündigung — bleiben, aber nur das Nötigste tun", "en": "Quiet quitting — staying, but doing only the minimum", "es": "Renuncia silenciosa: quedarse pero hacer lo mínimo", "ja": "静かな退職 — 辞めずに最低限だけ働く", "vi": "Nghỉ việc trong im lặng — vẫn ở lại nhưng chỉ làm mức tối thiểu"}'::jsonb,
 '[조용한 사직]',
 '[{"type": "명사", "examples": [{"de": "Ich mache gerade stille Kündigung — um sechs klappt der Laptop zu.", "es": "Últimamente estoy en renuncia silenciosa: a las seis cierro el portátil y ya.", "ja": "最近静かな退職中。6時になったら即ノートPC閉じる。", "vi": "Dạo này tớ nghỉ việc trong im lặng, đúng sáu giờ là gập laptop.", "eng": "I am quiet quitting these days — laptop shuts at six, every day.", "kor": "요즘 나 조용한 사직 중이야. 6시 되면 바로 노트북 닫아."}], "definition": "실제로 회사를 그만두지는 않지만 마음은 떠나, 계약된 최소한의 업무만 하고 야근이나 추가 업무를 거절하는 태도. 영어 quiet quitting의 번역어로 조용한 퇴사라고도 하며, 어느 쪽으로 검색해도 같은 말이라 항목은 하나다. 게으름이 아니라 일에 삶을 갈아 넣지 않겠다는 선언에 가깝다.", "definition_i18n": {"de": "Im Job bleiben, innerlich aber ausgestiegen: genau das Vertragliche tun, Überstunden und Zusatzaufgaben ablehnen. Die koreanische Wiedergabe von quiet quitting, auch 조용한 퇴사 geschrieben — beide Suchen führen hierher. Weniger Faulheit als die Ansage, sich nicht aufzuopfern.", "en": "Staying in the job while checking out mentally: doing exactly what the contract requires and declining overtime or extra tasks. The Korean rendering of quiet quitting, also written 조용한 퇴사 — either search brings you here. Less laziness than a declaration that work will not consume your life.", "es": "Seguir en la empresa con la cabeza fuera: hacer solo lo contratado y rechazar horas extra o tareas añadidas. Traducción de quiet quitting, también escrito 조용한 퇴사 — ambas búsquedas llevan aquí. Más que pereza, es declarar que el trabajo no se llevará tu vida.", "ja": "実際には辞めないが心は離れ、契約上の最低限の業務だけをして残業や追加業務を断る態度。英語quiet quittingの訳語で조용한 퇴사とも書き、どちらで検索しても同じ項目。怠けではなく仕事に人生を注ぎ込まないという宣言に近い。", "vi": "Vẫn đi làm nhưng tâm đã rời đi: chỉ làm đúng phần hợp đồng và từ chối tăng ca hay việc phát sinh. Bản dịch của quiet quitting, còn viết là 조용한 퇴사 — tìm kiểu nào cũng ra mục này. Không phải lười, mà là tuyên bố không đánh đổi cuộc sống cho công việc."}}]'::jsonb,
 '2022년 7월 미국 뉴욕의 한 엔지니어가 틱톡 계정 zaidleppelin에 올린 영상으로 전 세계에 퍼졌다(한국 언론 표기는 자료마다 달라 계정명으로 적는다). 배경으로는 코로나19 초기의 대량 해고와 그 뒤 남은 직원들의 과로가 꼽힌다. 한국에서는 워라밸·소확행 같은 기존 흐름과 맞물려 빠르게 정착했고, 원조는 한국이라는 주장이 나올 정도였다.',
 '{"de": "Wurde global durch ein TikTok-Video vom Juli 2022 eines New Yorker Ingenieurs unter dem Account zaidleppelin (koreanische Medien transkribieren den Namen unterschiedlich, daher nur das Handle). Hintergrund: Massenentlassungen der Pandemie und Überlastung der Verbliebenen. In Korea setzte es sich neben 워라밸 und 소확행 rasch durch.", "en": "Went global from a July 2022 TikTok video by a New York engineer posting as zaidleppelin (Korean outlets transliterate the name differently, so only the handle is given). The backdrop: pandemic-era mass layoffs and overwork for those who stayed. In Korea it landed fast alongside 워라밸 and 소확행 — some commentators even argued Korea got there first.", "es": "Se globalizó con un vídeo de TikTok de julio de 2022 de un ingeniero neoyorquino con la cuenta zaidleppelin (la prensa coreana transcribe su nombre de formas distintas, así que solo damos el usuario). Trasfondo: despidos masivos de la pandemia y sobrecarga de los que se quedaron. En Corea cuajó rápido junto a 워라밸 y 소확행.", "ja": "2022年7月、ニューヨークのエンジニアがTikTokアカウントzaidleppelinに投稿した動画で世界に広まった(韓国報道の人名表記は資料ごとに異なるためアカウント名のみ記載)。背景はコロナ初期の大量解雇と残った社員の過労。韓国では워라밸・소확행の流れと重なり急速に定着し、元祖は韓国という主張まで出た。", "vi": "Lan ra toàn cầu từ video TikTok tháng 7/2022 của một kỹ sư New York với tài khoản zaidleppelin (báo Hàn phiên âm tên khác nhau nên chỉ ghi tên tài khoản). Bối cảnh: làn sóng sa thải thời COVID và tình trạng quá tải của người ở lại. Ở Hàn, nó bén rễ nhanh cùng 워라밸 và 소확행."}'::jsonb,
 '본인의 태도를 설명할 때도, 회사가 문제를 진단할 때도 쓴다. 조용한 사직 중이라는 말은 퇴사 의사를 밝힌 게 아니라 앞으로 최소 업무만 하겠다는 뜻이니 오해하지 말 것. 상사 앞에서 대놓고 쓰면 태업 선언으로 들린다.',
 '{"de": "Sowohl zur Selbstbeschreibung als auch in der Firmendiagnose gebraucht. 조용한 사직 중 ist keine Kündigung, sondern die Ansage, künftig nur das Nötigste zu tun. Vor der Chefin klingt es nach Dienst nach Vorschrift.", "en": "Used both by workers describing themselves and by companies diagnosing a problem. Saying you are 조용한 사직 중 is not notice of resignation — it means you will do the minimum from now on. Said in front of a boss it sounds like declaring a work-to-rule.", "es": "Lo usan tanto los trabajadores sobre sí mismos como las empresas al diagnosticar. Decir 조용한 사직 중 no es anunciar tu dimisión: es avisar de que harás lo mínimo. Ante el jefe suena a huelga de celo.", "ja": "本人が自分の態度を説明するときにも、会社が問題を診断するときにも使う。조용한 사직 중は退職の意思表示ではなく今後は最低限だけという意味。上司の前で使えばサボタージュ宣言に聞こえる。", "vi": "Cả người lao động tự mô tả lẫn công ty chẩn đoán vấn đề đều dùng. Nói 조용한 사직 중 không phải là xin nghỉ việc mà là từ giờ chỉ làm mức tối thiểu. Nói trước mặt sếp nghe như tuyên bố lãn công."}'::jsonb,
 '{워라밸,칼퇴,"월급 루팡",퇴준생,소확행}'::text[], '{"조용한 퇴사"}'::text[], 0, 0,
 '[{"lang": "🇺🇸 EN", "text": "Quiet quitting"}, {"lang": "🇯🇵 JA", "text": "静かな退職"}, {"lang": "🇨🇳 ZH", "text": "安静离职"}, {"lang": "🇻🇳 VI", "text": "Nghỉ việc trong im lặng"}, {"lang": "🇪🇸 ES", "text": "Renuncia silenciosa"}, {"lang": "🇩🇪 DE", "text": "Stille Kündigung"}]'::jsonb)
on conflict (id) do nothing;

commit;
